<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>NWH.VehiclePhysics2.Multiplayer.Mirror</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="NWH.VehiclePhysics2">
      <HintPath>..\..\Assemblies\NWH.VehiclePhysics2.dll</HintPath>
    </Reference>
    <Reference Include="Mirror">
      <HintPath>..\..\Assemblies\Mirror.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="NWH.Common">
      <HintPath>..\..\Assemblies\NWH.Common.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>