<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>GameAnalytics</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="UnityEngine">
      <HintPath>..\..\Assemblies\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="Mono.Data.Sqlite">
      <HintPath>..\..\Assemblies\Mono.Data.Sqlite.dll</HintPath>
    </Reference>
    <Reference Include="System.Core" />
    <Reference Include="System.Data" />
  </ItemGroup>
</Project>