namespace Features.NetworkInputModule.Scripts
{
	public enum InputFieldType
	{
		None = 0,
		SpectatorLeft = 1,
		SpectatorRight = 2,
		OpenSettings = 3,
		Movement = 4,
		Jump = 5,
		Rotation = 6,
		ChangeMouseVisibility = 7,
		Crouch = 8,
		Sprint = 9,
		GrabItem = 10,
		DropAllFromArms = 11,
		ArmItemDistanceChange = 12,
		ItemInteract = 13,
		MouseForward = 14,
		BodyEmote = 15,
		FaceEmote = 16,
		HandEmote = 17,
		EmoteNavigation = 18,
		HotBar_1 = 19,
		HotBar_2 = 20,
		HotBar_3 = 21,
		HotBar_4 = 22,
		HotBar_5 = 23,
		HotBar_6 = 24,
		HotBar_7 = 25,
		HotBar_8 = 26,
		HotBar_9 = 27,
		HotBar_0 = 28,
		TurnOnOffOverlay = 29,
		AnyVectorChange = 30,
		UIApply = 31,
		UIApplyWindow = 32,
		UIBack = 33,
		Navigate = 34,
		Submit = 35,
		Cancel = 36,
		Point = 37,
		Click = 38,
		ScrollWheel = 39,
		MiddleClick = 40,
		RightClick = 41,
		TrackedDevicePosition = 42,
		TrackedDeviceOrientation = 43,
		UpgradesBack = 44,
		AdditionalNavigationLeft = 45,
		AdditionalNavigationRight = 46,
		ExtraAdditionalNavigationLeft = 47,
		ExtraAdditionalNavigationRight = 48,
		HoldApply = 49,
		PushToTalk = 50,
		GameplayApply = 51
	}
}
