<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>PlayerTutorialGuideEnemyStateMachine</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="MovementModule">
      <HintPath>..\..\Assemblies\MovementModule.dll</HintPath>
    </Reference>
    <Reference Include="DeadPartsModule">
      <HintPath>..\..\Assemblies\DeadPartsModule.dll</HintPath>
    </Reference>
    <Reference Include="EnemyData">
      <HintPath>..\..\Assemblies\EnemyData.dll</HintPath>
    </Reference>
    <Reference Include="Zenject">
      <HintPath>..\..\Assemblies\Zenject.dll</HintPath>
    </Reference>
    <Reference Include="UnityHFSM">
      <HintPath>..\..\Assemblies\UnityHFSM.dll</HintPath>
    </Reference>
    <Reference Include="Fusion.Runtime">
      <HintPath>..\..\Assemblies\Fusion.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="ItemSpawnerModule">
      <HintPath>..\..\Assemblies\ItemSpawnerModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AIModule">
      <HintPath>..\..\Assemblies\UnityEngine.AIModule.dll</HintPath>
    </Reference>
    <Reference Include="StatsModule.Realization">
      <HintPath>..\..\Assemblies\StatsModule.Realization.dll</HintPath>
    </Reference>
    <Reference Include="EnemyCoreSystems">
      <HintPath>..\..\Assemblies\EnemyCoreSystems.dll</HintPath>
    </Reference>
    <Reference Include="EnemyStatHealth">
      <HintPath>..\..\Assemblies\EnemyStatHealth.dll</HintPath>
    </Reference>
    <Reference Include="PlayerSkinModule.VisibilityHandling">
      <HintPath>..\..\Assemblies\PlayerSkinModule.VisibilityHandling.dll</HintPath>
    </Reference>
    <Reference Include="PlayerSpawnerModule">
      <HintPath>..\..\Assemblies\PlayerSpawnerModule.dll</HintPath>
    </Reference>
    <Reference Include="GrabModule">
      <HintPath>..\..\Assemblies\GrabModule.dll</HintPath>
    </Reference>
    <Reference Include="PlayerCustomization">
      <HintPath>..\..\Assemblies\PlayerCustomization.dll</HintPath>
    </Reference>
    <Reference Include="SkinConfiguration">
      <HintPath>..\..\Assemblies\SkinConfiguration.dll</HintPath>
    </Reference>
    <Reference Include="DeadPartsModuleData">
      <HintPath>..\..\Assemblies\DeadPartsModuleData.dll</HintPath>
    </Reference>
    <Reference Include="Obi">
      <HintPath>..\..\Assemblies\Obi.dll</HintPath>
    </Reference>
    <Reference Include="AnimationModule">
      <HintPath>..\..\Assemblies\AnimationModule.dll</HintPath>
    </Reference>
    <Reference Include="AIModuleStateMachineModule">
      <HintPath>..\..\Assemblies\AIModuleStateMachineModule.dll</HintPath>
    </Reference>
    <Reference Include="PlayerStatsVisualizationModule">
      <HintPath>..\..\Assemblies\PlayerStatsVisualizationModule.dll</HintPath>
    </Reference>
    <Reference Include="TeethModule">
      <HintPath>..\..\Assemblies\TeethModule.dll</HintPath>
    </Reference>
    <Reference Include="EnemySystemsBehavior">
      <HintPath>..\..\Assemblies\EnemySystemsBehavior.dll</HintPath>
    </Reference>
    <Reference Include="EnemyCoreKit">
      <HintPath>..\..\Assemblies\EnemyCoreKit.dll</HintPath>
    </Reference>
    <Reference Include="AIModule">
      <HintPath>..\..\Assemblies\AIModule.dll</HintPath>
    </Reference>
    <Reference Include="Fusion.Common">
      <HintPath>..\..\Assemblies\Fusion.Common.dll</HintPath>
    </Reference>
    <Reference Include="EnemyContexts">
      <HintPath>..\..\Assemblies\EnemyContexts.dll</HintPath>
    </Reference>
    <Reference Include="Zenject-usage">
      <HintPath>..\..\Assemblies\Zenject-usage.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>..\..\Assemblies\UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="EntityStatsModule">
      <HintPath>..\..\Assemblies\EntityStatsModule.dll</HintPath>
    </Reference>
    <Reference Include="SerializableDictionary">
      <HintPath>..\..\Assemblies\SerializableDictionary.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>