<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>WeaponModule</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="AudioServiceModule">
      <HintPath>..\..\Assemblies\AudioServiceModule.dll</HintPath>
    </Reference>
    <Reference Include="Fusion.Runtime">
      <HintPath>..\..\Assemblies\Fusion.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="UniTask">
      <HintPath>..\..\Assemblies\UniTask.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>..\..\Assemblies\UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Cinemachine">
      <HintPath>..\..\Assemblies\Unity.Cinemachine.dll</HintPath>
    </Reference>
    <Reference Include="ScreenShakeModule">
      <HintPath>..\..\Assemblies\ScreenShakeModule.dll</HintPath>
    </Reference>
    <Reference Include="ItemDamageModule">
      <HintPath>..\..\Assemblies\ItemDamageModule.dll</HintPath>
    </Reference>
    <Reference Include="Input">
      <HintPath>..\..\Assemblies\Input.dll</HintPath>
    </Reference>
    <Reference Include="DamageableTrackModule">
      <HintPath>..\..\Assemblies\DamageableTrackModule.dll</HintPath>
    </Reference>
    <Reference Include="PlayerStatesModule">
      <HintPath>..\..\Assemblies\PlayerStatesModule.dll</HintPath>
    </Reference>
    <Reference Include="NetworkInputModule">
      <HintPath>..\..\Assemblies\NetworkInputModule.dll</HintPath>
    </Reference>
    <Reference Include="MultiplayerSessionServices">
      <HintPath>..\..\Assemblies\MultiplayerSessionServices.dll</HintPath>
    </Reference>
    <Reference Include="ObjectDespawnModule">
      <HintPath>..\..\Assemblies\ObjectDespawnModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ParticleSystemModule">
      <HintPath>..\..\Assemblies\UnityEngine.ParticleSystemModule.dll</HintPath>
    </Reference>
    <Reference Include="FMODUnity">
      <HintPath>..\..\Assemblies\FMODUnity.dll</HintPath>
    </Reference>
    <Reference Include="GrabModule">
      <HintPath>..\..\Assemblies\GrabModule.dll</HintPath>
    </Reference>
    <Reference Include="InteractModule">
      <HintPath>..\..\Assemblies\InteractModule.dll</HintPath>
    </Reference>
    <Reference Include="Fusion.Common">
      <HintPath>..\..\Assemblies\Fusion.Common.dll</HintPath>
    </Reference>
    <Reference Include="Zenject-usage">
      <HintPath>..\..\Assemblies\Zenject-usage.dll</HintPath>
    </Reference>
    <Reference Include="Fusion.Log">
      <HintPath>..\..\Assemblies\Fusion.Log.dll</HintPath>
    </Reference>
    <Reference Include="NetworkServices">
      <HintPath>..\..\Assemblies\NetworkServices.dll</HintPath>
    </Reference>
    <Reference Include="ItemsModule">
      <HintPath>..\..\Assemblies\ItemsModule.dll</HintPath>
    </Reference>
    <Reference Include="ItemCollisionModule">
      <HintPath>..\..\Assemblies\ItemCollisionModule.dll</HintPath>
    </Reference>
    <Reference Include="InputModule.Core">
      <HintPath>..\..\Assemblies\InputModule.Core.dll</HintPath>
    </Reference>
    <Reference Include="Unity.InputSystem">
      <HintPath>..\..\Assemblies\Unity.InputSystem.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>