<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>EnemyCoreKit</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Fusion.Runtime">
      <HintPath>..\..\Assemblies\Fusion.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="EnemyData">
      <HintPath>..\..\Assemblies\EnemyData.dll</HintPath>
    </Reference>
    <Reference Include="AIModule">
      <HintPath>..\..\Assemblies\AIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityHFSM">
      <HintPath>..\..\Assemblies\UnityHFSM.dll</HintPath>
    </Reference>
    <Reference Include="EnemyContexts">
      <HintPath>..\..\Assemblies\EnemyContexts.dll</HintPath>
    </Reference>
    <Reference Include="Zenject">
      <HintPath>..\..\Assemblies\Zenject.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AIModule">
      <HintPath>..\..\Assemblies\UnityEngine.AIModule.dll</HintPath>
    </Reference>
    <Reference Include="StatsModule.Realization">
      <HintPath>..\..\Assemblies\StatsModule.Realization.dll</HintPath>
    </Reference>
    <Reference Include="EnemyCoreSystems">
      <HintPath>..\..\Assemblies\EnemyCoreSystems.dll</HintPath>
    </Reference>
    <Reference Include="PlayerSpawnerModule">
      <HintPath>..\..\Assemblies\PlayerSpawnerModule.dll</HintPath>
    </Reference>
    <Reference Include="Fusion.Common">
      <HintPath>..\..\Assemblies\Fusion.Common.dll</HintPath>
    </Reference>
    <Reference Include="EntityStatsModule">
      <HintPath>..\..\Assemblies\EntityStatsModule.dll</HintPath>
    </Reference>
    <Reference Include="Zenject-usage">
      <HintPath>..\..\Assemblies\Zenject-usage.dll</HintPath>
    </Reference>
    <Reference Include="EnemySystemsBehavior">
      <HintPath>..\..\Assemblies\EnemySystemsBehavior.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>