using Features.AIModule.Scripts;
using Features.AIModule.Scripts.ManInShadows;
using Features.AIModuleStateMachine.Scripts.CoinRobSwarmEnemy.Settings;
using Features.AIModuleStateMachine.Scripts.Core.Damageable;
using Features.AIModuleStateMachine.Scripts.HeadcrabEnemy.Settings;
using Features.AerohockeyBeachInteractableModule.Scripts;
using Features.AnalyticsModule.GameAnalyticsJournalingModule.Scripts.Data.Configurations;
using Features.AudioDevicesModule.Scripts;
using Features.AudioModule.Scripts;
using Features.BarBeachInteractableModule.Scripts;
using Features.BasketballHoopModule.Scripts;
using Features.BeachInteractableCommonModule.Scripts;
using Features.BeachPresetModule.Scripts.Core.Configurations;
using Features.BlackjackBeachInteractableModule.Scripts;
using Features.BootstrapModule.Scripts.Core;
using Features.CameraModelModule;
using Features.CartUpgradesModule.Scripts.Core;
using Features.ChestScreamerModule.Scripts;
using Features.ChunkSystem;
using Features.CrocodileGameModule.Scripts;
using Features.CustomFontAssetCreatorModule.Scripts;
using Features.CustomNetworkEventsModule.Scripts;
using Features.DamageableTrackModule.Scripts;
using Features.DeadPartEffectModule.Scripts;
using Features.DeadPartsModule.Data;
using Features.DeadPartsModule.Scripts;
using Features.DeathHandlingModule.Scripts;
using Features.DebugArtSelectorModule.Scripts;
using Features.DeviceModule.Scripts;
using Features.EmotesModule.Scripts;
using Features.EnemiesAppearSoundModule.Scripts;
using Features.EntitiesSoundOcclusionModule.Scripts;
using Features.GamePhasesModule.Scripts;
using Features.GoogleFormModule.Scripts;
using Features.GrabModule.Scripts;
using Features.HingeModule.Scripts;
using Features.ItemDamageModule.Scripts;
using Features.JacuzziBeachInteractableModule.Scripts;
using Features.KrakenModule.Scripts;
using Features.KrakenModule.Scripts.Core;
using Features.LevelGatesModule.Scripts;
using Features.LevelLightModule.Scripts;
using Features.LevelModule.Scripts;
using Features.LevelModule.Scripts.LevelTransition;
using Features.LevelModule.Scripts.RoomVariations;
using Features.LevelObjectSpawnModule.Scripts;
using Features.LineArmModule.Scripts;
using Features.MainMenuModule.Scripts;
using Features.MainMenuModule.Scripts.Credits;
using Features.MainMenuModule.Scripts.Views.Chapters;
using Features.Movement.Scripts;
using Features.MultiplayerSessionServices.Scripts;
using Features.MultiplayerSessionServices.Scripts.NetworkMasterClientTracking;
using Features.NavigationModule.Scripts;
using Features.PlatformStatusRealizationModule.Scripts;
using Features.PlayerSpawner.Scripts;
using Features.PlayerStatesModule.Scripts;
using Features.PlayersEyeFocusModule.Scripts;
using Features.PlayersStatisticsModule.Scripts;
using Features.PostProcessingModule.Scripts;
using Features.QuotaModule.Scripts;
using Features.RandomSoundPlayModule.Scripts;
using Features.RumModule.Scripts;
using Features.SceneTransitionsModule.Scripts;
using Features.SceneTransitionsModule.Scripts.LoadingScreen;
using Features.SelfMicrophonePlayerModule;
using Features.SettingsMenuModule.Scripts;
using Features.SettingsMenuModule.Scripts.Data;
using Features.SettingsMenuModule.Scripts.SettingViews;
using Features.SkinConfiguration.Scripts;
using Features.SlotMachineModule.Scripts.Rewards;
using Features.StatsUsageModule.Scripts.Configurations.EntityStatTypeEntities;
using Features.StatsUsageModule.Scripts.Entities.EntityStatTypeEntities;
using Features.StoreModule.Scripts;
using Features.StreamersSupportModule.Scripts;
using Features.StruggleBarModule.Scripts;
using Features.SynchronizedModelsModule.Scripts;
using Features.TeethModule.Scripts.Tooth;
using Features.ThrowModule.Scripts;
using Features.TipsModule.Scripts.Display;
using Features.TrampolineModule.Scripts;
using Features.TutorialModule.Scripts.Analytics;
using Features.TutorialModule.Scripts.GuideModule;
using Features.TutorialModule.Scripts.TutorialStepsSystem.API.Configurations;
using Features.TutorialModule.Scripts.UITipsModule;
using Features.UIAnimationsModule.Scripts;
using Features.UINavigationModuleRealization.Scripts.BackButton;
using Features.VignetteUIEffectModule.Scripts;
using Features.VoiceControlModule.Scripts;
using Features.VoiceOcclusionModule.Scripts;
using Features.VoiceSpeakersModule.Scripts.MimicVoice;
using Features.WorldTokenModule.Scripts;
using Global.Modules.Localization_Module.Scripts;
using RSG.Muffin.AssetLoaderModule.Core;
using RSG.Muffin.InputDeviceSubmodule.InputDeviceModule.Scripts;
using RSG.Muffin.StatsSubmodule.EntityStatsModule.Scripts.StatsEntity.Configurations;
using RSG.Muffin.SteamSubmodule.SteamModule.Scripts.Data;
using Zenject;

namespace Features.BootstrapModule.Scripts.Installers
{
	public class ConfigurationInstaller : Installer<ConfigurationInstaller>
	{
		private readonly IAssetLoaderFacadeService _assetLoaderFacadeService;

		public ConfigurationInstaller(IAssetLoaderFacadeService assetLoaderService)
		{
			_assetLoaderFacadeService = assetLoaderService;
		}

		public override void InstallBindings()
		{
			ConfigurationBindingBatch configurationBindingBatch = new ConfigurationBindingBatch(base.Container, _assetLoaderFacadeService);
			configurationBindingBatch.Add<MultiplayerSessionConfig>("MultiplayerSessionConfig_Default");
			configurationBindingBatch.Add<NetworkMasterClientTrackingConfiguration>("NetworkMasterClientTrackingConfiguration_Default");
			configurationBindingBatch.Add<ModelsSynchronizerConfiguration>("ModelsSynchronizerConfiguration_Default");
			configurationBindingBatch.Add<EventSynchronizerConfiguration>("EventSynchronizerConfiguration_Default");
			configurationBindingBatch.Add<QuotaConfiguration>("QuotaConfiguration_Default");
			configurationBindingBatch.Add<EnemyDissolveEffectConfiguration>("EnemyDissolveEffectConfiguration_Default");
			configurationBindingBatch.Add<GameStatusesConfiguration>("GameStatusesConfiguration_Default");
			configurationBindingBatch.Add<ChapterResumeRewardConfiguration>("ChapterResumeRewardConfiguration_Default");
			configurationBindingBatch.Add<BasketballConfiguration>("BasketballConfiguration_Default");
			configurationBindingBatch.Add<CrocodileGameConfiguration>("CrocodileGameConfiguration_Default");
			configurationBindingBatch.Add<TrampolineConfiguration>("TrampolineConfiguration_Default");
			configurationBindingBatch.Add<JacuzziBeachInteractableConfiguration>("JacuzziBeachInteractableConfiguration_Default");
			configurationBindingBatch.Add<AerohockeyConfiguration>("AerohockeyConfiguration_Default");
			configurationBindingBatch.Add<BarBeachInteractableConfiguration>("BarBeachInteractableConfiguration_Default");
			configurationBindingBatch.Add<BlackjackConfiguration>("BlackjackConfiguration_Default");
			configurationBindingBatch.Add<MicrophoneConfiguration>("MicrophoneConfiguration_Default");
			configurationBindingBatch.Add<SelfMicrophoneMonitorConfiguration>("SelfMicrophoneMonitorConfiguration_Default");
			configurationBindingBatch.Add<InitialSettingsConfiguration>("InitialSettingsConfiguration_Default");
			configurationBindingBatch.Add<QualitySettingsOptionsConfiguration>("QualitySettingsOptionsConfiguration_Default");
			configurationBindingBatch.Add<PlayerAudioViewConfiguration>("PlayerAudioViewConfiguration_Default");
			configurationBindingBatch.Add<ItemCostReduceConfig>("ItemCostReduceConfig_Default");
			configurationBindingBatch.Add<LevelObjectConfiguration>("LevelObjectConfiguration_Default");
			configurationBindingBatch.AddAs<AccumulativeStatsConfigurationBase<EntityStatType>, EntityAccumulativeStatsConfiguration>("EntityAccumulativeStatsConfiguration_Default");
			configurationBindingBatch.Add<EnemySpawnConfiguration>("EnemySpawnConfiguration_Default");
			configurationBindingBatch.Add<EnemySpawnConfigurationsHolder>("EnemySpawnConfigurationsHolder");
			configurationBindingBatch.Add<EnemyResourceWarmupConfiguration>("EnemyResourceWarmupConfiguration_Default");
			configurationBindingBatch.Add<CoinRobSwarmEnemySettings>("CoinRobSwarmEnemySettings_Default");
			configurationBindingBatch.Add<PlayerStatsConfiguration>("PlayerStatsConfiguration_Default");
			configurationBindingBatch.Add<NavigationConfiguration>("NavigationConfiguration_Default");
			configurationBindingBatch.Add<UIBackButtonPriorityConfiguration>("UIBackButtonPriorityConfiguration_Default");
			configurationBindingBatch.Add<VignetteAffectionConfiguration>("VignetteAffectionConfiguration_Default");
			configurationBindingBatch.Add<CameraWaterLensConfiguration>("CameraWaterLensConfiguration_Default");
			configurationBindingBatch.Add<VignetteUIEffectViewsConfiguration>("VignetteUIEffectViewsConfiguration_Default");
			configurationBindingBatch.Add<HeadcrabVignetteSettings>("HeadcrabVignetteSettings_Default");
			configurationBindingBatch.Add<EnemiesAppearSoundConfiguration>("EnemiesAppearSoundConfiguration");
			configurationBindingBatch.Add<EntitiesSoundOcclusionConfiguration>("EntitiesSoundOcclusionConfiguration_Default");
			configurationBindingBatch.Add<RandomSoundPlayConfiguration>("RandomSoundPlayConfiguration_Default");
			configurationBindingBatch.Add<SkinsConfiguration>("SkinsConfiguration_Default");
			configurationBindingBatch.Add<PlayerStatesConfiguration>("PlayerStatesConfiguration_Default");
			configurationBindingBatch.Add<LevelsConfiguration>("LevelsConfiguration_Default");
			configurationBindingBatch.Add<ChaptersConfiguration>("ChaptersConfiguration_Default");
			configurationBindingBatch.Add<ChapterPreviewConfiguration>("ChapterPreviewConfiguration_Default");
			configurationBindingBatch.Add<ChapterTypeLocalizationConfiguration>("ChapterTypeLocalizationConfiguration_Default");
			configurationBindingBatch.Add<LineArmConfiguration>("LineArmConfiguration_Default");
			configurationBindingBatch.Add<PlayerDeadPartsConfiguration>("PlayerDeadPartsConfiguration_Default");
			configurationBindingBatch.Add<KrakenBehaviourConfiguration>("KrakenBehaviourConfiguration_Default");
			configurationBindingBatch.Add<KrakenHelpThrowConfiguration>("KrakenHelpThrowConfiguration_Default");
			configurationBindingBatch.Add<KrakenAggressiveThrowConfiguration>("KrakenAggressiveThrowConfiguration_Default");
			configurationBindingBatch.Add<EyesTargetsPriorityConfiguration>("EyesTargetsPriorityConfiguration_Default");
			configurationBindingBatch.Add<TipsConfiguration>("TipsConfiguration_Default");
			configurationBindingBatch.Add<GrabDistanceConfiguration>("GrabDistanceConfiguration_Default");
			configurationBindingBatch.Add<EmotesConfiguration>("EmotesConfiguration_Default");
			configurationBindingBatch.Add<DeathConfiguration>("DeathConfiguration_Default");
			configurationBindingBatch.Add<StruggleBarConfiguration>("StruggleBarConfiguration_Default");
			configurationBindingBatch.Add<LevelObjectByLevelTypeConfiguration>("LevelObjectByLevelTypeConfiguration_Default");
			configurationBindingBatch.Add<EmotesMapConfig>("EmotesMapConfig_Default");
			configurationBindingBatch.Add<RegionsPingConfiguration>("RegionsPingConfiguration_Default");
			configurationBindingBatch.Add<LoadingScreenSettings>("LoadingScreenSettings_default");
			configurationBindingBatch.Add<TransitionInstallerConfiguration>("TransitionInstallerConfiguration_Default");
			configurationBindingBatch.Add<LevelTransitionConfiguration>("LevelTransitionConfiguration_Default");
			configurationBindingBatch.Add<VoiceConfig>("VoiceConfig_Default");
			configurationBindingBatch.Add<ScreenShakeByDamageConfiguration>("ScreenShakeByDamageConfiguration_Default");
			configurationBindingBatch.Add<VoiceOcclusionConfiguration>("VoiceOcclusionConfiguration_Default");
			configurationBindingBatch.Add<MimicVoiceCaptureConfiguration>("MimicVoiceCaptureConfiguration_Default");
			configurationBindingBatch.Add<ArtListConfiguration>("ArtListConfiguration_Default");
			configurationBindingBatch.Add<LevelGateConfiguration>("LevelGateConfiguration_Default");
			configurationBindingBatch.Add<GamePhasesConfiguration>("GamePhasesConfiguration_Default");
			configurationBindingBatch.Add<MusicConfiguration>("MusicConfiguration_Default.asset");
			configurationBindingBatch.Add<ToothRemoveByDamageConfiguration>("ToothRemoveByDamageConfiguration_Default");
			configurationBindingBatch.Add<ToothCustomizationConfig>("ToothCustomizationConfig_Default");
			configurationBindingBatch.Add<WorldTokenConfiguration>("WorldTokenConfiguration_Default");
			configurationBindingBatch.Add<FogSwitchConfiguration>("FogSwitchConfiguration_Default");
			configurationBindingBatch.Add<GoogleFormConfiguration>("GoogleFormConfiguration");
			configurationBindingBatch.Add<MainMenuPopupsConfiguration>("MainMenuPopupsConfiguration_Default");
			configurationBindingBatch.Add<GameAnalyticsEventsConfiguration>("GameAnalyticsEventsConfiguration_Default");
			configurationBindingBatch.Add<SessionEndAnalyticsPlacePriorityConfiguration>("SessionEndAnalyticsPlacePriorityConfiguration_Default");
			configurationBindingBatch.Add<SessionEndAnalyticsReasonPriorityConfiguration>("SessionEndAnalyticsReasonPriorityConfiguration_Default");
			configurationBindingBatch.Add<GoldenButtConfiguration>("GoldenButtConfiguration_Default");
			configurationBindingBatch.Add<ButtTexturePresetConfiguration>("ButtTexturePresetConfiguration_Default");
			configurationBindingBatch.Add<StoreLevelConfiguration>("StoreLevelConfiguration_Default");
			configurationBindingBatch.Add<StorePoolConfiguration>("StorePoolConfiguration_Default");
			configurationBindingBatch.Add<ChunkLayersConfiguration>("ChunkLayersConfiguration_Default");
			configurationBindingBatch.Add<RumConfiguration>("RumConfiguration_Default");
			configurationBindingBatch.Add<RumIconsConfiguration>("RumIconsConfiguration_Default");
			configurationBindingBatch.Add<DrunkennessConfiguration>("DrunkennessConfiguration_Default");
			configurationBindingBatch.Add<SpectatorConfiguration>("SpectatorConfiguration_Default");
			configurationBindingBatch.Add<HingeSetupConfiguration>("HingeSetupConfiguration_Default");
			configurationBindingBatch.Add<ChestScreamerConfiguration>("ChestScreamerConfiguration_Default");
			configurationBindingBatch.Add<ScreenModeLocalizationConfiguration>("ScreenModeLocalizationConfiguration_Default");
			configurationBindingBatch.Add<ButtMeshPresetConfiguration>("ButtMeshPresetConfiguration_Default");
			configurationBindingBatch.Add<LanguagesLocalizationConfiguration>("LanguagesLocalizationConfiguration_Default");
			configurationBindingBatch.Add<RoomVariationsConfiguration>("RoomVariationsConfiguration_Default");
			configurationBindingBatch.Add<BeachByLevelsPresetConfiguration>("BeachByLevelsPresetConfiguration_Default");
			configurationBindingBatch.Add<StreamersStandsConfiguration>("StreamersStandsConfiguration_Default");
			configurationBindingBatch.Add<DeviceEditorSwitcherConfiguration>("DeviceEditorSwitcherConfiguration_Default");
			configurationBindingBatch.Add<SteamEditorConfiguration>("SteamEditorConfiguration");
			configurationBindingBatch.Add<PlayerThrowConfiguration>("PlayerThrowConfiguration_Default");
			configurationBindingBatch.Add<BeachInteractableSpawnConfiguration>("BeachInteractableSpawnConfiguration_Default");
			configurationBindingBatch.Add<BeachInteractableIconsConfiguration>("BeachInteractableIconsConfiguration_Default");
			configurationBindingBatch.Add<StatisticsSpawnedItemsIconsConfiguration>("StatisticsSpawnedItemsIconsConfiguration_Default");
			configurationBindingBatch.Add<ManInShadowFlickerConfiguration>("ManInShadowFlickerConfiguration_Default");
			configurationBindingBatch.Add<PlayerRagdollSideEffectsConfiguration>("PlayerRagdollSideEffectsConfiguration_Default");
			configurationBindingBatch.Add<CameraTransitionConfiguration>("CameraTransitionConfiguration_Default");
			configurationBindingBatch.Add<CameraSettingsConfiguration>("CameraSettingsConfiguration_Default");
			configurationBindingBatch.Add<FontsData>("FontsData_Default");
			configurationBindingBatch.Add<UIAnimationsConfig>("UIAnimationsConfig_Default");
			configurationBindingBatch.Add<InputDevicesPriorityConfiguration>("InputDevicesPriorityConfiguration_Default");
			configurationBindingBatch.Add<FlashlightConfiguration>("FlashlightConfiguration_Default");
			configurationBindingBatch.Add<CreditsConfiguration>("CreditsConfiguration_Default");
			configurationBindingBatch.Add<TutorialStepsConfiguration>("TutorialStepsConfiguration_Default");
			configurationBindingBatch.Add<GuideLineConfiguration>("GuideLineConfiguration_Default");
			configurationBindingBatch.Add<TipConfiguration>("TipConfiguration_Default");
			configurationBindingBatch.Add<UITipConfiguration>("UITipConfiguration_Default");
			configurationBindingBatch.Add<TutorialAnalyticsConfiguration>("TutorialAnalyticsConfiguration_Default");
			configurationBindingBatch.Add<SlotMachineRewardConfig>("SlotMachineRewardConfig_Default");
			configurationBindingBatch.Add<CartUpgradeConfiguration>("CartUpgradeConfiguration_Default");
			configurationBindingBatch.LoadAllAndBind();
		}
	}
}
