using Features.AIModule.Data;
using Features.AIModule.Scripts;
using Features.AIModule.Scripts.AttractionZone;
using Features.AIModule.Scripts.ManInShadows;
using Features.AIModuleStateMachine.Scripts.AliveEnemyCount;
using Features.AIModuleStateMachine.Scripts.CoinRobSwarmEnemy;
using Features.AIModuleStateMachine.Scripts.CoinRobSwarmEnemy.RatsHole;
using Features.AIModuleStateMachine.Scripts.Core.Damageable;
using Features.AIModuleStateMachine.Scripts.Core.SafeZones;
using Features.AIModuleStateMachine.Scripts.Data;
using Features.AIModuleStateMachine.Scripts.MimicEnemy;
using Features.AnalyticsModule.GameAnalyticsJournalingModule.Scripts.Data;
using Features.AudioDevicesModule.Scripts;
using Features.AudioDevicesModule.Scripts.PushToTalk.Views;
using Features.BasketballHoopModule.Scripts;
using Features.BeachInteractableCommonModule.Scripts;
using Features.BeachPresetModule.Scripts.Data;
using Features.BigButtBeachInteractableModule.Scripts;
using Features.BrightnessModule.Scripts;
using Features.CameraModelModule;
using Features.CameraModuleRotation.Scripts;
using Features.ChunkSystem;
using Features.ConfirmExitPopupService.Scripts;
using Features.DamageableTrackModule.Scripts;
using Features.DeadPartsModule.Scripts;
using Features.DeathHandlingModule.Scripts;
using Features.DisconnectHandlerModule.Scripts.Installers;
using Features.EmotesModule.Scripts;
using Features.EnemyFearingModule.Scripts;
using Features.FallConstraintModule.Scripts;
using Features.FogModule.Scripts;
using Features.GameModeModule.Scripts;
using Features.GamePauseModule.Scripts;
using Features.GrabModule.Scripts;
using Features.HUDModule.Scripts;
using Features.HeadwearModule.Scripts;
using Features.ItemCollisionModule.Scripts;
using Features.ItemDamageModule.Scripts;
using Features.ItemsModule.Scripts;
using Features.KrakenModule.Scripts;
using Features.KrakenModule.Scripts.Data;
using Features.LevelGatesModule.Data;
using Features.LevelGatesModule.Scripts;
using Features.LevelLightModule.Scripts;
using Features.LevelModule.Scripts;
using Features.LevelModule.Scripts.LevelTransition;
using Features.LevelModule.Scripts.RoomVariations;
using Features.LevelObjectSpawnModule.Scripts;
using Features.LineArmModule.Scripts;
using Features.LineArmModule.Scripts.Data;
using Features.LineArmModule.Scripts.HeavyItemData;
using Features.MainMenuModule.Scripts;
using Features.MouseVisibilityModule.Scripts;
using Features.Movement.Scripts;
using Features.MultiplayerSessionServices.Scripts;
using Features.MusicalInstrumentsModule.Scripts.Core;
using Features.NavigationModule.Scripts;
using Features.NetworkInputModule.Scripts;
using Features.NetworkRandomModule.Scripts;
using Features.NetworkServices.Scripts.InterestManagement;
using Features.NetworkTelemetry.Scripts;
using Features.PlayerGrabModule.Scripts;
using Features.PlayerPresenceModule.Networked;
using Features.PlayerRenderModule.Scripts;
using Features.PlayerSpawner.Scripts;
using Features.PlayerStatesModule.Scripts;
using Features.PlayerStatesModule.Scripts.Views;
using Features.PlayersEyeFocusModule.Scripts;
using Features.PlayersPingModule.Scripts;
using Features.PositionMarkersModule;
using Features.PostProcessingModule.Scripts;
using Features.ProgressSavingModule.Scripts.PlayerInfo;
using Features.QuotaModule.Scripts;
using Features.RagdollModule.Scripts;
using Features.RandomSoundPlayModule.Scripts;
using Features.RumModule.Scripts;
using Features.RuporModule.Scripts;
using Features.ScreenShakeModule.Scripts;
using Features.SessionManagementModule.Models;
using Features.SettingsMenuModule.Scripts;
using Features.SettingsMenuModule.Scripts.Data;
using Features.StatsUsageModule.Scripts.StatsData;
using Features.SteamInviteModule.Scripts;
using Features.StoreModule.Scripts;
using Features.StoreModule.Scripts.MovedToBeachLocal;
using Features.StreamersSupportModule.Scripts;
using Features.StrechArmsModule.Scripts;
using Features.StruggleBarModule.Scripts;
using Features.SwimmingModule.Scripts;
using Features.TeethModule.Scripts.Tooth;
using Features.TutorialModule.Scripts.TutorialCheckpointSystem;
using Features.TutorialModule.Scripts.TutorialStepsSystem;
using Features.TutorialModule.Scripts.TutorialStepsSystem.API.Installers;
using Features.TutorialProgressModule.Scripts;
using Features.UIAnimationsModule.Scripts;
using Features.VignetteUIEffectModule.Scripts;
using Features.VoiceOcclusionModule.Scripts;
using Features.VoiceSpeakersModule.Scripts.Data;
using Features.WeatherModule.Scripts;
using PlayerCustomization;
using PlayerCustomization.Data;
using PlayerCustomization.Networked;
using Zenject;

namespace Features.BootstrapModule.Scripts.Installers
{
	public class DataInstaller : Installer<DataInstaller>
	{
		public override void InstallBindings()
		{
			base.Container.Bind<MultiplayerModel>().AsSingle();
			base.Container.Bind<SessionStateSnapshot>().AsSingle();
			base.Container.Bind<SpawnedVoiceModel>().AsSingle();
			base.Container.Bind<ActiveSpeakerModel>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<PlayerVoiceActivityModel>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<PlayersVoiceEnabledModel>().AsSingle();
			base.Container.Bind<PlayerMovableModel>().AsSingle();
			Installer<GlobalDisconnectInstaller>.Install(base.Container);
			base.Container.BindInterfacesAndSelfTo<PlayerCustomizationModel>().AsSingle();
			base.Container.Bind<PlayerAvatarCosmeticsModel>().AsSingle();
			base.Container.Bind<SessionRewardModel>().AsSingle();
			base.Container.BindInterfacesTo<SessionRewardStoreSpawnSystem>().AsSingle();
			base.Container.Bind<PlayerRenderModel>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<PlayerProfileModel>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<TutorialProgressModel>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<PlayerInfoModel>().AsSingle();
			base.Container.Bind<PlayerSpawnPointsModel>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<LevelContentSpawnRegistry>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<SessionPlayerSeatingService>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<ArmStartsModel>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<ArmStateModel>().AsSingle();
			base.Container.Bind<CameraModel>().AsSingle();
			base.Container.Bind<FieldOfViewModel>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<CustomPlayerEventsSynchronizedModel>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<StoreAnalyticsQuotaSynchronizedModel>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<CurrentWalletSynchronizedModel>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<SteamLobbySyncModel>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<PlayersGatesModelSynchronizedModel>().AsSingle();
			base.Container.Bind<PreDeadTimerModel>().AsSingle();
			base.Container.Bind<StruggleBarModel>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<LevelTransitionTimerSynchronizedModel>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<MouseVisibilityModel>().AsSingle();
			base.Container.Bind<PositionMarkersModel>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<CurrentSettingsModel>().AsSingle();
			base.Container.Bind<NotAppliedSettingsModel>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<GameGlobalNetworkingPause>().AsSingle();
			base.Container.Bind<PlayersVolumeData>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<IdlePoseForArmModel>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<PlayersStatesSynchronizer>().AsSingle();
			base.Container.Bind<LocalBodyHideSuspensionModel>().AsSingle();
			base.Container.Bind<EnemySpawnPointsModel>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<SpawnedPlayersModel>().AsSingle();
			base.Container.Bind<PlayerReboundModel>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<ArmControllersModel>().AsSingle();
			base.Container.Bind<ItemCollisionModel>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<PlayersArmsModel>().AsSingle();
			base.Container.Bind<ArmInputModel>().AsSingle();
			base.Container.Bind<ItemDamageDisplayModel>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<SpawnedItemsModel>().AsSingle();
			base.Container.Bind<LevelSpawnPointsModel>().AsSingle();
			base.Container.Bind<LevelsObjectCostModel>().AsSingle();
			base.Container.Bind<PlayerResurrectionModel>().AsSingle();
			base.Container.Bind<QuotaContainerModel>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<SpawnedEntityStatsModel>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<PlayerDamageablesTrackModel>().AsSingle();
			base.Container.Bind<PlayerDamageAbsorbersModel>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<PLayerGrabOutlineModel>().AsSingle();
			base.Container.Bind<PostProcessingModel>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<CameraWaterLensModel>().AsSingle();
			base.Container.Bind<VignetteUIEffectModel>().AsSingle();
			base.Container.Bind<GameModeModel>().AsSingle();
			base.Container.Bind<LightObjectsModel>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<FlashlightPositionsModel>().AsSingle();
			base.Container.Bind<BeachMaterialSwapModel>().AsSingle();
			base.Container.Bind<BeachIndexedLightModel>().AsSingle();
			base.Container.Bind<BeachPresetRuntimeModel>().AsSingle();
			base.Container.Bind<StandsModel>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<BeachInteractableSpawnModel>().AsSingle();
			base.Container.Bind<PlayerDeadPartModel>().AsSingle();
			base.Container.Bind<HeadwearModel>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<LineArmsModel>().AsSingle();
			base.Container.Bind<LineArmGrabSettingsModel>().AsSingle();
			base.Container.Bind<HeavyItemLocalModel>().AsSingle();
			base.Container.Bind<TableCenterModel>().AsSingle();
			base.Container.Bind<InteractModel>().AsSingle();
			base.Container.Bind<PlayerEyesTargetsModel>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<Features.LevelModule.Scripts.LevelModel>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<ChapterProgressSyncModel>().AsSingle();
			base.Container.Bind<PlayersRagdollModel>().AsSingle();
			base.Container.Bind<EnemyTransformsModel>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<AliveEnemyCountModel>().AsSingle();
			base.Container.Bind<EnemyAttractionZoneListenerModel>().AsSingle();
			base.Container.BindInterfacesTo<EnemyAttractionZoneService>().AsSingle();
			base.Container.Bind<SessionPlayerDeadPartStore>().AsSingle();
			base.Container.Bind<PlayerDeadPartTypes>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<ManInShadowsPointsModel>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<PlayerEnemyInteractionBlocksModel>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<CauldronStealthModel>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<EnemyHeadwearModel>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<RandomSoundPlayedModel>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<KrakenHelpThrowModel>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<KrakenPlayerThrowTrackerModel>().AsSingle();
			base.Container.Bind<KrakenRuntimeModel>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<KrakenAppearTriggerWindowModel>().AsSingle();
			base.Container.Bind<StatsViewModel>().AsSingle();
			base.Container.Bind<PlayerRaycastPointsModel>().AsSingle();
			base.Container.Bind<MimicInterestPointsModel>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<EnemyTargetPositionsModel>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<EnemySafeZoneInteractionPointsModel>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<PlayerGrabSimplePointGrabableModel>().AsSingle();
			base.Container.Bind<RegionsPingModel>().AsSingle();
			base.Container.Bind<EnemySpawnConfigurationModel>().AsSingle();
			base.Container.Bind<FallConstraintModel>().AsSingle();
			base.Container.Bind<LevelGatesModel>().AsSingle();
			base.Container.Bind<RoomTerritoryModel>().AsSingle();
			base.Container.Bind<GateCorridorLightModel>().AsSingle();
			base.Container.Bind<EnemyFearListenerModel>().AsSingle();
			base.Container.Bind<BusyByHeadCrabPlayers>().AsSingle();
			base.Container.Bind<CoinRobSwarmsDataHolder>().AsSingle();
			base.Container.Bind<RatsHoleSpawnPointsModel>().AsSingle();
			base.Container.Bind<CharacterTeethModel>().AsSingle();
			base.Container.Bind<BrightnessModel>().AsSingle();
			base.Container.Bind<SessionAnalyticsModel>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<SessionEndAnalyticsContextModel>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<SentAnalyticsModel>().AsSingle();
			base.Container.Bind<MenuOpenedAnalyticsSourceModel>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<SwimmingFlowPointModel>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<SwimPathGridCache>().AsSingle();
			base.Container.Bind<SwimGridPathfinder>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<RumStatsRewardModel>().AsSingle();
			base.Container.Bind<RumBuffsViewModel>().AsSingle();
			base.Container.Bind<ActiveAOILayerModel>().AsSingle();
			base.Container.Bind<ChunkSystemModel>().AsSingle();
			base.Container.Bind<MicrophoneModel>().AsSingle();
			base.Container.Bind<SpectatorViewModel>().AsSingle();
			base.Container.Bind<RuporModel>().AsSingle();
			base.Container.Bind<VoiceDistanceModel>().AsSingle();
			base.Container.Bind<CameraLocalScreenShakeModel>().AsSingle();
			base.Container.Bind<HeadBobbingModel>().AsSingle();
			base.Container.Bind<MovedToBeachEventClass>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<PlayersPingModel>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<StoreDraftMoneyModel>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<StoreStatsModel>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<StoreSeaterRegistry>().AsSingle();
			base.Container.Bind<SpawnedRoomsModel>().AsSingle();
			base.Container.Bind<LevelRoomsModel>().AsSingle();
			base.Container.Bind<NavigationModel>().AsSingle();
			base.Container.Bind<CardsOnTableModel>().AsSingle();
			base.Container.Bind<TelemetryTrackablesModel>().AsSingle();
			base.Container.Bind<ConfirmPopupModel>().AsSingle();
			base.Container.Bind<BasketballHoopSpawnLocationsModel>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<BigButtBeachCounterProgressModel>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<ChapterProgressModel>().AsSingle();
			base.Container.Bind<FlickerAdjustingModel>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<WeatherModel>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<NetworkRandomRequestModel>().AsSingle();
			base.Container.Bind<EmoteAvailabilityModel>().AsSingle();
			base.Container.Bind<SettingsModel>().AsSingle();
			base.Container.Bind<VirtualCursorModel>().AsSingle();
			base.Container.Bind<PushToTalkViewModel>().AsSingle();
			base.Container.Bind<MainMenuViewModel>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<StoreCustomizationModel>().AsSingle();
			base.Container.Bind<UIAnimationModel>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<FogRegionsModel>().AsSingle();
			base.Container.Bind<EnemyDeathEvent>().AsSingle();
			base.Container.Bind<PlayerResurrectionByPlayerEventClass>().AsSingle();
			base.Container.Bind<BeachInteractableSpawnEvent>().AsSingle();
			base.Container.Bind<StagingBeachInteractableModel>().AsSingle();
			Installer<TutorialDataInstaller>.Install(base.Container);
			base.Container.Bind<CurrentTutorialStepModel>().AsSingle();
			base.Container.BindInterfacesAndSelfTo<TutorialCheckPointModel>().AsSingle();
			base.Container.Bind<MusicalInstrumentModel>().AsSingle();
			base.Container.Bind<ActiveStoreModel>().AsSingle();
			base.Container.Bind<SpawnedRewardsModel>().AsSingle();
		}
	}
}
