using Features.AIModule.Scripts.Installers;
using Features.AIModuleStateMachine.Scripts.CoinRobSwarmEnemy;
using Features.AIModuleStateMachine.Scripts.Enemies.SleeperEnemy;
using Features.AIModuleStateMachine.Scripts.HeadcrabEnemy;
using Features.AIModuleStateMachine.Scripts.Installers;
using Features.AIModuleStateMachine.Scripts.MonkeyPorterEnemy;
using Features.AIModuleStateMachine.Scripts.MonkeyPorterEnemy.Settings;
using Features.AerohockeyBeachInteractableModule.Scripts;
using Features.AnalyticsModule.GameAnalyticsJournalingModule.Scripts.Systems;
using Features.BarBeachInteractableModule.Scripts;
using Features.BasketballHoopModule.Scripts.Installers;
using Features.BeachInteractableCommonModule.Scripts.Installers;
using Features.BeachPresetModule.Scripts.Core.Installers;
using Features.BigButtBeachInteractableModule.Scripts;
using Features.BoosterModule.BoosterModule.Scripts.Installers;
using Features.BootstrapModule.Scripts.Systems;
using Features.CameraModelModule.Installers;
using Features.CartUpgradesModule.Scripts.Installers;
using Features.ChestScreamerModule.Scripts.Installers;
using Features.CrocodileGameModule.Scripts;
using Features.DamageableTrackModule.Scripts.Installers;
using Features.DeadPartsModule.Scripts.Installers;
using Features.DeathHandlingModule.Scripts.Installers;
using Features.DebugArtSelectorModule.Scripts;
using Features.DebugModule.Scripts.CameraDebug;
using Features.EmotesModule.Scripts.Installers;
using Features.EnemiesAppearSoundModule.Scripts.Installers;
using Features.EnemyFearingModule.Scripts.Installers;
using Features.EntitiesSoundOcclusionModule.Scripts.Installers;
using Features.EnvironmentSpawnModule.Scripts.Installers;
using Features.FogModule.Scripts;
using Features.GameOverModule.Scripts.Installers;
using Features.GamePhasesModule.Scripts.Installers;
using Features.GrabModule.Scripts.PhysGrab.CartGrabber;
using Features.GuillotineModule.Scripts;
using Features.ItemDamageModule.Installers;
using Features.ItemsModule.Scripts;
using Features.ItemsModule.Scripts.Installers;
using Features.JacuzziBeachInteractableModule.Scripts;
using Features.KnifeThrowingModule.Scripts.Installers;
using Features.KrakenModule.Scripts.Installers;
using Features.LevelGatesModule.Scripts.Installers;
using Features.LevelModule.Scripts.LevelTransition.Installers;
using Features.LevelModule.Scripts.RoomVariations;
using Features.LevelModule.Scripts.Systems.Analytics;
using Features.LevelObjectSpawnModule.Scripts.Installers;
using Features.LineArmModule.Scripts;
using Features.LineArmModule.Scripts.Installers;
using Features.MainMenuModule.Scripts;
using Features.Movement.Scripts;
using Features.Movement.Scripts.Installers;
using Features.MultiplayerSessionServices.Scripts;
using Features.NavigationModule.Installers;
using Features.NetworkedModelRuntime;
using Features.OcclusionModule.Scripts;
using Features.ParkourBeachInteractableModule.Scripts;
using Features.PlatformStatusRealizationModule.Scripts.Installers;
using Features.PlayerRenderModule.Scripts.Installers;
using Features.PlayerSkinModule.Scripts.Installers;
using Features.PlayerSpawner.Scripts.Installers;
using Features.PlayerStatesModule.Scripts.Installers;
using Features.PlayerStatesModule.Scripts.Systems.StateMachine.Installers;
using Features.PlayerThrowModule.Scripts.Installers;
using Features.PlayersStatisticsModule.Scripts;
using Features.PostProcessingModule.Scripts.Installers;
using Features.QuotaModule.Scripts.Installers;
using Features.RagdollModule.Scripts;
using Features.RandomSoundPlayModule.Scripts.Installers;
using Features.RegenerationModule.Scripts;
using Features.RumModule.Scripts;
using Features.RuporModule.Scripts;
using Features.SessionManagementModule.Installers;
using Features.SessionManagementModule.Models;
using Features.SettingsMenuModule.Scripts;
using Features.SkinChangeModule.Scripts;
using Features.SlotMachineModule.Scripts;
using Features.StatsUsageModule.Scripts.Installers;
using Features.StoreModule.Scripts.Installers;
using Features.StreamersSupportModule.Scripts.Installers;
using Features.StruggleBarModule.Scripts.Installers;
using Features.TeethModule.Scripts.Installers;
using Features.TrampolineModule.Scripts;
using Features.TutorialModule.Scripts.Analytics;
using Features.TutorialModule.Scripts.GuideModule;
using Features.TutorialModule.Scripts.TutorialStepsSystem;
using Features.TutorialModule.Scripts.TutorialStepsSystem.TutorialAdditionalProcessors.Default.Installers;
using Features.TutorialModule.Scripts.TutorialStepsSystem.TutorialStepsFactorySystems.Di;
using Features.TutorialModule.Scripts.UITipsModule;
using Features.ViewSystemModule.Scripts.Installers;
using Features.VignetteUIEffectModule.Scripts.Installers;
using Features.VoiceControlModule.Scripts.VoiceChangeOnStates;
using Features.VoiceOcclusionModule.Scripts;
using Features.WorldTokenModule.Scripts.Installers;
using PlayerCustomization.LobbyAvatar.Systems;
using RSG.Muffin.MVPWindowsUnityUIArchitectureModule.Core;
using UnityEngine;
using Zenject;

namespace Features.BootstrapModule.Scripts.Installers
{
	[CreateAssetMenu(menuName = "Configurations/GameBootstrap/SessionContextInstaller", fileName = "SessionContextInstaller_Default", order = 0)]
	public class SessionContextInstaller : ScriptableObjectInstaller<SessionContextInstaller>
	{
		[SerializeField]
		private MonkeyPorterSpawnConfig _monkeyPorterSpawnConfig;

		public override void InstallBindings()
		{
			Installer<NetworkedModelRuntimeInstaller>.Install(base.Container);
			base.Container.BindInterfacesAndSelfTo<PlayerJoinSourceTrackingSystem>().AsSingle();
			base.Container.BindInterfacesTo<MatchmakingSessionStartAnalyticsSystem>().AsSingle();
			base.Container.BindInterfacesTo<EnemySpawnAnalyticsSystem>().AsSingle();
			Installer<SessionManagementSceneInstaller>.Install(base.Container);
			base.Container.BindInterfacesTo<PlayerAvatarLifecycleAdapter>().AsSingle();
			base.Container.BindInterfacesTo<SessionLevelUiAdapter>().AsSingle();
			base.Container.BindInterfacesTo<SessionEndScreensAdapter>().AsSingle();
			base.Container.BindInterfacesTo<SessionLoadingUiAdapter>().AsSingle();
			base.Container.BindInterfacesTo<SessionPlayerControl>().AsSingle();
			base.Container.BindInterfacesTo<SessionGameplayActivation>().AsSingle();
			base.Container.BindInterfacesTo<SessionVoiceControlAdapter>().AsSingle();
			base.Container.BindInterfacesTo<SessionPlaceReporterAdapter>().AsSingle();
			base.Container.BindInterfacesTo<LevelCompletionObservationAdapter>().AsSingle();
			base.Container.BindInterfacesTo<RunDefeatObservationAdapter>().AsSingle();
			base.Container.BindInterfacesTo<ReconnectPlacementAdapter>().AsSingle();
			base.Container.BindInterfacesTo<ReconnectStateSaver>().AsSingle().NonLazy();
			base.Container.BindInterfacesTo<ShopVotePersistenceAdapter>().AsSingle();
			base.Container.BindInterfacesTo<StoreReadyShopVoteSystem>().AsSingle().NonLazy();
			Installer<UIByContextInstaller>.Install(base.Container);
			Installer<SessionUIInstaller>.Install(base.Container);
			Installer<LobbyUIInstaller>.Install(base.Container);
			base.Container.Bind<WantToLeaveLobbyPopupModel>().AsSingle();
			base.Container.BindInterfacesTo<SessionLobbyWindowSystem>().AsSingle();
			Installer<PlatformStatusRealizationSessionInstaller>.Install(base.Container);
			base.Container.BindInterfacesTo<SessionLobbyChapterProgressSystem>().AsSingle();
			base.Container.BindInterfacesTo<PlayerLobbyAvatarWriterSystem>().AsSingle();
			base.Container.BindInterfacesTo<PlayerLobbyAvatarRosterAdapter>().AsSingle();
			base.Container.BindInterfacesTo<SessionModelScopeActivator>().AsSingle().NonLazy();
			Installer<GameOverModuleInstaller>.Install(base.Container);
			Installer<EnvironmentSpawnInstaller>.Install(base.Container);
			Installer<LevelObjectSpawnInstaller>.Install(base.Container);
			Installer<QuotaModuleInstaller>.Install(base.Container);
			base.Container.BindInterfacesTo<LevelProgressAnalyticsSystem>().AsSingle();
			Installer<BasketballHoopModuleInstaller>.Install(base.Container);
			Installer<PlayerStateModuleInstaller>.Install(base.Container);
			Installer<LocalPlayerStateMachineInstaller>.Install(base.Container);
			base.Container.BindInterfacesAndSelfTo<VoiceStatesSystem>().AsSingle();
			base.Container.BindInterfacesTo<SettingsWindowPauseSystem>().AsSingle();
			Installer<DeathHandlingInstaller>.Install(base.Container);
			Installer<StruggleBarInstaller>.Install(base.Container);
			Installer<UnjoinItemsOnPlayerFallSystemInstaller>.Install(base.Container);
			Installer<StatsInstaller>.Install(base.Container);
			Installer<PlayerSpawnerInstaller>.Install(base.Container);
			Installer<PostProcessingInstaller>.Install(base.Container);
			Installer<ResurrectionInstaller>.Install(base.Container);
			Installer<EnemyFearingInstaller>.Install(base.Container);
			Installer<NavigationModuleInstaller>.Install(base.Container);
			Installer<AIModuleInstaller>.Install(base.Container);
			Installer<EnemiesAppearSoundModuleInstaller>.Install(base.Container);
			Installer<RandomSoundPlayModuleInstaller>.Install(base.Container);
			Installer<AIModuleStateMachineInstaller>.Install(base.Container);
			Installer<CoinRobSwarmEnemySessionInstaller>.Install(base.Container);
			base.Container.Bind<MonkeyPorterSpawnConfig>().FromInstance(_monkeyPorterSpawnConfig).AsSingle();
			Installer<MonkeyPorterSessionInstaller>.Install(base.Container);
			Installer<SleeperEnemySessionInstaller>.Install(base.Container);
			base.Container.BindInterfacesAndSelfTo<SharedMasterMigrationService>().AsSingle().NonLazy();
			Installer<CameraDebugInstaller>.Install(base.Container);
			Installer<DeadPartsInstaller>.Install(base.Container);
			Installer<KrakenModuleInstaller>.Install(base.Container);
			base.Container.BindInterfacesTo<LocalPlayerRagdollSimulationSystem>().AsSingle();
			base.Container.BindInterfacesTo<LocalPlayerFollowService>().AsSingle();
			base.Container.BindInterfacesTo<PlayerFollowRequestSystem>().AsSingle();
			Installer<ThrowModuleInstaller>.Install(base.Container);
			base.Container.BindInterfacesTo<PlayerRagdollMuteSystem>().AsSingle();
			base.Container.BindInterfacesTo<VoiceOcclusionSystem>().AsSingle();
			base.Container.Bind<OcclusionSettings>().AsSingle();
			base.Container.BindInterfacesTo<RoomOcclusionSystem>().AsSingle();
			base.Container.BindInterfacesTo<GpuOcclusionBlendGuardSystem>().AsSingle();
			Installer<MovementInstaller>.Install(base.Container);
			Installer<PlayerSkinInstaller>.Install(base.Container);
			Installer<EmotesModuleInstaller>.Install(base.Container);
			Installer<LevelTransitionModuleInstaller>.Install(base.Container);
			Installer<ChestScreamerInstaller>.Install(base.Container);
			Installer<DamageableTrackModuleInstaller>.Install(base.Container);
			base.Container.BindInterfacesTo<ArtApplierService>().AsSingle();
			Installer<LevelGatesInstaller>.Install(base.Container);
			Installer<VignetteUIEffectModuleInstaller>.Install(base.Container);
			Installer<HeadCrabVignetteInstaller>.Install(base.Container);
			Installer<GamePhasesModuleInstaller>.Install(base.Container);
			Installer<WorldTokenModuleInstaller>.Install(base.Container);
			Installer<LineArmInstaller>.Install(base.Container);
			Installer<BoosterModuleInstaller>.Install(base.Container);
			Installer<RumInstaller>.Install(base.Container);
			Installer<CartUpgradesInstaller>.Install(base.Container);
			Installer<StoreModuleInstaller>.Install(base.Container);
			Installer<RuporInteractionInstaller>.Install(base.Container);
			base.Container.Bind<CartItemAddedEventClass>().AsSingle();
			base.Container.BindInterfacesTo<CartPopupCostSystem>().AsSingle();
			base.Container.Bind<BigButtBeachCounterChangedEventClass>().AsSingle();
			base.Container.BindInterfacesTo<BigButtBeachCounterPopupSystem>().AsSingle();
			base.Container.Bind<BigButtBeachGrabClickedEventClass>().AsSingle();
			base.Container.Bind<BigButtBeachExternalGrabEventClass>().AsSingle();
			base.Container.BindInterfacesTo<BigButtBeachGrabClickPopupSystem>().AsSingle();
			base.Container.BindInterfacesTo<RegenerationSystem>().AsSingle();
			Installer<ItemsModuleInstaller>.Install(base.Container);
			Installer<BeachPresetModuleInstaller>.Install(base.Container);
			Installer<StreamersSupportModuleInstaller>.Install(base.Container);
			Installer<ItemDamageInstaller>.Install(base.Container);
			Installer<TeethCustomizationInstaller>.Install(base.Container);
			Installer<LevelRoomsInstaller>.Install(base.Container);
			Installer<GuillotineModuleInstaller>.Install(base.Container);
			Installer<SlotMachineModuleInstaller>.Install(base.Container);
			Installer<CrocodileGameModuleInstaller>.Install(base.Container);
			Installer<ParkourBeachInteractableModuleInstaller>.Install(base.Container);
			Installer<JacuzziBeachInteractableModuleInstaller>.Install(base.Container);
			Installer<AerohockeyBeachInteractableModuleInstaller>.Install(base.Container);
			Installer<BarBeachInteractableModuleInstaller>.Install(base.Container);
			Installer<TrampolineModuleInstaller>.Install(base.Container);
			Installer<SkinChangeInstaller>.Install(base.Container);
			Installer<KnifeThrowingTableInstaller>.Install(base.Container);
			Installer<BeachInteractableCommonInstaller>.Install(base.Container);
			Installer<PlayerRenderModuleInstaller>.Install(base.Container);
			Installer<CameraModelModuleInstaller>.Install(base.Container);
			Installer<PlayersStatisticsInstaller>.Install(base.Container);
			Installer<EntitiesSoundOcclusionInstaller>.Install(base.Container);
			Installer<TutorialFactorySystemsInstaller>.Install(base.Container);
			Installer<LocationTutorialSystemInstaller>.Install(base.Container);
			Installer<BaseTutorialAdditionalProvessorsInstaller>.Install(base.Container);
			Installer<GuideModuleInstaller>.Install(base.Container);
			Installer<UITipsModuleInstaller>.Install(base.Container);
			Installer<TutorialAnalyticsInstaller>.Install(base.Container);
			Installer<FogModuleInstaller>.Install(base.Container);
		}
	}
}
