internal sealed class JbFlhsYYjsRqDruEheImUOWwxUAr
{
	public static readonly LLThLPMLZOEcDZpxspOYGuElNwOT MnGdYWwnFIUfBypdTNeanrJvtLLg = HmxTdvPgICdUKgpGRAgkBcpOZVBE.sIJeWLuCKrkFAyGatWlBhBIvefteA(RMdkYNRVGlZjQwxYveGlUGKwBsqB.DeviceNotConnected);
}
