<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SettingsMenuModule.Data</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="Localization">
      <HintPath>..\..\Assemblies\Localization.dll</HintPath>
    </Reference>
    <Reference Include="SavingSystemModule">
      <HintPath>..\..\Assemblies\SavingSystemModule.dll</HintPath>
    </Reference>
    <Reference Include="SavingModule">
      <HintPath>..\..\Assemblies\SavingModule.dll</HintPath>
    </Reference>
    <Reference Include="DeviceModule.DeviceData">
      <HintPath>..\..\Assemblies\DeviceModule.DeviceData.dll</HintPath>
    </Reference>
    <Reference Include="Fusion.Realtime">
      <HintPath>..\..\Assemblies\Fusion.Realtime.dll</HintPath>
    </Reference>
    <Reference Include="SerializableDictionary">
      <HintPath>..\..\Assemblies\SerializableDictionary.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>