<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SessionManagement.Installers</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="LevelModule">
      <HintPath>..\..\Assemblies\LevelModule.dll</HintPath>
    </Reference>
    <Reference Include="SessionManagement.Runtime">
      <HintPath>..\..\Assemblies\SessionManagement.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="MultiplayerSessionServices">
      <HintPath>..\..\Assemblies\MultiplayerSessionServices.dll</HintPath>
    </Reference>
    <Reference Include="NetworkRandomModule">
      <HintPath>..\..\Assemblies\NetworkRandomModule.dll</HintPath>
    </Reference>
    <Reference Include="UniTask">
      <HintPath>..\..\Assemblies\UniTask.dll</HintPath>
    </Reference>
    <Reference Include="StoreModule">
      <HintPath>..\..\Assemblies\StoreModule.dll</HintPath>
    </Reference>
    <Reference Include="PlayerStatesModule">
      <HintPath>..\..\Assemblies\PlayerStatesModule.dll</HintPath>
    </Reference>
    <Reference Include="Zenject">
      <HintPath>..\..\Assemblies\Zenject.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="Fusion.Runtime">
      <HintPath>..\..\Assemblies\Fusion.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="SerializableDictionary">
      <HintPath>..\..\Assemblies\SerializableDictionary.dll</HintPath>
    </Reference>
    <Reference Include="SessionManagement.Presence">
      <HintPath>..\..\Assemblies\SessionManagement.Presence.dll</HintPath>
    </Reference>
    <Reference Include="SessionManagement.Gate">
      <HintPath>..\..\Assemblies\SessionManagement.Gate.dll</HintPath>
    </Reference>
    <Reference Include="WeatherModule.Contracts">
      <HintPath>..\..\Assemblies\WeatherModule.Contracts.dll</HintPath>
    </Reference>
    <Reference Include="WeatherModule">
      <HintPath>..\..\Assemblies\WeatherModule.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>