<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SpecialTagsProcessor</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="SpecialTagsProcessor.Configurations">
      <HintPath>..\..\Assemblies\SpecialTagsProcessor.Configurations.dll</HintPath>
    </Reference>
    <Reference Include="SpecialTagsProcessor.API">
      <HintPath>..\..\Assemblies\SpecialTagsProcessor.API.dll</HintPath>
    </Reference>
    <Reference Include="Zenject">
      <HintPath>..\..\Assemblies\Zenject.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>