<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>InputDeviceModuleRealization</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="NetworkInputModule">
      <HintPath>..\..\Assemblies\NetworkInputModule.dll</HintPath>
    </Reference>
    <Reference Include="InputModule.Core">
      <HintPath>..\..\Assemblies\InputModule.Core.dll</HintPath>
    </Reference>
    <Reference Include="Unity.InputSystem">
      <HintPath>..\..\Assemblies\Unity.InputSystem.dll</HintPath>
    </Reference>
    <Reference Include="Input">
      <HintPath>..\..\Assemblies\Input.dll</HintPath>
    </Reference>
    <Reference Include="Zenject">
      <HintPath>..\..\Assemblies\Zenject.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>