<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>ConditionalExpression</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net35</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="PlayMaker">
      <HintPath>..\..\Assemblies\PlayMaker.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>..\..\Assemblies\UnityEngine.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>