<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>ItemDamageModule</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="ItemCollisionModule">
      <HintPath>..\..\Assemblies\ItemCollisionModule.dll</HintPath>
    </Reference>
    <Reference Include="Fusion.Runtime">
      <HintPath>..\..\Assemblies\Fusion.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="UniTask">
      <HintPath>..\..\Assemblies\UniTask.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="MultiplayerSessionServices">
      <HintPath>..\..\Assemblies\MultiplayerSessionServices.dll</HintPath>
    </Reference>
    <Reference Include="ScreenShakeModule">
      <HintPath>..\..\Assemblies\ScreenShakeModule.dll</HintPath>
    </Reference>
    <Reference Include="AudioServiceModule">
      <HintPath>..\..\Assemblies\AudioServiceModule.dll</HintPath>
    </Reference>
    <Reference Include="SerializableDictionary">
      <HintPath>..\..\Assemblies\SerializableDictionary.dll</HintPath>
    </Reference>
    <Reference Include="ItemsModule">
      <HintPath>..\..\Assemblies\ItemsModule.dll</HintPath>
    </Reference>
    <Reference Include="GameUpdaterModule">
      <HintPath>..\..\Assemblies\GameUpdaterModule.dll</HintPath>
    </Reference>
    <Reference Include="CameraModel">
      <HintPath>..\..\Assemblies\CameraModel.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>..\..\Assemblies\Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>..\..\Assemblies\UnityEngine.UIModule.dll</HintPath>
    </Reference>
    <Reference Include="DOTween">
      <HintPath>..\..\Assemblies\DOTween.dll</HintPath>
    </Reference>
    <Reference Include="Zenject-usage">
      <HintPath>..\..\Assemblies\Zenject-usage.dll</HintPath>
    </Reference>
    <Reference Include="CustomNetworkEventsModule">
      <HintPath>..\..\Assemblies\CustomNetworkEventsModule.dll</HintPath>
    </Reference>
    <Reference Include="MVPWindowsUnityUIArchitectureModule">
      <HintPath>..\..\Assemblies\MVPWindowsUnityUIArchitectureModule.dll</HintPath>
    </Reference>
    <Reference Include="Zenject">
      <HintPath>..\..\Assemblies\Zenject.dll</HintPath>
    </Reference>
    <Reference Include="FMODUnity">
      <HintPath>..\..\Assemblies\FMODUnity.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Cinemachine">
      <HintPath>..\..\Assemblies\Unity.Cinemachine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ParticleSystemModule">
      <HintPath>..\..\Assemblies\UnityEngine.ParticleSystemModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>..\..\Assemblies\UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>..\..\Assemblies\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="DoTweenModule">
      <HintPath>..\..\Assemblies\DoTweenModule.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>