<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Mirror.Transports</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="kcp2k">
      <HintPath>..\..\Assemblies\kcp2k.dll</HintPath>
    </Reference>
    <Reference Include="Mirror">
      <HintPath>..\..\Assemblies\Mirror.dll</HintPath>
    </Reference>
    <Reference Include="SimpleWebTransport">
      <HintPath>..\..\Assemblies\SimpleWebTransport.dll</HintPath>
    </Reference>
    <Reference Include="Mirror.BouncyCastle.Cryptography">
      <HintPath>..\..\Assemblies\Mirror.BouncyCastle.Cryptography.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestModule">
      <HintPath>..\..\Assemblies\UnityEngine.UnityWebRequestModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="Telepathy">
      <HintPath>..\..\Assemblies\Telepathy.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>..\..\Assemblies\UnityEngine.IMGUIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.JSONSerializeModule">
      <HintPath>..\..\Assemblies\UnityEngine.JSONSerializeModule.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>