<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SteamLanguageReal</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Zenject">
      <HintPath>..\..\Assemblies\Zenject.dll</HintPath>
    </Reference>
    <Reference Include="SteamModule.API">
      <HintPath>..\..\Assemblies\SteamModule.API.dll</HintPath>
    </Reference>
    <Reference Include="SteamImplementationModule">
      <HintPath>..\..\Assemblies\SteamImplementationModule.dll</HintPath>
    </Reference>
    <Reference Include="Zenject.MockableRealization">
      <HintPath>..\..\Assemblies\Zenject.MockableRealization.dll</HintPath>
    </Reference>
    <Reference Include="com.rlabrecque.steamworks.net">
      <HintPath>..\..\Assemblies\com.rlabrecque.steamworks.net.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>