using System;
using Rewired.Internal.Localization;
using UnityEngine;

namespace Rewired
{
	[Serializable]
	public abstract class InputCategory : bguKJVtsagJfXPpJQeurpzlOLIYd
	{
		[SerializeField]
		[CustomObfuscation(rename = false)]
		protected string _name;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		protected string _descriptiveName;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		protected string _key;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		protected string _tag;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		protected int _id;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		protected bool _userAssignable;

		[NonSerialized]
		private uDMHJlZGqPMWeMVCxldavZLGKMck xbzYqjVyUyRKYoHnQRFqHVCMPddG;

		[NonSerialized]
		private int xAEaKXXPZAiJFzmHGCtzNMKAnPQj;

		internal abstract string keyCategory { get; }

		public string name
		{
			get
			{
				return _name;
			}
			internal set
			{
				_name = text;
			}
		}

		public string descriptiveName
		{
			get
			{
				if (!ReInput.isReady || !LocalizationManager.isEnabled || xbzYqjVyUyRKYoHnQRFqHVCMPddG == null)
				{
					return _descriptiveName;
				}
				return xbzYqjVyUyRKYoHnQRFqHVCMPddG.MpfwJMTclVnnxEuHhBPCmlxJadkBA;
			}
			internal set
			{
				nonLocalizedDescriptiveName = text;
			}
		}

		public string tag
		{
			get
			{
				return _tag;
			}
			internal set
			{
				_tag = text;
			}
		}

		public int id
		{
			get
			{
				return _id;
			}
			internal set
			{
				_id = num;
			}
		}

		public bool userAssignable
		{
			get
			{
				return _userAssignable;
			}
			internal set
			{
				_userAssignable = flag;
			}
		}

		[CustomObfuscation(rename = false)]
		internal string key
		{
			get
			{
				return _key;
			}
			set
			{
				_key = value;
				if (ReInput.isReady && xbzYqjVyUyRKYoHnQRFqHVCMPddG != null)
				{
					xbzYqjVyUyRKYoHnQRFqHVCMPddG.hPAqnroLHIcbmjXldArpEMTOSiTdb();
				}
			}
		}

		[CustomObfuscation(rename = false)]
		internal string nonLocalizedDescriptiveName
		{
			get
			{
				return _descriptiveName;
			}
			set
			{
				_descriptiveName = value;
				if (ReInput.isReady && xbzYqjVyUyRKYoHnQRFqHVCMPddG != null)
				{
					xbzYqjVyUyRKYoHnQRFqHVCMPddG.YSgvMmquHVoFhixWnSsVWmcflge();
				}
			}
		}

		string bguKJVtsagJfXPpJQeurpzlOLIYd.keyCategory => keyCategory;

		string bguKJVtsagJfXPpJQeurpzlOLIYd.scriptingName => _name;

		string bguKJVtsagJfXPpJQeurpzlOLIYd.nonLocalizedDescriptiveName
		{
			get
			{
				return _descriptiveName;
			}
			set
			{
				_descriptiveName = value;
			}
		}

		string bguKJVtsagJfXPpJQeurpzlOLIYd.key => _key;

		int bguKJVtsagJfXPpJQeurpzlOLIYd.autoGeneratedValueFlags
		{
			get
			{
				return xAEaKXXPZAiJFzmHGCtzNMKAnPQj;
			}
			set
			{
				xAEaKXXPZAiJFzmHGCtzNMKAnPQj = value;
			}
		}

		public InputCategory()
		{
		}

		public InputCategory(InputCategory P_0)
		{
			_name = P_0._name;
			_descriptiveName = P_0._descriptiveName;
			_key = P_0._key;
			_tag = P_0._tag;
			_id = P_0._id;
			_userAssignable = P_0._userAssignable;
			xAEaKXXPZAiJFzmHGCtzNMKAnPQj = P_0.xAEaKXXPZAiJFzmHGCtzNMKAnPQj;
		}

		internal virtual void OyVwADHPtCrAvUkjrpdvrzNAWspf()
		{
			xbzYqjVyUyRKYoHnQRFqHVCMPddG = uDMHJlZGqPMWeMVCxldavZLGKMck.KoYuvhvHwZHOiMEpyUHHifMSYsLO(this);
		}

		internal virtual void mkcTIuyVhyjgcOyTVIRjtEYxhOAJ()
		{
		}
	}
}
