using System;
using Rewired.Internal.Localization;
using UnityEngine;

namespace Rewired
{
	[Serializable]
	public sealed class InputLayout : bguKJVtsagJfXPpJQeurpzlOLIYd
	{
		private const string keyCategory = "controller_map/layout";

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private string _name;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private string _descriptiveName;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private string _key;

		[SerializeField]
		[CustomObfuscation(rename = false)]
		private int _id;

		[NonSerialized]
		private uDMHJlZGqPMWeMVCxldavZLGKMck pqzPedMfCsjupzLCxWGIcblwQRZT;

		[NonSerialized]
		private int UMoCIoHSneXNEkyAmbgKEYSgSTTpc;

		public string name
		{
			get
			{
				return _name;
			}
			internal set
			{
				_name = text;
			}
		}

		public string descriptiveName
		{
			get
			{
				if (!ReInput.isReady || !LocalizationManager.isEnabled || pqzPedMfCsjupzLCxWGIcblwQRZT == null)
				{
					return _descriptiveName;
				}
				return pqzPedMfCsjupzLCxWGIcblwQRZT.MpfwJMTclVnnxEuHhBPCmlxJadkBA;
			}
			internal set
			{
				nonLocalizedDescriptiveName = text;
			}
		}

		public int id
		{
			get
			{
				return _id;
			}
			internal set
			{
				_id = num;
			}
		}

		[CustomObfuscation(rename = false)]
		internal string key
		{
			get
			{
				return _key;
			}
			set
			{
				_key = value;
				if (ReInput.isReady && pqzPedMfCsjupzLCxWGIcblwQRZT != null)
				{
					pqzPedMfCsjupzLCxWGIcblwQRZT.hPAqnroLHIcbmjXldArpEMTOSiTdb();
				}
			}
		}

		[CustomObfuscation(rename = false)]
		internal string nonLocalizedDescriptiveName
		{
			get
			{
				return _descriptiveName;
			}
			set
			{
				_descriptiveName = value;
				if (ReInput.isReady && pqzPedMfCsjupzLCxWGIcblwQRZT != null)
				{
					pqzPedMfCsjupzLCxWGIcblwQRZT.YSgvMmquHVoFhixWnSsVWmcflge();
				}
			}
		}

		string bguKJVtsagJfXPpJQeurpzlOLIYd.keyCategory => "controller_map/layout";

		string bguKJVtsagJfXPpJQeurpzlOLIYd.scriptingName => _name;

		string bguKJVtsagJfXPpJQeurpzlOLIYd.nonLocalizedDescriptiveName
		{
			get
			{
				return _descriptiveName;
			}
			set
			{
				_descriptiveName = value;
			}
		}

		string bguKJVtsagJfXPpJQeurpzlOLIYd.key => _key;

		int bguKJVtsagJfXPpJQeurpzlOLIYd.autoGeneratedValueFlags
		{
			get
			{
				return UMoCIoHSneXNEkyAmbgKEYSgSTTpc;
			}
			set
			{
				UMoCIoHSneXNEkyAmbgKEYSgSTTpc = value;
			}
		}

		public InputLayout()
		{
		}

		public InputLayout(InputLayout P_0)
			: this()
		{
			_name = P_0._name;
			_descriptiveName = P_0._descriptiveName;
			_key = P_0._key;
			_id = P_0._id;
			UMoCIoHSneXNEkyAmbgKEYSgSTTpc = P_0.UMoCIoHSneXNEkyAmbgKEYSgSTTpc;
		}

		public InputLayout Clone()
		{
			return new InputLayout(this);
		}

		internal void oqfPrkRCqhrtUheegalROxJRyzgr()
		{
			pqzPedMfCsjupzLCxWGIcblwQRZT = uDMHJlZGqPMWeMVCxldavZLGKMck.KoYuvhvHwZHOiMEpyUHHifMSYsLO(this);
		}

		internal void vbcHWrORUXncbVrsWftXexqHatgFA()
		{
		}
	}
}
