<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>VisualDesignCafe.Nature</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="UnityEngine.WindModule">
      <HintPath>..\..\Assemblies\UnityEngine.WindModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>..\..\Assemblies\UnityEngine.IMGUIModule.dll</HintPath>
    </Reference>
    <Reference Include="VisualDesignCafe.ShaderX">
      <HintPath>..\..\Assemblies\VisualDesignCafe.ShaderX.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>..\..\Assemblies\UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>