<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>EvilCore</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="UniTask">
      <HintPath>..\..\Assemblies\UniTask.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>..\..\Assemblies\UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.RenderPipelines.HighDefinition.Runtime">
      <HintPath>..\..\Assemblies\Unity.RenderPipelines.HighDefinition.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="PrimeTween.Runtime">
      <HintPath>..\..\Assemblies\PrimeTween.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="System.Core" />
    <Reference Include="Unity.RenderPipelines.Core.Runtime">
      <HintPath>..\..\Assemblies\Unity.RenderPipelines.Core.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="VContainer">
      <HintPath>..\..\Assemblies\VContainer.dll</HintPath>
    </Reference>
    <Reference Include="Sirenix.Serialization">
      <HintPath>..\..\Assemblies\Sirenix.Serialization.dll</HintPath>
    </Reference>
    <Reference Include="EvilCore.EvilLogger">
      <HintPath>..\..\Assemblies\EvilCore.EvilLogger.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>