<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>EvilCore.Inputs</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="Rewired_Core">
      <HintPath>..\..\Assemblies\Rewired_Core.dll</HintPath>
    </Reference>
    <Reference Include="Sirenix.OdinInspector.Attributes">
      <HintPath>..\..\Assemblies\Sirenix.OdinInspector.Attributes.dll</HintPath>
    </Reference>
    <Reference Include="System.Core" />
    <Reference Include="UnityEngine.UI">
      <HintPath>..\..\Assemblies\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>..\..\Assemblies\Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="EvilCore.Localization">
      <HintPath>..\..\Assemblies\EvilCore.Localization.dll</HintPath>
    </Reference>
    <Reference Include="VContainer">
      <HintPath>..\..\Assemblies\VContainer.dll</HintPath>
    </Reference>
    <Reference Include="EvilCore.Extensions">
      <HintPath>..\..\Assemblies\EvilCore.Extensions.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>