using BasicModules.DatabaseModule.Core.Scripts;

namespace Global.Modules.Database_Module.Scripts.Configurations
{
	public interface IDatabaseDataManipulatorsFactory
	{
		IDatabaseDataReader CreateGoogleSheetsDatabaseDataReader(ICsvDatabaseConverter csvDatabaseConverter, DatabasePickingDataConfiguration databasePickingDataConfiguration);

		IDatabaseDataWriter CreateGoogleSheetsDatabaseDataWriter(DatabasePickingDataConfiguration databasePickingDataConfiguration);
	}
}
