<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>AIModuleStateMachine.AliveEnemyCount</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="EnemyData">
      <HintPath>..\..\Assemblies\EnemyData.dll</HintPath>
    </Reference>
    <Reference Include="SessionCleanup">
      <HintPath>..\..\Assemblies\SessionCleanup.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>