<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>AnalyticsData</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="NetworkedModelCodegen">
      <HintPath>..\..\Assemblies\NetworkedModelCodegen.dll</HintPath>
    </Reference>
    <Reference Include="EnemyData">
      <HintPath>..\..\Assemblies\EnemyData.dll</HintPath>
    </Reference>
    <Reference Include="SavingSystemModule">
      <HintPath>..\..\Assemblies\SavingSystemModule.dll</HintPath>
    </Reference>
    <Reference Include="SavingModule">
      <HintPath>..\..\Assemblies\SavingModule.dll</HintPath>
    </Reference>
    <Reference Include="SynchronizedModels.Json">
      <HintPath>..\..\Assemblies\SynchronizedModels.Json.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="SerializableDictionary">
      <HintPath>..\..\Assemblies\SerializableDictionary.dll</HintPath>
    </Reference>
    <Reference Include="SynchronizedModels.DataStreaming">
      <HintPath>..\..\Assemblies\SynchronizedModels.DataStreaming.dll</HintPath>
    </Reference>
    <Reference Include="SessionCleanup">
      <HintPath>..\..\Assemblies\SessionCleanup.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>