<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>EnemySystemsBehavior</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Fusion.Runtime">
      <HintPath>..\..\Assemblies\Fusion.Runtime.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>