namespace Rewired
{
	[CustomObfuscation(rename = false)]
	internal enum InputPlatform
	{
		Unknown = 0,
		WindowsDirectInput = 1,
		WindowsRawInput = 2,
		WindowsXInput = 3,
		WindowsFallback = 4,
		WindowsUWP = 5,
		WindowsUWPFallback = 6,
		OSXNative = 7,
		OSXFallback = 8,
		LinuxNative = 9,
		LinuxFallback = 10,
		LinuxFallback_PreConfigured = 11,
		AndroidFallback = 12,
		AmazonFireTVFallback = 13,
		RazerForgeTVFallback = 14,
		iOSFallback = 15,
		WindowsPhone8Fallback = 16,
		BlackberryFallback = 17,
		PS3Fallback = 18,
		PS4Fallback = 19,
		PSMFallback = 20,
		PSVitaFallback = 21,
		XBox360Fallback = 22,
		XBoxOneFallback = 23,
		WiiFallback = 24,
		WiiUFallback = 25,
		Fallback = 26,
		Ouya = 27,
		XboxOne = 28,
		GameCore = 29,
		PS4 = 30,
		PS5 = 31,
		NintendoSwitch = 32,
		NintendoSwitchFallback = 33,
		Stadia = 34,
		Custom = 35,
		InternalDriver = 36,
		SDL2 = 37,
		SDL2Windows = 38,
		SDL2OSX = 39,
		SDL2Linux = 40,
		Steam = 41,
		WebGL = 42,
		AppleGameController = 43
	}
}
