<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>PlayerCustomization.LobbyAvatar.Data</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="NetworkedModelCodegen">
      <HintPath>..\..\Assemblies\NetworkedModelCodegen.dll</HintPath>
    </Reference>
    <Reference Include="Fusion.Runtime">
      <HintPath>..\..\Assemblies\Fusion.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="SkinConfiguration">
      <HintPath>..\..\Assemblies\SkinConfiguration.dll</HintPath>
    </Reference>
    <Reference Include="DeadPartsModuleData">
      <HintPath>..\..\Assemblies\DeadPartsModuleData.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>