<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Sirenix.OdinInspector.Modules.UnityLocalization</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Unity.Localization">
      <HintPath>..\..\Assemblies\Unity.Localization.dll</HintPath>
    </Reference>
    <Reference Include="Sirenix.Serialization">
      <HintPath>..\..\Assemblies\Sirenix.Serialization.dll</HintPath>
    </Reference>
    <Reference Include="Sirenix.Serialization.Config">
      <HintPath>..\..\Assemblies\Sirenix.Serialization.Config.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>