using System;
using Obi;
using Unity.Jobs;
using UnityEngine;

[Unity.Jobs.DOTSCompilerGenerated]
internal class __JobReflectionRegistrationOutput__13069050244643737771
{
	public static void CreateJobReflectionData()
	{
		try
		{
			IJobParallelForExtensions.EarlyJobInit<GenerateBoxContactsJob>();
			IJobParallelForExtensions.EarlyJobInit<GenerateCapsuleContactsJob>();
			IJobParallelForExtensions.EarlyJobInit<BurstColliderWorld.IdentifyMovingColliders>();
			IJobExtensions.EarlyJobInit<BurstColliderWorld.UpdateMovingColliders>();
			IJobParallelForExtensions.EarlyJobInit<BurstColliderWorld.GenerateContactsJob>();
			IJobExtensions.EarlyJobInit<BurstColliderWorld.PrefixSumJob>();
			IJobExtensions.EarlyJobInit<BurstColliderWorld.SortContactPairsByShape>();
			IJobParallelForExtensions.EarlyJobInit<BurstColliderWorld.ApplyForceZonesJob>();
			IJobParallelForExtensions.EarlyJobInit<GenerateDistanceFieldContactsJob>();
			IJobParallelForExtensions.EarlyJobInit<GenerateEdgeMeshContactsJob>();
			IJobParallelForExtensions.EarlyJobInit<GenerateHeightFieldContactsJob>();
			IJobParallelForExtensions.EarlyJobInit<GenerateSphereContactsJob>();
			IJobParallelForExtensions.EarlyJobInit<GenerateTriangleMeshContactsJob>();
			IJobParallelForExtensions.EarlyJobInit<BurstAerodynamicConstraintsBatch.AerodynamicConstraintsBatchJob>();
			IJobParallelForExtensions.EarlyJobInit<BurstBendConstraintsBatch.BendConstraintsBatchJob>();
			IJobParallelForExtensions.EarlyJobInit<BurstBendConstraintsBatch.ApplyBendConstraintsBatchJob>();
			IJobParallelForExtensions.EarlyJobInit<BurstBendTwistConstraintsBatch.BendTwistConstraintsBatchJob>();
			IJobParallelForExtensions.EarlyJobInit<BurstBendTwistConstraintsBatch.ApplyBendTwistConstraintsBatchJob>();
			IJobParallelForExtensions.EarlyJobInit<BurstConstraintsBatchImpl.ClearLambdasJob>();
			IJobParallelForExtensions.EarlyJobInit<BurstChainConstraintsBatch.ChainConstraintsBatchJob>();
			IJobParallelForExtensions.EarlyJobInit<BurstChainConstraintsBatch.ApplyChainConstraintsBatchJob>();
			IJobExtensions.EarlyJobInit<ApplyCollisionConstraintsBatchJob>();
			IJobParallelForExtensions.EarlyJobInit<BurstColliderCollisionConstraintsBatch.UpdateContactsJob>();
			IJobExtensions.EarlyJobInit<BurstColliderCollisionConstraintsBatch.CollisionConstraintsBatchJob>();
			IJobExtensions.EarlyJobInit<BurstColliderFrictionConstraintsBatch.FrictionConstraintsBatchJob>();
			IJobParallelForExtensions.EarlyJobInit<BurstDensityConstraints.ClearFluidDataJob>();
			IJobParallelForExtensions.EarlyJobInit<BurstDensityConstraints.UpdateInteractionsJob>();
			IJobParallelForExtensions.EarlyJobInit<BurstDensityConstraints.CalculateLambdasJob>();
			IJobParallelForExtensions.EarlyJobInit<BurstDensityConstraints.ApplyPositionDeltasJob>();
			IJobParallelForExtensions.EarlyJobInit<BurstDensityConstraints.ApplyAtmosphereJob>();
			IJobParallelForExtensions.EarlyJobInit<BurstDensityConstraints.AverageSmoothPositionsJob>();
			IJobParallelForExtensions.EarlyJobInit<BurstDensityConstraints.AverageAnisotropyJob>();
			IJobParallelForExtensions.EarlyJobInit<BurstDensityConstraintsBatch.UpdateDensitiesJob>();
			IJobParallelForExtensions.EarlyJobInit<BurstDensityConstraintsBatch.ApplyDensityConstraintsJob>();
			IJobParallelForExtensions.EarlyJobInit<BurstDensityConstraintsBatch.ViscosityVorticityJob>();
			IJobParallelForExtensions.EarlyJobInit<BurstDensityConstraintsBatch.NormalsJob>();
			IJobParallelForExtensions.EarlyJobInit<BurstDensityConstraintsBatch.AccumulateSmoothPositionsJob>();
			IJobParallelForExtensions.EarlyJobInit<BurstDensityConstraintsBatch.AccumulateAnisotropyJob>();
			IJobParallelForExtensions.EarlyJobInit<BurstDistanceConstraintsBatch.DistanceConstraintsBatchJob>();
			IJobParallelForExtensions.EarlyJobInit<BurstDistanceConstraintsBatch.ApplyDistanceConstraintsBatchJob>();
			IJobParallelForExtensions.EarlyJobInit<ApplyBatchedCollisionConstraintsBatchJob>();
			IJobParallelForExtensions.EarlyJobInit<BurstParticleCollisionConstraintsBatch.UpdateParticleContactsJob>();
			IJobParallelForExtensions.EarlyJobInit<BurstParticleCollisionConstraintsBatch.ParticleCollisionConstraintsBatchJob>();
			IJobParallelForExtensions.EarlyJobInit<BurstParticleFrictionConstraintsBatch.ParticleFrictionConstraintsBatchJob>();
			IJobParallelForExtensions.EarlyJobInit<BurstPinConstraintsBatch.ClearPinsJob>();
			IJobParallelForExtensions.EarlyJobInit<BurstPinConstraintsBatch.UpdatePinsJob>();
			IJobParallelForExtensions.EarlyJobInit<BurstPinConstraintsBatch.PinConstraintsBatchJob>();
			IJobExtensions.EarlyJobInit<BurstPinConstraintsBatch.ApplyPinConstraintsBatchJob>();
			IJobParallelForExtensions.EarlyJobInit<BurstPinConstraintsBatch.ProjectRenderablePositionsJob>();
			IJobParallelForExtensions.EarlyJobInit<BurstPinholeConstraintsBatch.ClearPinsJob>();
			IJobParallelForExtensions.EarlyJobInit<BurstPinholeConstraintsBatch.UpdatePinsJob>();
			IJobParallelForExtensions.EarlyJobInit<BurstPinholeConstraintsBatch.PinholeConstraintsBatchJob>();
			IJobExtensions.EarlyJobInit<BurstPinholeConstraintsBatch.ApplyPinholeConstraintsBatchJob>();
			IJobParallelForExtensions.EarlyJobInit<BurstShapeMatchingConstraintsBatch.ShapeMatchingCalculateRestJob>();
			IJobParallelForExtensions.EarlyJobInit<BurstShapeMatchingConstraintsBatch.ShapeMatchingConstraintsBatchJob>();
			IJobParallelForExtensions.EarlyJobInit<BurstShapeMatchingConstraintsBatch.ApplyShapeMatchingConstraintsBatchJob>();
			IJobParallelForExtensions.EarlyJobInit<BurstSkinConstraintsBatch.SkinConstraintsBatchJob>();
			IJobParallelForExtensions.EarlyJobInit<BurstSkinConstraintsBatch.ApplySkinConstraintsBatchJob>();
			IJobExtensions.EarlyJobInit<BurstStitchConstraintsBatch.StitchConstraintsBatchJob>();
			IJobExtensions.EarlyJobInit<BurstStitchConstraintsBatch.ApplyStitchConstraintsBatchJob>();
			IJobParallelForExtensions.EarlyJobInit<BurstStretchShearConstraintsBatch.StretchShearConstraintsBatchJob>();
			IJobParallelForExtensions.EarlyJobInit<BurstStretchShearConstraintsBatch.ApplyStretchShearConstraintsBatchJob>();
			IJobParallelForExtensions.EarlyJobInit<BurstTetherConstraintsBatch.TetherConstraintsBatchJob>();
			IJobParallelForExtensions.EarlyJobInit<BurstTetherConstraintsBatch.ApplyTetherConstraintsBatchJob>();
			IJobParallelForExtensions.EarlyJobInit<BurstVolumeConstraintsBatch.VolumeConstraintsBatchJob>();
			IJobParallelForExtensions.EarlyJobInit<BurstVolumeConstraintsBatch.ApplyVolumeConstraintsBatchJob>();
			IJobParallelForExtensions.EarlyJobInit<BurstPrefixSum.BlockSumJob>();
			IJobExtensions.EarlyJobInit<BurstPrefixSum.BlockSum>();
			IJobParallelForExtensions.EarlyJobInit<BurstPrefixSum.PrefixSumJob>();
			IJobExtensions.EarlyJobInit<ParticleGrid.UpdateGrid>();
			IJobParallelForExtensions.EarlyJobInit<ParticleGrid.GenerateParticleParticleContactsJob>();
			IJobParallelForExtensions.EarlyJobInit<SpatialQueryJob>();
			IJobParallelForExtensions.EarlyJobInit<BuildParticleMeshDataJob>();
			IJobParallelForExtensions.EarlyJobInit<BurstFoamRenderSystem.ProjectOnSortAxisJob>();
			IJobParallelForExtensions.EarlyJobInit<BurstFoamRenderSystem.SortParticles>();
			IJobParallelForExtensions.EarlyJobInit<BurstFoamRenderSystem.BuildFoamMeshDataJob>();
			IJobParallelForExtensions.EarlyJobInit<BurstInstancedParticleRenderSystem.InstancedParticleTransforms>();
			IJobParallelForExtensions.EarlyJobInit<BurstChainRopeRenderSystem.InstanceTransforms>();
			IJobParallelForExtensions.EarlyJobInit<BurstExtrudedRopeRenderSystem.BuildExtrudedMesh>();
			IJobParallelForExtensions.EarlyJobInit<BurstLineRopeRenderSystem.BuildLineMesh>();
			IJobParallelForExtensions.EarlyJobInit<BurstMeshRopeRenderSystem.BuildRopeMeshJob>();
			IJobParallelForExtensions.EarlyJobInit<ChaikinSmoothChunksJob>();
			IJobParallelForExtensions.EarlyJobInit<DecimateChunksJob>();
			IJobParallelForExtensions.EarlyJobInit<ParallelTransportJob>();
			IJobParallelForExtensions.EarlyJobInit<ApplyInertialForcesJob>();
			IJobParallelForExtensions.EarlyJobInit<CalculateSimplexBoundsJob>();
			IJobParallelForExtensions.EarlyJobInit<BoundsReductionJob>();
			IJobParallelForExtensions.EarlyJobInit<EnforceLimitsJob>();
			IJobExtensions.EarlyJobInit<FindFluidParticlesJob>();
			IJobParallelForExtensions.EarlyJobInit<EmitParticlesJob>();
			IJobParallelForExtensions.EarlyJobInit<GenerateParticlesJob>();
			IJobParallelForDeferExtensions.EarlyJobInit<UpdateParticlesJob>();
			IJobParallelForDeferExtensions.EarlyJobInit<CopyJob>();
			IJobParallelForExtensions.EarlyJobInit<InterpolationJob>();
			IJobParallelForExtensions.EarlyJobInit<PredictPositionsJob>();
			IJobParallelForExtensions.EarlyJobInit<ResetNormals>();
			IJobParallelForExtensions.EarlyJobInit<UpdateTriangleNormalsJob>();
			IJobParallelForExtensions.EarlyJobInit<UpdateEdgeNormalsJob>();
			IJobParallelForExtensions.EarlyJobInit<RenderableOrientationFromNormals>();
			IJobParallelForExtensions.EarlyJobInit<UpdateParticleLifetimesJob>();
			IJobParallelForExtensions.EarlyJobInit<UpdatePositionsJob>();
			IJobParallelForExtensions.EarlyJobInit<UpdateVelocitiesJob>();
			IJobExtensions.EarlyJobInit<DequeueIntoArrayJob<BurstContact>>();
			IJobExtensions.EarlyJobInit<DequeueIntoArrayJob<FluidInteraction>>();
			IJobExtensions.EarlyJobInit<DequeueIntoArrayJob<BurstQueryResult>>();
		}
		catch (Exception ex)
		{
			EarlyInitHelpers.JobReflectionDataCreationFailed(ex);
		}
	}

	[RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterAssembliesLoaded)]
	public static void EarlyInit()
	{
		CreateJobReflectionData();
	}
}
