<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>CustomUserReporting.Default</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="UserReport.Client">
      <HintPath>..\..\Assemblies\UserReport.Client.dll</HintPath>
    </Reference>
    <Reference Include="UserReport">
      <HintPath>..\..\Assemblies\UserReport.dll</HintPath>
    </Reference>
    <Reference Include="Zenject">
      <HintPath>..\..\Assemblies\Zenject.dll</HintPath>
    </Reference>
    <Reference Include="SettingsMenu">
      <HintPath>..\..\Assemblies\SettingsMenu.dll</HintPath>
    </Reference>
    <Reference Include="NetworkInputModule">
      <HintPath>..\..\Assemblies\NetworkInputModule.dll</HintPath>
    </Reference>
    <Reference Include="MouseVisibilityModule">
      <HintPath>..\..\Assemblies\MouseVisibilityModule.dll</HintPath>
    </Reference>
    <Reference Include="GamePauseModule">
      <HintPath>..\..\Assemblies\GamePauseModule.dll</HintPath>
    </Reference>
    <Reference Include="CameraModel">
      <HintPath>..\..\Assemblies\CameraModel.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>..\..\Assemblies\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>..\..\Assemblies\Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>..\..\Assemblies\UnityEngine.UIModule.dll</HintPath>
    </Reference>
    <Reference Include="UniTask">
      <HintPath>..\..\Assemblies\UniTask.dll</HintPath>
    </Reference>
    <Reference Include="UserReport.Di">
      <HintPath>..\..\Assemblies\UserReport.Di.dll</HintPath>
    </Reference>
    <Reference Include="Zenject.MockableRealization">
      <HintPath>..\..\Assemblies\Zenject.MockableRealization.dll</HintPath>
    </Reference>
    <Reference Include="UserReportAdapter">
      <HintPath>..\..\Assemblies\UserReportAdapter.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityAnalyticsModule">
      <HintPath>..\..\Assemblies\UnityEngine.UnityAnalyticsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>..\..\Assemblies\UnityEngine.ImageConversionModule.dll</HintPath>
    </Reference>
    <Reference Include="MVPWindowsUnityUIArchitectureModule">
      <HintPath>..\..\Assemblies\MVPWindowsUnityUIArchitectureModule.dll</HintPath>
    </Reference>
    <Reference Include="AssetLoaderServiceModule">
      <HintPath>..\..\Assemblies\AssetLoaderServiceModule.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>