<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>EvilCore.Extensions</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>..\..\Assemblies\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>..\..\Assemblies\UnityEngine.UIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>..\..\Assemblies\UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="VContainer">
      <HintPath>..\..\Assemblies\VContainer.dll</HintPath>
    </Reference>
    <Reference Include="UniTask">
      <HintPath>..\..\Assemblies\UniTask.dll</HintPath>
    </Reference>
    <Reference Include="Facepunch.Steamworks.Win64">
      <HintPath>..\..\Assemblies\Facepunch.Steamworks.Win64.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TerrainModule">
      <HintPath>..\..\Assemblies\UnityEngine.TerrainModule.dll</HintPath>
    </Reference>
    <Reference Include="System.Core" />
    <Reference Include="EvilCore.EvilLogger">
      <HintPath>..\..\Assemblies\EvilCore.EvilLogger.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TerrainPhysicsModule">
      <HintPath>..\..\Assemblies\UnityEngine.TerrainPhysicsModule.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>