<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>UINavigationModuleRealization</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="UnityEngine.UI">
      <HintPath>..\..\Assemblies\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UINavigationModule">
      <HintPath>..\..\Assemblies\UINavigationModule.dll</HintPath>
    </Reference>
    <Reference Include="UINavigationModule.Components">
      <HintPath>..\..\Assemblies\UINavigationModule.Components.dll</HintPath>
    </Reference>
    <Reference Include="SerializableDictionary">
      <HintPath>..\..\Assemblies\SerializableDictionary.dll</HintPath>
    </Reference>
    <Reference Include="NetworkInputModule">
      <HintPath>..\..\Assemblies\NetworkInputModule.dll</HintPath>
    </Reference>
    <Reference Include="FMODUnity">
      <HintPath>..\..\Assemblies\FMODUnity.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>..\..\Assemblies\Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="Zenject">
      <HintPath>..\..\Assemblies\Zenject.dll</HintPath>
    </Reference>
    <Reference Include="Zenject-usage">
      <HintPath>..\..\Assemblies\Zenject-usage.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>..\..\Assemblies\UnityEngine.UIModule.dll</HintPath>
    </Reference>
    <Reference Include="InputModule.Core">
      <HintPath>..\..\Assemblies\InputModule.Core.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>