using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

[assembly: AssemblyTitle("Rewired Core")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Guavaman Enterprises")]
[assembly: AssemblyProduct("Rewired")]
[assembly: AssemblyCopyright("Copyright © 2014 Augie R. Maddox. All rights reserved.")]
[assembly: AssemblyTrademark("Augie R. Maddox")]
[assembly: ComVisible(false)]
[assembly: Guid("ecfc0337-34dc-46b5-a9d4-b8f38334a8dd")]
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: InternalsVisibleTo("Rewired_Editor")]
[assembly: InternalsVisibleTo("Rewired_Windows")]
[assembly: InternalsVisibleTo("Rewired_OSX")]
[assembly: InternalsVisibleTo("Rewired_Linux")]
[assembly: InternalsVisibleTo("Rewired_NintendoSwitch")]
[assembly: InternalsVisibleTo("Rewired_NintendoSwitch_EditorRuntime")]
[assembly: InternalsVisibleTo("Rewired_NintendoSwitch_Editor")]
[assembly: InternalsVisibleTo("Rewired_NintendoSwitch2")]
[assembly: InternalsVisibleTo("Rewired_NintendoSwitch2_EditorRuntime")]
[assembly: InternalsVisibleTo("Rewired_NintendoSwitch2_Editor")]
[assembly: InternalsVisibleTo("Rewired_WebGL")]
[assembly: InternalsVisibleTo("Rewired_Android")]
[assembly: InternalsVisibleTo("Rewired_GameCore")]
[assembly: InternalsVisibleTo("Rewired_GameCore_EditorRuntime")]
[assembly: InternalsVisibleTo("Rewired_GameCore_Editor")]
[assembly: InternalsVisibleTo("Rewired_PlayStation4")]
[assembly: InternalsVisibleTo("Rewired_PlayStation4_Editor")]
[assembly: InternalsVisibleTo("Rewired_PlayStation4_EditorRuntime")]
[assembly: InternalsVisibleTo("Rewired_PlayStation5")]
[assembly: InternalsVisibleTo("Rewired_PlayStation5_Editor")]
[assembly: InternalsVisibleTo("Rewired_PlayStation5_EditorRuntime")]
[assembly: InternalsVisibleTo("Rewired_UWP_EditorRuntime")]
[assembly: AssemblyInformationalVersion("1.0.0+5a4d9a345e71370a4dcce524956617af22db42c7")]
[assembly: AssemblyVersion("1.0.0.0")]
[module: SuppressIldasm]
