<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>LevelModuleInstallers</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Zenject">
      <HintPath>..\..\Assemblies\Zenject.dll</HintPath>
    </Reference>
    <Reference Include="LevelModule">
      <HintPath>..\..\Assemblies\LevelModule.dll</HintPath>
    </Reference>
    <Reference Include="PlayerTransitedToLevel">
      <HintPath>..\..\Assemblies\PlayerTransitedToLevel.dll</HintPath>
    </Reference>
    <Reference Include="LevelModuleSystems">
      <HintPath>..\..\Assemblies\LevelModuleSystems.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>