<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>AnalyticsInstallers</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="AssetLoaderServiceModule">
      <HintPath>..\..\Assemblies\AssetLoaderServiceModule.dll</HintPath>
    </Reference>
    <Reference Include="Zenject">
      <HintPath>..\..\Assemblies\Zenject.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="GameJournaling">
      <HintPath>..\..\Assemblies\GameJournaling.dll</HintPath>
    </Reference>
    <Reference Include="Zenject.MockableRealization">
      <HintPath>..\..\Assemblies\Zenject.MockableRealization.dll</HintPath>
    </Reference>
    <Reference Include="AnalyticsSystems">
      <HintPath>..\..\Assemblies\AnalyticsSystems.dll</HintPath>
    </Reference>
    <Reference Include="AnalyticsModuleCore">
      <HintPath>..\..\Assemblies\AnalyticsModuleCore.dll</HintPath>
    </Reference>
    <Reference Include="AnalyticsData">
      <HintPath>..\..\Assemblies\AnalyticsData.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>