using Rewired;

[CustomClassObfuscation(renamePubIntMembers = false, renamePrivateMembers = false)]
internal interface bguKJVtsagJfXPpJQeurpzlOLIYd
{
	string keyCategory { get; }

	string scriptingName { get; }

	string nonLocalizedDescriptiveName { get; set; }

	string key { get; }

	int autoGeneratedValueFlags { get; set; }
}
