using Rewired;

[CustomClassObfuscation(renamePubIntMembers = false, renamePrivateMembers = false)]
internal interface HQqbZoQigscgVQcdQGCMdxuNvzzS
{
	string keyCategory { get; }

	string key { get; }

	int autoGeneratedValueFlags { get; set; }
}
