using System;
using Rewired.Internal.Localization;

internal class PNpsspmaeIckaEYciaSqXgOdyvotA : bguKJVtsagJfXPpJQeurpzlOLIYd
{
	protected readonly FDNFDGKMldROgCHjPdSVTnUzAnLgb btlrLJvUtVMTgngydkyaezASOFbm;

	private readonly string WmZXOjDQHNlKKnZLKKqtGFLFDTyiA;

	private readonly string XSpnDVaXvUIoRpKYVPPfuiBuoPpL;

	private string VHSkhVSllzriMgYMXNxRtjZSAxpv;

	private readonly string KbkRGGvflRvxwVcXlAJeauTrHaYdb;

	private int NbKGbsJkObnnXrgeBPqIEMqcBXQjA;

	public FDNFDGKMldROgCHjPdSVTnUzAnLgb SEmUEYhFCOinEboyOFclOuvyHfqgb => btlrLJvUtVMTgngydkyaezASOFbm;

	string bguKJVtsagJfXPpJQeurpzlOLIYd.keyCategory => WmZXOjDQHNlKKnZLKKqtGFLFDTyiA;

	string bguKJVtsagJfXPpJQeurpzlOLIYd.scriptingName => XSpnDVaXvUIoRpKYVPPfuiBuoPpL;

	string bguKJVtsagJfXPpJQeurpzlOLIYd.nonLocalizedDescriptiveName
	{
		get
		{
			return VHSkhVSllzriMgYMXNxRtjZSAxpv;
		}
		set
		{
			VHSkhVSllzriMgYMXNxRtjZSAxpv = value;
		}
	}

	string bguKJVtsagJfXPpJQeurpzlOLIYd.key => KbkRGGvflRvxwVcXlAJeauTrHaYdb;

	int bguKJVtsagJfXPpJQeurpzlOLIYd.autoGeneratedValueFlags
	{
		get
		{
			return NbKGbsJkObnnXrgeBPqIEMqcBXQjA;
		}
		set
		{
			NbKGbsJkObnnXrgeBPqIEMqcBXQjA = value;
		}
	}

	public string keyCategory => WmZXOjDQHNlKKnZLKKqtGFLFDTyiA;

	public string scriptingName => XSpnDVaXvUIoRpKYVPPfuiBuoPpL;

	public string zdsEXqGbgFgpRWZpvCSgpdwbtisv
	{
		get
		{
			if (!LocalizationManager.isEnabled)
			{
				return VHSkhVSllzriMgYMXNxRtjZSAxpv;
			}
			return btlrLJvUtVMTgngydkyaezASOFbm.MpfwJMTclVnnxEuHhBPCmlxJadkBA;
		}
	}

	public string nonLocalizedDescriptiveName => VHSkhVSllzriMgYMXNxRtjZSAxpv;

	public string key => KbkRGGvflRvxwVcXlAJeauTrHaYdb;

	public PNpsspmaeIckaEYciaSqXgOdyvotA(FDNFDGKMldROgCHjPdSVTnUzAnLgb P_0, string P_1, string P_2, string P_3, string P_4)
	{
		if (P_0 == null)
		{
			throw new ArgumentNullException();
		}
		btlrLJvUtVMTgngydkyaezASOFbm = P_0;
		WmZXOjDQHNlKKnZLKKqtGFLFDTyiA = P_1;
		XSpnDVaXvUIoRpKYVPPfuiBuoPpL = P_2;
		VHSkhVSllzriMgYMXNxRtjZSAxpv = P_3;
		KbkRGGvflRvxwVcXlAJeauTrHaYdb = P_4;
		P_0.FSygSkZkOZRlfprpDasbAbVdqyGH(this);
	}

	public virtual bool HigUEXRMHDCBxDAIsCfdHIKAlrTJ(PNpsspmaeIckaEYciaSqXgOdyvotA P_0, bool P_1)
	{
		if (P_0 == null)
		{
			return false;
		}
		if ((object)GetType() != P_0.GetType())
		{
			return false;
		}
		if (!btlrLJvUtVMTgngydkyaezASOFbm.PstXrjtELzTCScyWAcSsHTXMaNuK(P_0.btlrLJvUtVMTgngydkyaezASOFbm, P_1))
		{
			return false;
		}
		return true;
	}
}
