using System;
using Rewired.Internal.Localization;

internal abstract class qsMHzLAapFqYwEIgPNGcCicKhxkM : FDNFDGKMldROgCHjPdSVTnUzAnLgb
{
	protected LocalizedString[] jwbVsaSgCaLLJfvJjylSjayHlbyi;

	public int EmBvRrmOxLyVerpWWUxvcvaHPtec => FDNFDGKMldROgCHjPdSVTnUzAnLgb.FaWRBKagAChKzYIPTHxodNThJXtKA(base.tnQKiUchqifinDnJuSQdboJqaQgK, base.bEKIbEjDpMfnJogudzLlVaoylrODb);

	public abstract string UZtpxFUPQZBSvGgnZjNTrWXUAlHF(int P_0);

	protected qsMHzLAapFqYwEIgPNGcCicKhxkM(sztzDKprOgaEtSRoFjITTczsHDuW P_0, LsWebCorzTdhEUjUrAlgVzPmJJHR P_1)
		: base(P_0, P_1)
	{
	}

	protected qsMHzLAapFqYwEIgPNGcCicKhxkM(bOFZUEPNgDgQSavjlJvfJaMptbnQA P_0, sztzDKprOgaEtSRoFjITTczsHDuW P_1, LsWebCorzTdhEUjUrAlgVzPmJJHR P_2)
		: base(P_0, P_1, P_2)
	{
		if (P_0 == null)
		{
			throw new ArgumentNullException("dataSource");
		}
	}

	protected virtual void vQtdpntFpZGKWdmjBKDRKLSkTGte()
	{
		int num = EmBvRrmOxLyVerpWWUxvcvaHPtec;
		jwbVsaSgCaLLJfvJjylSjayHlbyi = null;
		if (num > 0)
		{
			jwbVsaSgCaLLJfvJjylSjayHlbyi = new LocalizedString[num];
			for (int i = 0; i < num; i++)
			{
				jwbVsaSgCaLLJfvJjylSjayHlbyi[i] = new LocalizedString();
			}
		}
		UnrybsryaIWFpZtUNyuzUDGOqKMH();
	}

	public virtual void lUqYRBOMHmmAsYjUQLKWTMFuEJyE(bOFZUEPNgDgQSavjlJvfJaMptbnQA P_0)
	{
		FSygSkZkOZRlfprpDasbAbVdqyGH(P_0);
	}

	public virtual void edoISZVVLFqNLVCoyPjLDcIZHkSR(bguKJVtsagJfXPpJQeurpzlOLIYd P_0)
	{
		base.FSygSkZkOZRlfprpDasbAbVdqyGH(P_0);
		if (!(P_0 is bOFZUEPNgDgQSavjlJvfJaMptbnQA))
		{
			throw new ArgumentException("value must implement " + typeof(bOFZUEPNgDgQSavjlJvfJaMptbnQA));
		}
	}

	public virtual void OIDXqZztljoaAEKugYBNLVlqQiUn()
	{
		IKlsylKZUPoPZutFmVypQCUyJCdT();
	}

	public virtual void doBhoWdKbzyvPkrKuEstAlSDpYsQB()
	{
		sUWPMtNBLWLNaHkrSGMrmklXilrKA();
		if (jwbVsaSgCaLLJfvJjylSjayHlbyi != null)
		{
			for (int i = 0; i < EmBvRrmOxLyVerpWWUxvcvaHPtec; i++)
			{
				jwbVsaSgCaLLJfvJjylSjayHlbyi[i].Clear();
			}
		}
	}

	public virtual bool bOouhFpprmnIenHRDvNuJYAveuEN(FopEdGIdXdIETmMGGpfJptNngDfeb P_0, bool P_1)
	{
		if (!(P_0 is qsMHzLAapFqYwEIgPNGcCicKhxkM qsMHzLAapFqYwEIgPNGcCicKhxkM2))
		{
			return false;
		}
		if (!TIbllctYhBPpFlqcVRhFKAQKVURc(P_0, P_1))
		{
			return false;
		}
		bOFZUEPNgDgQSavjlJvfJaMptbnQA bOFZUEPNgDgQSavjlJvfJaMptbnQA2 = JrNSXOoPbyfvCsYwXqkJnjIACSkQ();
		bOFZUEPNgDgQSavjlJvfJaMptbnQA bOFZUEPNgDgQSavjlJvfJaMptbnQA3 = qsMHzLAapFqYwEIgPNGcCicKhxkM2.JrNSXOoPbyfvCsYwXqkJnjIACSkQ();
		if (bOFZUEPNgDgQSavjlJvfJaMptbnQA2 == null != (bOFZUEPNgDgQSavjlJvfJaMptbnQA3 == null))
		{
			return false;
		}
		if (bOFZUEPNgDgQSavjlJvfJaMptbnQA2 != null && P_1)
		{
			int num = EmBvRrmOxLyVerpWWUxvcvaHPtec;
			for (int i = 0; i < num; i++)
			{
				if (!string.Equals(bOFZUEPNgDgQSavjlJvfJaMptbnQA2.GetSpecialElementKey(i), bOFZUEPNgDgQSavjlJvfJaMptbnQA3.GetSpecialElementKey(i), StringComparison.Ordinal))
				{
					return false;
				}
				if (!string.Equals(bOFZUEPNgDgQSavjlJvfJaMptbnQA2.GetSpecialElementNonLocalizedDescriptiveName(i), bOFZUEPNgDgQSavjlJvfJaMptbnQA3.GetSpecialElementNonLocalizedDescriptiveName(i), StringComparison.Ordinal))
				{
					return false;
				}
			}
		}
		return true;
	}

	protected virtual void HNkMxMYCqaAfIdtBRFiNJkaOrdXFb()
	{
		bnDwmhTjXYwxCTTxOQceUSJDV();
		if (jwbVsaSgCaLLJfvJjylSjayHlbyi != null)
		{
			for (int i = 0; i < jwbVsaSgCaLLJfvJjylSjayHlbyi.Length; i++)
			{
				jwbVsaSgCaLLJfvJjylSjayHlbyi[i].Clear();
			}
		}
	}

	protected virtual void AXEGGhUCWKfQEnftIkDpHkiJGOgEA(cwXjjPkxPWMBcEFwnCUCcKJomfDI P_0)
	{
		base.nIhCTLejCUDzcAzoRcmLjSsBLnitA(P_0);
		bOFZUEPNgDgQSavjlJvfJaMptbnQA bOFZUEPNgDgQSavjlJvfJaMptbnQA2 = JrNSXOoPbyfvCsYwXqkJnjIACSkQ();
		if (bOFZUEPNgDgQSavjlJvfJaMptbnQA2 == null || string.IsNullOrEmpty(bOFZUEPNgDgQSavjlJvfJaMptbnQA2.key) || base.tnQKiUchqifinDnJuSQdboJqaQgK != sztzDKprOgaEtSRoFjITTczsHDuW.CompoundElement || !FDNFDGKMldROgCHjPdSVTnUzAnLgb.tGJPnPxMDZQkntURokRfyFQymnPw(base.bEKIbEjDpMfnJogudzLlVaoylrODb, out var fOURUkakBckGnlgOkmwbemAJMKXu))
		{
			return;
		}
		for (int i = 0; i < fOURUkakBckGnlgOkmwbemAJMKXu.nljDQfJxofEWjKNOQVvUJFNJxAjqA; i++)
		{
			int num = 8388608 << i;
			if ((bOFZUEPNgDgQSavjlJvfJaMptbnQA2.autoGeneratedValueFlags & num) == 0 && !string.IsNullOrEmpty(bOFZUEPNgDgQSavjlJvfJaMptbnQA2.key) && string.IsNullOrEmpty(bOFZUEPNgDgQSavjlJvfJaMptbnQA2.GetSpecialElementKey(i)))
			{
				string text = bOFZUEPNgDgQSavjlJvfJaMptbnQA2.key;
				if (fOURUkakBckGnlgOkmwbemAJMKXu.kjxfzmNdTUsBjoWkavsROrRXBLoe(i).hVoDmAuzzdsThlipnOyZAzFukJTU.HasValue)
				{
					text = LocalizationManager.AppendToKeyAxisDirection(text, fOURUkakBckGnlgOkmwbemAJMKXu.kjxfzmNdTUsBjoWkavsROrRXBLoe(i).hVoDmAuzzdsThlipnOyZAzFukJTU.Value);
				}
				bOFZUEPNgDgQSavjlJvfJaMptbnQA2.SetSpecialElementKey(i, text);
				bOFZUEPNgDgQSavjlJvfJaMptbnQA2.autoGeneratedValueFlags |= num;
				WNOKfMLBcQgmwLBfRHLEkGrCnlHM(num);
			}
			int num2 = 16384 << i;
			if ((bOFZUEPNgDgQSavjlJvfJaMptbnQA2.autoGeneratedValueFlags & num2) == 0 && !string.IsNullOrEmpty(bOFZUEPNgDgQSavjlJvfJaMptbnQA2.nonLocalizedDescriptiveName) && string.IsNullOrEmpty(bOFZUEPNgDgQSavjlJvfJaMptbnQA2.GetSpecialElementNonLocalizedDescriptiveName(i)))
			{
				string text2 = bOFZUEPNgDgQSavjlJvfJaMptbnQA2.nonLocalizedDescriptiveName;
				if (fOURUkakBckGnlgOkmwbemAJMKXu.kjxfzmNdTUsBjoWkavsROrRXBLoe(i).hVoDmAuzzdsThlipnOyZAzFukJTU.HasValue)
				{
					text2 = LocalizationManager.AppendToNameAxisDirection(text2, fOURUkakBckGnlgOkmwbemAJMKXu.kjxfzmNdTUsBjoWkavsROrRXBLoe(i).hVoDmAuzzdsThlipnOyZAzFukJTU.Value);
				}
				bOFZUEPNgDgQSavjlJvfJaMptbnQA2.SetSpecialElementNonLocalizedDescriptiveName(i, text2);
				bOFZUEPNgDgQSavjlJvfJaMptbnQA2.autoGeneratedValueFlags |= num2;
				WNOKfMLBcQgmwLBfRHLEkGrCnlHM(num2);
			}
		}
	}

	protected virtual void ybXifsrsJggaNLwbrePXcjDFPwucb(IWFfSiUJvBqDpiIZIfMeuQqJMGul P_0)
	{
		base.EfmhgRjLUYYNAKgnORbsBEMiVRrB(P_0);
		bOFZUEPNgDgQSavjlJvfJaMptbnQA bOFZUEPNgDgQSavjlJvfJaMptbnQA2 = JrNSXOoPbyfvCsYwXqkJnjIACSkQ();
		if (bOFZUEPNgDgQSavjlJvfJaMptbnQA2 == null || ((uint)bOFZUEPNgDgQSavjlJvfJaMptbnQA2.autoGeneratedValueFlags & (uint)P_0) == 0 || base.tnQKiUchqifinDnJuSQdboJqaQgK != sztzDKprOgaEtSRoFjITTczsHDuW.CompoundElement || !FDNFDGKMldROgCHjPdSVTnUzAnLgb.tGJPnPxMDZQkntURokRfyFQymnPw(base.bEKIbEjDpMfnJogudzLlVaoylrODb, out var fOURUkakBckGnlgOkmwbemAJMKXu))
		{
			return;
		}
		for (int i = 0; i < fOURUkakBckGnlgOkmwbemAJMKXu.nljDQfJxofEWjKNOQVvUJFNJxAjqA; i++)
		{
			int num = 8388608 << i;
			if ((bOFZUEPNgDgQSavjlJvfJaMptbnQA2.autoGeneratedValueFlags & num) != 0)
			{
				bOFZUEPNgDgQSavjlJvfJaMptbnQA2.SetSpecialElementKey(i, null);
				bOFZUEPNgDgQSavjlJvfJaMptbnQA2.autoGeneratedValueFlags &= ~num;
				WNOKfMLBcQgmwLBfRHLEkGrCnlHM(num);
			}
			int num2 = 16384 << i;
			if ((bOFZUEPNgDgQSavjlJvfJaMptbnQA2.autoGeneratedValueFlags & num2) != 0)
			{
				bOFZUEPNgDgQSavjlJvfJaMptbnQA2.SetSpecialElementNonLocalizedDescriptiveName(i, null);
				bOFZUEPNgDgQSavjlJvfJaMptbnQA2.autoGeneratedValueFlags &= ~num2;
				WNOKfMLBcQgmwLBfRHLEkGrCnlHM(num2);
			}
		}
	}

	protected virtual IWFfSiUJvBqDpiIZIfMeuQqJMGul YaJfRkLTDjljXKMZUmIqCDUFGFyS(cwXjjPkxPWMBcEFwnCUCcKJomfDI P_0)
	{
		IWFfSiUJvBqDpiIZIfMeuQqJMGul iWFfSiUJvBqDpiIZIfMeuQqJMGul = base.MYTaudXHwNmJAoFwqqafrbwMFkCFA(P_0);
		int num = EmBvRrmOxLyVerpWWUxvcvaHPtec;
		if ((P_0 & cwXjjPkxPWMBcEFwnCUCcKJomfDI.Keys) != cwXjjPkxPWMBcEFwnCUCcKJomfDI.None)
		{
			for (int i = 0; i < num; i++)
			{
				iWFfSiUJvBqDpiIZIfMeuQqJMGul = (IWFfSiUJvBqDpiIZIfMeuQqJMGul)((int)iWFfSiUJvBqDpiIZIfMeuQqJMGul | (8388608 << i));
			}
		}
		if ((P_0 & cwXjjPkxPWMBcEFwnCUCcKJomfDI.Names) != cwXjjPkxPWMBcEFwnCUCcKJomfDI.None)
		{
			for (int j = 0; j < num; j++)
			{
				iWFfSiUJvBqDpiIZIfMeuQqJMGul = (IWFfSiUJvBqDpiIZIfMeuQqJMGul)((int)iWFfSiUJvBqDpiIZIfMeuQqJMGul | (16384 << j));
			}
		}
		return iWFfSiUJvBqDpiIZIfMeuQqJMGul;
	}

	protected bOFZUEPNgDgQSavjlJvfJaMptbnQA JrNSXOoPbyfvCsYwXqkJnjIACSkQ()
	{
		return tFHgnqTfapMzUfeUcgrtSgOorhTm() as bOFZUEPNgDgQSavjlJvfJaMptbnQA;
	}

	protected virtual void nKDCsBClUGxclqBiTHKlsgxuTXVX()
	{
		base.eCoUKPYzeytCrbuDxEwhAldiAbYf();
		int num = EmBvRrmOxLyVerpWWUxvcvaHPtec;
		for (int i = 0; i < num; i++)
		{
			UZtpxFUPQZBSvGgnZjNTrWXUAlHF(i);
		}
	}

	protected virtual void PTqhAAHxspUblfjVnAWfZAYlsOvK()
	{
		KDsUceJlYCDVBhMNBMROGovUueSnA();
		if (base.tnQKiUchqifinDnJuSQdboJqaQgK != sztzDKprOgaEtSRoFjITTczsHDuW.CompoundElement)
		{
			return;
		}
		LsWebCorzTdhEUjUrAlgVzPmJJHR lsWebCorzTdhEUjUrAlgVzPmJJHR = base.bEKIbEjDpMfnJogudzLlVaoylrODb;
		if ((lsWebCorzTdhEUjUrAlgVzPmJJHR == LsWebCorzTdhEUjUrAlgVzPmJJHR.Axis2D || (uint)(lsWebCorzTdhEUjUrAlgVzPmJJHR - 3) <= 2u) && jwbVsaSgCaLLJfvJjylSjayHlbyi != null)
		{
			int num = EmBvRrmOxLyVerpWWUxvcvaHPtec;
			for (int i = 0; i < num; i++)
			{
				gHHpnMuGywauOByTsYtKEwUhbDMtA(1, new OBzZblFCcoXjpegrNwgWHpLkWsfD(jwbVsaSgCaLLJfvJjylSjayHlbyi[i], 16384 << i));
			}
		}
	}
}
