using System;
using Rewired;
using Rewired.Internal.Glyphs;
using Rewired.Internal.Localization;

internal abstract class tuBqkboMGQhtvUaslwCURlYjKxjB : qwCYZlXUhRSrBsVnztigTaoxgEur
{
	protected readonly KeyedGlyph ezAExQjkpCeLRFOGwIdJNVtzOEXB;

	protected readonly KeyedGlyph fCPAojmOCyZnyMuugjeHRupBcGIN;

	public abstract object ivgGbvjljGLQSbxeeHhSPwvwKzZb { get; }

	public abstract object yLUKfKXXayZNlhzpjLtAckROOAOB { get; }

	public abstract string YHLjcmxgqGUnWoepoFwHlpXwGlOQ { get; }

	public abstract string BOHsCXxxroVnAbuhrSFCqvZoizFN { get; }

	protected tuBqkboMGQhtvUaslwCURlYjKxjB(FDNFDGKMldROgCHjPdSVTnUzAnLgb.sztzDKprOgaEtSRoFjITTczsHDuW P_0, FDNFDGKMldROgCHjPdSVTnUzAnLgb.LsWebCorzTdhEUjUrAlgVzPmJJHR P_1)
		: base(P_0, P_1)
	{
		ezAExQjkpCeLRFOGwIdJNVtzOEXB = new KeyedGlyph();
		fCPAojmOCyZnyMuugjeHRupBcGIN = new KeyedGlyph();
	}

	protected tuBqkboMGQhtvUaslwCURlYjKxjB(vRDWZTvhTxtVFxhZXNeeonctREwv P_0, FDNFDGKMldROgCHjPdSVTnUzAnLgb.sztzDKprOgaEtSRoFjITTczsHDuW P_1, FDNFDGKMldROgCHjPdSVTnUzAnLgb.LsWebCorzTdhEUjUrAlgVzPmJJHR P_2)
		: base(P_0, P_1, P_2)
	{
		if (P_0 == null)
		{
			throw new ArgumentNullException("dataSource");
		}
		ezAExQjkpCeLRFOGwIdJNVtzOEXB = new KeyedGlyph();
		fCPAojmOCyZnyMuugjeHRupBcGIN = new KeyedGlyph();
	}

	protected virtual void eZlAScbkYaFaaFgaGQgKjeNdCQIqB()
	{
		qsiNTFFWkCaHHghrUFrlrwKWLYgc();
	}

	public virtual void uyDJJnQKvXNCjHQIhoaaSeiyQAQo(vRDWZTvhTxtVFxhZXNeeonctREwv P_0)
	{
		QAxXyYCvMGLPopqbVHETwtyFMYp(P_0);
	}

	public virtual void mcOXYqSPPhESVTMIfgcVKmdYACUDb(HQqbZoQigscgVQcdQGCMdxuNvzzS P_0)
	{
		base.QAxXyYCvMGLPopqbVHETwtyFMYp(P_0);
		if (!(P_0 is vRDWZTvhTxtVFxhZXNeeonctREwv))
		{
			throw new ArgumentException("value must implement " + typeof(vRDWZTvhTxtVFxhZXNeeonctREwv));
		}
	}

	public virtual void clgagPihHrDzLcuxhpRKTFKbbtnHB()
	{
		KmzkVsdajGhBLIOWKwewLUcsutOqA();
		ezAExQjkpCeLRFOGwIdJNVtzOEXB.Clear();
		fCPAojmOCyZnyMuugjeHRupBcGIN.Clear();
	}

	public void wDtluCxTkDRAbhRQXfjgiMsRFDsj()
	{
		ezAExQjkpCeLRFOGwIdJNVtzOEXB.Clear();
		tMayuIsQLYXoRyaFQofqKOJaetdi(FDNFDGKMldROgCHjPdSVTnUzAnLgb.cwXjjPkxPWMBcEFwnCUCcKJomfDI.Keys);
	}

	public void hMaAxAQUCbJuHAWpIwbObkVKtaNfA()
	{
		fCPAojmOCyZnyMuugjeHRupBcGIN.Clear();
		tMayuIsQLYXoRyaFQofqKOJaetdi(FDNFDGKMldROgCHjPdSVTnUzAnLgb.cwXjjPkxPWMBcEFwnCUCcKJomfDI.Keys);
	}

	public virtual bool KJWbLpcVyrMhvpzvhxXdcrUkmBYP(ZCteKPZRxTbUmaKieiJZhAaEJCygB P_0)
	{
		if (!(P_0 is tuBqkboMGQhtvUaslwCURlYjKxjB tuBqkboMGQhtvUaslwCURlYjKxjB2))
		{
			return false;
		}
		if (!IRbkeYQlVSjULCXcAuGgJxErcvUH(P_0))
		{
			return false;
		}
		vRDWZTvhTxtVFxhZXNeeonctREwv vRDWZTvhTxtVFxhZXNeeonctREwv2 = AAKsGNHagELacdKjFIpwDLqVeZeB();
		vRDWZTvhTxtVFxhZXNeeonctREwv vRDWZTvhTxtVFxhZXNeeonctREwv3 = tuBqkboMGQhtvUaslwCURlYjKxjB2.AAKsGNHagELacdKjFIpwDLqVeZeB();
		if (vRDWZTvhTxtVFxhZXNeeonctREwv2 == null != (vRDWZTvhTxtVFxhZXNeeonctREwv3 == null))
		{
			return false;
		}
		if (vRDWZTvhTxtVFxhZXNeeonctREwv2 != null && (!string.Equals(vRDWZTvhTxtVFxhZXNeeonctREwv2.positiveKey, vRDWZTvhTxtVFxhZXNeeonctREwv3.positiveKey, StringComparison.Ordinal) || !string.Equals(vRDWZTvhTxtVFxhZXNeeonctREwv2.negativeKey, vRDWZTvhTxtVFxhZXNeeonctREwv3.negativeKey, StringComparison.Ordinal)))
		{
			return false;
		}
		return true;
	}

	protected virtual void LVgichliLFxHmLlvrPpcevZydyPv()
	{
		czbubsWEIcNhAduyhhXvcTrgoGuK();
		ezAExQjkpCeLRFOGwIdJNVtzOEXB.Clear();
		fCPAojmOCyZnyMuugjeHRupBcGIN.Clear();
	}

	protected virtual void dHvptIrPLDCJuGBYQRZDkBLuicXfb(FDNFDGKMldROgCHjPdSVTnUzAnLgb.cwXjjPkxPWMBcEFwnCUCcKJomfDI P_0)
	{
		base.tMayuIsQLYXoRyaFQofqKOJaetdi(P_0);
		vRDWZTvhTxtVFxhZXNeeonctREwv vRDWZTvhTxtVFxhZXNeeonctREwv2 = AAKsGNHagELacdKjFIpwDLqVeZeB();
		if (vRDWZTvhTxtVFxhZXNeeonctREwv2 == null || string.IsNullOrEmpty(vRDWZTvhTxtVFxhZXNeeonctREwv2.key))
		{
			return;
		}
		if ((vRDWZTvhTxtVFxhZXNeeonctREwv2.autoGeneratedValueFlags & 8) == 0 && string.IsNullOrEmpty(vRDWZTvhTxtVFxhZXNeeonctREwv2.positiveKey) && lWFFCdFNGnSjLpPDvEodJWQqESvM(Pole.Positive))
		{
			vRDWZTvhTxtVFxhZXNeeonctREwv2.positiveKey = vRDWZTvhTxtVFxhZXNeeonctREwv2.key;
			if (DcmXqYnhsScEkXteQXLfkwvQuinK(Pole.Positive))
			{
				vRDWZTvhTxtVFxhZXNeeonctREwv2.positiveKey = LocalizationManager.AppendToKeyAxisPole(vRDWZTvhTxtVFxhZXNeeonctREwv2.positiveKey, Pole.Positive);
			}
			vRDWZTvhTxtVFxhZXNeeonctREwv2.autoGeneratedValueFlags |= 8;
			QsUCZNOSicazMKHKLTixYAhXAyft(8);
		}
		if ((vRDWZTvhTxtVFxhZXNeeonctREwv2.autoGeneratedValueFlags & 0x10) == 0 && string.IsNullOrEmpty(vRDWZTvhTxtVFxhZXNeeonctREwv2.negativeKey) && lWFFCdFNGnSjLpPDvEodJWQqESvM(Pole.Negative))
		{
			vRDWZTvhTxtVFxhZXNeeonctREwv2.negativeKey = vRDWZTvhTxtVFxhZXNeeonctREwv2.key;
			if (DcmXqYnhsScEkXteQXLfkwvQuinK(Pole.Negative))
			{
				vRDWZTvhTxtVFxhZXNeeonctREwv2.negativeKey = LocalizationManager.AppendToKeyAxisPole(vRDWZTvhTxtVFxhZXNeeonctREwv2.negativeKey, Pole.Negative);
			}
			vRDWZTvhTxtVFxhZXNeeonctREwv2.autoGeneratedValueFlags |= 16;
			QsUCZNOSicazMKHKLTixYAhXAyft(16);
		}
	}

	protected virtual void BgpjGEhOprbHPpNfcEYnmOMukcyHb(FDNFDGKMldROgCHjPdSVTnUzAnLgb.IWFfSiUJvBqDpiIZIfMeuQqJMGul P_0)
	{
		base.hliIBmbqiCkrOaIzfryRFuzvoUmt(P_0);
		vRDWZTvhTxtVFxhZXNeeonctREwv vRDWZTvhTxtVFxhZXNeeonctREwv2 = AAKsGNHagELacdKjFIpwDLqVeZeB();
		if (vRDWZTvhTxtVFxhZXNeeonctREwv2 != null && ((uint)vRDWZTvhTxtVFxhZXNeeonctREwv2.autoGeneratedValueFlags & (uint)P_0) != 0)
		{
			if ((P_0 & FDNFDGKMldROgCHjPdSVTnUzAnLgb.IWFfSiUJvBqDpiIZIfMeuQqJMGul.PositiveKey) != FDNFDGKMldROgCHjPdSVTnUzAnLgb.IWFfSiUJvBqDpiIZIfMeuQqJMGul.None && (vRDWZTvhTxtVFxhZXNeeonctREwv2.autoGeneratedValueFlags & 8) != 0)
			{
				vRDWZTvhTxtVFxhZXNeeonctREwv2.positiveKey = null;
				QsUCZNOSicazMKHKLTixYAhXAyft(8);
				vRDWZTvhTxtVFxhZXNeeonctREwv2.autoGeneratedValueFlags &= -9;
			}
			if ((P_0 & FDNFDGKMldROgCHjPdSVTnUzAnLgb.IWFfSiUJvBqDpiIZIfMeuQqJMGul.NegativeKey) != FDNFDGKMldROgCHjPdSVTnUzAnLgb.IWFfSiUJvBqDpiIZIfMeuQqJMGul.None && (vRDWZTvhTxtVFxhZXNeeonctREwv2.autoGeneratedValueFlags & 0x10) != 0)
			{
				vRDWZTvhTxtVFxhZXNeeonctREwv2.negativeKey = null;
				QsUCZNOSicazMKHKLTixYAhXAyft(16);
				vRDWZTvhTxtVFxhZXNeeonctREwv2.autoGeneratedValueFlags &= -17;
			}
		}
	}

	protected virtual FDNFDGKMldROgCHjPdSVTnUzAnLgb.IWFfSiUJvBqDpiIZIfMeuQqJMGul uNGdQFErihEVCRqfPsqTPdwVXXNk(FDNFDGKMldROgCHjPdSVTnUzAnLgb.cwXjjPkxPWMBcEFwnCUCcKJomfDI P_0)
	{
		FDNFDGKMldROgCHjPdSVTnUzAnLgb.IWFfSiUJvBqDpiIZIfMeuQqJMGul iWFfSiUJvBqDpiIZIfMeuQqJMGul = base.EmHCnifFrHRBPDcsfUpvKXiEwuICA(P_0);
		if ((P_0 & FDNFDGKMldROgCHjPdSVTnUzAnLgb.cwXjjPkxPWMBcEFwnCUCcKJomfDI.Keys) != FDNFDGKMldROgCHjPdSVTnUzAnLgb.cwXjjPkxPWMBcEFwnCUCcKJomfDI.None)
		{
			iWFfSiUJvBqDpiIZIfMeuQqJMGul |= (FDNFDGKMldROgCHjPdSVTnUzAnLgb.IWFfSiUJvBqDpiIZIfMeuQqJMGul)24;
		}
		return iWFfSiUJvBqDpiIZIfMeuQqJMGul;
	}

	protected vRDWZTvhTxtVFxhZXNeeonctREwv AAKsGNHagELacdKjFIpwDLqVeZeB()
	{
		return mTZTIPnsHjouJscecTzhOxkyLBCX() as vRDWZTvhTxtVFxhZXNeeonctREwv;
	}

	protected virtual bool DcmXqYnhsScEkXteQXLfkwvQuinK(Pole P_0)
	{
		return base.wqOdiMjEIcQdAMDjSwXWDxtwrCnx switch
		{
			FDNFDGKMldROgCHjPdSVTnUzAnLgb.sztzDKprOgaEtSRoFjITTczsHDuW.Axis => true, 
			FDNFDGKMldROgCHjPdSVTnUzAnLgb.sztzDKprOgaEtSRoFjITTczsHDuW.Button => false, 
			_ => false, 
		};
	}

	protected virtual bool lWFFCdFNGnSjLpPDvEodJWQqESvM(Pole P_0)
	{
		return base.wqOdiMjEIcQdAMDjSwXWDxtwrCnx switch
		{
			FDNFDGKMldROgCHjPdSVTnUzAnLgb.sztzDKprOgaEtSRoFjITTczsHDuW.Axis => true, 
			FDNFDGKMldROgCHjPdSVTnUzAnLgb.sztzDKprOgaEtSRoFjITTczsHDuW.Button => P_0 switch
			{
				Pole.Positive => true, 
				Pole.Negative => false, 
				_ => false, 
			}, 
			_ => false, 
		};
	}

	protected virtual void HnWvBArotrJtlooNcpusmnyWHgKD()
	{
		base.tCgFabDNaInoTqPiHLGuoxNDlTKN();
		_ = ivgGbvjljGLQSbxeeHhSPwvwKzZb;
		_ = yLUKfKXXayZNlhzpjLtAckROOAOB;
	}

	protected virtual void yHNDtraRtSnPeBZZkmdMJTnCWhvg()
	{
		TwwHjHcRsTtsMchrKnIghIedfCQF();
		piakUSCLcudJRhZilcQmLsckObsUA(8, new RTLJigdPBumdJaIlwNYFaZzbdnrR
		{
			bgcEhOhwfuxKZtuHkopcUGIuSvyA = ezAExQjkpCeLRFOGwIdJNVtzOEXB
		});
		piakUSCLcudJRhZilcQmLsckObsUA(16, new RTLJigdPBumdJaIlwNYFaZzbdnrR
		{
			bgcEhOhwfuxKZtuHkopcUGIuSvyA = fCPAojmOCyZnyMuugjeHRupBcGIN
		});
	}
}
