using System;

internal class wlBeZVzMrOSaPhoZNWiGbiPoInUiA : HQqbZoQigscgVQcdQGCMdxuNvzzS
{
	protected readonly qwCYZlXUhRSrBsVnztigTaoxgEur vgmzkPhqbACbbHBPzpHVXXdserlCA;

	private readonly string wsGArAlDKYmIolsgtxTAWImDpyVD;

	private readonly string mEqrLwEeQsKNwbiDygLFGquOSHfPA;

	private int yYYrEnQbylqGcSokuaMbVrnLDlsH;

	public qwCYZlXUhRSrBsVnztigTaoxgEur ZHWZyKZfukIGqpMnZnoOAfPoEqiT => vgmzkPhqbACbbHBPzpHVXXdserlCA;

	string HQqbZoQigscgVQcdQGCMdxuNvzzS.keyCategory => wsGArAlDKYmIolsgtxTAWImDpyVD;

	string HQqbZoQigscgVQcdQGCMdxuNvzzS.key => mEqrLwEeQsKNwbiDygLFGquOSHfPA;

	int HQqbZoQigscgVQcdQGCMdxuNvzzS.autoGeneratedValueFlags
	{
		get
		{
			return yYYrEnQbylqGcSokuaMbVrnLDlsH;
		}
		set
		{
			yYYrEnQbylqGcSokuaMbVrnLDlsH = value;
		}
	}

	public string keyCategory => wsGArAlDKYmIolsgtxTAWImDpyVD;

	public string key => mEqrLwEeQsKNwbiDygLFGquOSHfPA;

	public wlBeZVzMrOSaPhoZNWiGbiPoInUiA(qwCYZlXUhRSrBsVnztigTaoxgEur P_0, string P_1, string P_2)
	{
		if (P_0 == null)
		{
			throw new ArgumentNullException();
		}
		vgmzkPhqbACbbHBPzpHVXXdserlCA = P_0;
		wsGArAlDKYmIolsgtxTAWImDpyVD = P_1;
		mEqrLwEeQsKNwbiDygLFGquOSHfPA = P_2;
		P_0.QAxXyYCvMGLPopqbVHETwtyFMYp(this);
	}

	public virtual bool UwjrvhCktxFvKBXKYmXrPCuzjJGB(wlBeZVzMrOSaPhoZNWiGbiPoInUiA P_0)
	{
		if (P_0 == null)
		{
			return false;
		}
		if ((object)GetType() != P_0.GetType())
		{
			return false;
		}
		if (!vgmzkPhqbACbbHBPzpHVXXdserlCA.qCFiRDjEOHkqdfmCYPvVKSPPChWf(P_0.vgmzkPhqbACbbHBPzpHVXXdserlCA))
		{
			return false;
		}
		return true;
	}
}
