using System;
using Rewired.Internal.Glyphs;
using Rewired.Internal.Localization;

internal abstract class xuHAMsPRrvFcgexXBjGajRCrxuIrA : qwCYZlXUhRSrBsVnztigTaoxgEur
{
	protected KeyedGlyph[] EuWvVkicGdspLKtexwjwbWJFrnnC;

	public int OjXgszImhXNPnIOPoXNdfWcCKqDkb => FDNFDGKMldROgCHjPdSVTnUzAnLgb.FaWRBKagAChKzYIPTHxodNThJXtKA(base.wqOdiMjEIcQdAMDjSwXWDxtwrCnx, base.IZNtPIPgpZUaKCjlrRZfskAbHxRI);

	public abstract object XmlgGslFtGJifkBoPmYBBdHirZpm(int P_0);

	public abstract string LiGFhODBRwkVpOqUDPjgnZGYaAyNA(int P_0);

	protected xuHAMsPRrvFcgexXBjGajRCrxuIrA(FDNFDGKMldROgCHjPdSVTnUzAnLgb.sztzDKprOgaEtSRoFjITTczsHDuW P_0, FDNFDGKMldROgCHjPdSVTnUzAnLgb.LsWebCorzTdhEUjUrAlgVzPmJJHR P_1)
		: base(P_0, P_1)
	{
	}

	protected xuHAMsPRrvFcgexXBjGajRCrxuIrA(qRYbqBqElSaesizKXsECcXURAVVeb P_0, FDNFDGKMldROgCHjPdSVTnUzAnLgb.sztzDKprOgaEtSRoFjITTczsHDuW P_1, FDNFDGKMldROgCHjPdSVTnUzAnLgb.LsWebCorzTdhEUjUrAlgVzPmJJHR P_2)
		: base(P_0, P_1, P_2)
	{
		if (P_0 == null)
		{
			throw new ArgumentNullException("dataSource");
		}
	}

	protected virtual void muMXgHEvytGmHJLqOzsMaSzmldmw()
	{
		int num = OjXgszImhXNPnIOPoXNdfWcCKqDkb;
		EuWvVkicGdspLKtexwjwbWJFrnnC = null;
		if (num > 0)
		{
			EuWvVkicGdspLKtexwjwbWJFrnnC = new KeyedGlyph[num];
			for (int i = 0; i < num; i++)
			{
				EuWvVkicGdspLKtexwjwbWJFrnnC[i] = new KeyedGlyph();
			}
		}
		qsiNTFFWkCaHHghrUFrlrwKWLYgc();
	}

	public virtual void fclcWmCUDMSCZKoXMKvIkvhhdkXyA(qRYbqBqElSaesizKXsECcXURAVVeb P_0)
	{
		QAxXyYCvMGLPopqbVHETwtyFMYp(P_0);
	}

	public virtual void wbKAzVNPwKdjZwggeGxLaoAVJUhE(HQqbZoQigscgVQcdQGCMdxuNvzzS P_0)
	{
		base.QAxXyYCvMGLPopqbVHETwtyFMYp(P_0);
		if (!(P_0 is qRYbqBqElSaesizKXsECcXURAVVeb))
		{
			throw new ArgumentException("value must implement " + typeof(qRYbqBqElSaesizKXsECcXURAVVeb));
		}
	}

	public virtual void eSHZHqBNTJJEQtuodlXzFddudeNY()
	{
		KmzkVsdajGhBLIOWKwewLUcsutOqA();
		if (EuWvVkicGdspLKtexwjwbWJFrnnC != null)
		{
			for (int i = 0; i < OjXgszImhXNPnIOPoXNdfWcCKqDkb; i++)
			{
				EuWvVkicGdspLKtexwjwbWJFrnnC[i].Clear();
			}
		}
	}

	public virtual bool XcEuAiGzMflFkOCooEyWeLOfDVxe(ZCteKPZRxTbUmaKieiJZhAaEJCygB P_0)
	{
		if (!(P_0 is xuHAMsPRrvFcgexXBjGajRCrxuIrA xuHAMsPRrvFcgexXBjGajRCrxuIrA2))
		{
			return false;
		}
		if (!IRbkeYQlVSjULCXcAuGgJxErcvUH(P_0))
		{
			return false;
		}
		qRYbqBqElSaesizKXsECcXURAVVeb qRYbqBqElSaesizKXsECcXURAVVeb2 = dtnANHBYQkwfrIhHCASFpUHwWUUM();
		qRYbqBqElSaesizKXsECcXURAVVeb qRYbqBqElSaesizKXsECcXURAVVeb3 = xuHAMsPRrvFcgexXBjGajRCrxuIrA2.dtnANHBYQkwfrIhHCASFpUHwWUUM();
		if (qRYbqBqElSaesizKXsECcXURAVVeb2 == null != (qRYbqBqElSaesizKXsECcXURAVVeb3 == null))
		{
			return false;
		}
		if (qRYbqBqElSaesizKXsECcXURAVVeb2 != null)
		{
			int num = OjXgszImhXNPnIOPoXNdfWcCKqDkb;
			for (int i = 0; i < num; i++)
			{
				if (!string.Equals(qRYbqBqElSaesizKXsECcXURAVVeb2.GetSpecialElementKey(i), qRYbqBqElSaesizKXsECcXURAVVeb3.GetSpecialElementKey(i), StringComparison.Ordinal))
				{
					return false;
				}
			}
		}
		return true;
	}

	protected virtual void bruGjtapRHjlWgBrGdiNMfObnZNLc()
	{
		czbubsWEIcNhAduyhhXvcTrgoGuK();
		if (EuWvVkicGdspLKtexwjwbWJFrnnC != null)
		{
			for (int i = 0; i < EuWvVkicGdspLKtexwjwbWJFrnnC.Length; i++)
			{
				EuWvVkicGdspLKtexwjwbWJFrnnC[i].Clear();
			}
		}
	}

	protected virtual void rRtOZvKHJiOdNXNhpbBzcpvKqGmaA(FDNFDGKMldROgCHjPdSVTnUzAnLgb.cwXjjPkxPWMBcEFwnCUCcKJomfDI P_0)
	{
		base.tMayuIsQLYXoRyaFQofqKOJaetdi(P_0);
		qRYbqBqElSaesizKXsECcXURAVVeb qRYbqBqElSaesizKXsECcXURAVVeb2 = dtnANHBYQkwfrIhHCASFpUHwWUUM();
		if (qRYbqBqElSaesizKXsECcXURAVVeb2 == null || base.wqOdiMjEIcQdAMDjSwXWDxtwrCnx != FDNFDGKMldROgCHjPdSVTnUzAnLgb.sztzDKprOgaEtSRoFjITTczsHDuW.CompoundElement || !FDNFDGKMldROgCHjPdSVTnUzAnLgb.tGJPnPxMDZQkntURokRfyFQymnPw(base.IZNtPIPgpZUaKCjlrRZfskAbHxRI, out var fOURUkakBckGnlgOkmwbemAJMKXu))
		{
			return;
		}
		for (int i = 0; i < fOURUkakBckGnlgOkmwbemAJMKXu.nljDQfJxofEWjKNOQVvUJFNJxAjqA; i++)
		{
			int num = 8388608 << i;
			if ((qRYbqBqElSaesizKXsECcXURAVVeb2.autoGeneratedValueFlags & num) == 0 && !string.IsNullOrEmpty(qRYbqBqElSaesizKXsECcXURAVVeb2.key) && string.IsNullOrEmpty(qRYbqBqElSaesizKXsECcXURAVVeb2.GetSpecialElementKey(i)))
			{
				string text = qRYbqBqElSaesizKXsECcXURAVVeb2.key;
				if (fOURUkakBckGnlgOkmwbemAJMKXu.kjxfzmNdTUsBjoWkavsROrRXBLoe(i).hVoDmAuzzdsThlipnOyZAzFukJTU.HasValue)
				{
					text = LocalizationManager.AppendToKeyAxisDirection(text, fOURUkakBckGnlgOkmwbemAJMKXu.kjxfzmNdTUsBjoWkavsROrRXBLoe(i).hVoDmAuzzdsThlipnOyZAzFukJTU.Value);
				}
				qRYbqBqElSaesizKXsECcXURAVVeb2.SetSpecialElementKey(i, text);
				qRYbqBqElSaesizKXsECcXURAVVeb2.autoGeneratedValueFlags |= num;
				QsUCZNOSicazMKHKLTixYAhXAyft(num);
			}
		}
	}

	protected virtual void GeKCiuxpJqHgMASukGbZfPSpNoZZA(FDNFDGKMldROgCHjPdSVTnUzAnLgb.IWFfSiUJvBqDpiIZIfMeuQqJMGul P_0)
	{
		base.hliIBmbqiCkrOaIzfryRFuzvoUmt(P_0);
		qRYbqBqElSaesizKXsECcXURAVVeb qRYbqBqElSaesizKXsECcXURAVVeb2 = dtnANHBYQkwfrIhHCASFpUHwWUUM();
		if (qRYbqBqElSaesizKXsECcXURAVVeb2 == null || ((uint)qRYbqBqElSaesizKXsECcXURAVVeb2.autoGeneratedValueFlags & (uint)P_0) == 0 || base.wqOdiMjEIcQdAMDjSwXWDxtwrCnx != FDNFDGKMldROgCHjPdSVTnUzAnLgb.sztzDKprOgaEtSRoFjITTczsHDuW.CompoundElement || !FDNFDGKMldROgCHjPdSVTnUzAnLgb.tGJPnPxMDZQkntURokRfyFQymnPw(base.IZNtPIPgpZUaKCjlrRZfskAbHxRI, out var fOURUkakBckGnlgOkmwbemAJMKXu))
		{
			return;
		}
		for (int i = 0; i < fOURUkakBckGnlgOkmwbemAJMKXu.nljDQfJxofEWjKNOQVvUJFNJxAjqA; i++)
		{
			int num = 8388608 << i;
			if ((qRYbqBqElSaesizKXsECcXURAVVeb2.autoGeneratedValueFlags & num) != 0)
			{
				qRYbqBqElSaesizKXsECcXURAVVeb2.SetSpecialElementKey(i, null);
				qRYbqBqElSaesizKXsECcXURAVVeb2.autoGeneratedValueFlags &= ~num;
				QsUCZNOSicazMKHKLTixYAhXAyft(num);
			}
		}
	}

	protected virtual FDNFDGKMldROgCHjPdSVTnUzAnLgb.IWFfSiUJvBqDpiIZIfMeuQqJMGul tzgKFNyVrqsNylmxUrCLWuDmmHIG(FDNFDGKMldROgCHjPdSVTnUzAnLgb.cwXjjPkxPWMBcEFwnCUCcKJomfDI P_0)
	{
		FDNFDGKMldROgCHjPdSVTnUzAnLgb.IWFfSiUJvBqDpiIZIfMeuQqJMGul iWFfSiUJvBqDpiIZIfMeuQqJMGul = base.EmHCnifFrHRBPDcsfUpvKXiEwuICA(P_0);
		int num = OjXgszImhXNPnIOPoXNdfWcCKqDkb;
		if ((P_0 & FDNFDGKMldROgCHjPdSVTnUzAnLgb.cwXjjPkxPWMBcEFwnCUCcKJomfDI.Keys) != FDNFDGKMldROgCHjPdSVTnUzAnLgb.cwXjjPkxPWMBcEFwnCUCcKJomfDI.None)
		{
			for (int i = 0; i < num; i++)
			{
				iWFfSiUJvBqDpiIZIfMeuQqJMGul = (FDNFDGKMldROgCHjPdSVTnUzAnLgb.IWFfSiUJvBqDpiIZIfMeuQqJMGul)((int)iWFfSiUJvBqDpiIZIfMeuQqJMGul | (8388608 << i));
			}
		}
		return iWFfSiUJvBqDpiIZIfMeuQqJMGul;
	}

	protected qRYbqBqElSaesizKXsECcXURAVVeb dtnANHBYQkwfrIhHCASFpUHwWUUM()
	{
		return mTZTIPnsHjouJscecTzhOxkyLBCX() as qRYbqBqElSaesizKXsECcXURAVVeb;
	}

	protected virtual void mCRMDoLyDsPwkkxvyOxWIXLsrEGh()
	{
		base.tCgFabDNaInoTqPiHLGuoxNDlTKN();
		int num = OjXgszImhXNPnIOPoXNdfWcCKqDkb;
		for (int i = 0; i < num; i++)
		{
			XmlgGslFtGJifkBoPmYBBdHirZpm(i);
		}
	}

	protected virtual void juRbrLYRBljsWHLueifvCfKbsDSK()
	{
		TwwHjHcRsTtsMchrKnIghIedfCQF();
	}
}
