using System;
using Rewired;
using Rewired.Internal.Localization;

internal abstract class zdotiSqMsHWmJGMFDBBIfDknpSrqA : FDNFDGKMldROgCHjPdSVTnUzAnLgb
{
	protected readonly LocalizedString EmWRFnLFeWCswGUFMLlLjSxsndSIA;

	protected readonly LocalizedString eWcBnrCtmGcAsuKkcBHpeNOiZPLWB;

	public abstract string ypoFNNDaQTVeKqsDkwEcIpgjZwGfA { get; }

	public abstract string CIYbIIBbIoEXdOMvSfyWNziRLZjc { get; }

	protected zdotiSqMsHWmJGMFDBBIfDknpSrqA(sztzDKprOgaEtSRoFjITTczsHDuW P_0, LsWebCorzTdhEUjUrAlgVzPmJJHR P_1)
		: base(P_0, P_1)
	{
		EmWRFnLFeWCswGUFMLlLjSxsndSIA = new LocalizedString();
		eWcBnrCtmGcAsuKkcBHpeNOiZPLWB = new LocalizedString();
	}

	protected zdotiSqMsHWmJGMFDBBIfDknpSrqA(lOhdpMIGSdyahJLjLKbbeUkHQJxnB P_0, sztzDKprOgaEtSRoFjITTczsHDuW P_1, LsWebCorzTdhEUjUrAlgVzPmJJHR P_2)
		: base(P_0, P_1, P_2)
	{
		if (P_0 == null)
		{
			throw new ArgumentNullException("dataSource");
		}
		EmWRFnLFeWCswGUFMLlLjSxsndSIA = new LocalizedString();
		eWcBnrCtmGcAsuKkcBHpeNOiZPLWB = new LocalizedString();
	}

	protected virtual void DhRSwHBUCoGgmhAlPCftsYAJRGMf()
	{
		UnrybsryaIWFpZtUNyuzUDGOqKMH();
	}

	public virtual void GtEtRrsVCeQEvNzNMrZWMNijwvXt(lOhdpMIGSdyahJLjLKbbeUkHQJxnB P_0)
	{
		FSygSkZkOZRlfprpDasbAbVdqyGH(P_0);
	}

	public virtual void SpUdpSWodsAhmeBRiJxkCrDDlNxcA(bguKJVtsagJfXPpJQeurpzlOLIYd P_0)
	{
		base.FSygSkZkOZRlfprpDasbAbVdqyGH(P_0);
		if (!(P_0 is lOhdpMIGSdyahJLjLKbbeUkHQJxnB))
		{
			throw new ArgumentException("value must implement " + typeof(lOhdpMIGSdyahJLjLKbbeUkHQJxnB));
		}
	}

	public virtual void ZcPXOTCSPHUIlOMttPemwXPSgubU()
	{
		IKlsylKZUPoPZutFmVypQCUyJCdT();
		EmWRFnLFeWCswGUFMLlLjSxsndSIA.Clear();
		eWcBnrCtmGcAsuKkcBHpeNOiZPLWB.Clear();
	}

	public virtual void ycLHNvAHOMixrTtdMICDMdSqQXSaA()
	{
		sUWPMtNBLWLNaHkrSGMrmklXilrKA();
		EmWRFnLFeWCswGUFMLlLjSxsndSIA.Clear();
		eWcBnrCtmGcAsuKkcBHpeNOiZPLWB.Clear();
	}

	public void hbWgZphUlHKneWgRXAGuHIpOkDoyA()
	{
		EmWRFnLFeWCswGUFMLlLjSxsndSIA.Clear();
		nIhCTLejCUDzcAzoRcmLjSsBLnitA(cwXjjPkxPWMBcEFwnCUCcKJomfDI.Keys);
	}

	public void ERYkzklgqAvssoFtgdVhiVrfrvqpA()
	{
		eWcBnrCtmGcAsuKkcBHpeNOiZPLWB.Clear();
		nIhCTLejCUDzcAzoRcmLjSsBLnitA(cwXjjPkxPWMBcEFwnCUCcKJomfDI.Keys);
	}

	public void nFzBoFXBNysVIMLFgBueCHpnWLDe()
	{
		EmWRFnLFeWCswGUFMLlLjSxsndSIA.Clear();
		nIhCTLejCUDzcAzoRcmLjSsBLnitA(cwXjjPkxPWMBcEFwnCUCcKJomfDI.Names);
	}

	public void GjiLKqPVUrrLpJzFcrhtOPEtLQgk()
	{
		eWcBnrCtmGcAsuKkcBHpeNOiZPLWB.Clear();
		nIhCTLejCUDzcAzoRcmLjSsBLnitA(cwXjjPkxPWMBcEFwnCUCcKJomfDI.Names);
	}

	public virtual bool HnOtiJjEAGEppfGiLxENbJtJQTyfA(FopEdGIdXdIETmMGGpfJptNngDfeb P_0, bool P_1)
	{
		if (!(P_0 is zdotiSqMsHWmJGMFDBBIfDknpSrqA zdotiSqMsHWmJGMFDBBIfDknpSrqA2))
		{
			return false;
		}
		if (!TIbllctYhBPpFlqcVRhFKAQKVURc(P_0, P_1))
		{
			return false;
		}
		lOhdpMIGSdyahJLjLKbbeUkHQJxnB lOhdpMIGSdyahJLjLKbbeUkHQJxnB2 = aymUlkLwdVCotZlKiVYDmhTNEVBU();
		lOhdpMIGSdyahJLjLKbbeUkHQJxnB lOhdpMIGSdyahJLjLKbbeUkHQJxnB3 = zdotiSqMsHWmJGMFDBBIfDknpSrqA2.aymUlkLwdVCotZlKiVYDmhTNEVBU();
		if (lOhdpMIGSdyahJLjLKbbeUkHQJxnB2 == null != (lOhdpMIGSdyahJLjLKbbeUkHQJxnB3 == null))
		{
			return false;
		}
		if (lOhdpMIGSdyahJLjLKbbeUkHQJxnB2 != null && P_1 && (!string.Equals(lOhdpMIGSdyahJLjLKbbeUkHQJxnB2.positiveKey, lOhdpMIGSdyahJLjLKbbeUkHQJxnB3.positiveKey, StringComparison.Ordinal) || !string.Equals(lOhdpMIGSdyahJLjLKbbeUkHQJxnB2.negativeKey, lOhdpMIGSdyahJLjLKbbeUkHQJxnB3.negativeKey, StringComparison.Ordinal) || !string.Equals(lOhdpMIGSdyahJLjLKbbeUkHQJxnB2.nonLocalizedPositiveDescriptiveName, lOhdpMIGSdyahJLjLKbbeUkHQJxnB3.nonLocalizedPositiveDescriptiveName, StringComparison.Ordinal) || !string.Equals(lOhdpMIGSdyahJLjLKbbeUkHQJxnB2.nonLocalizedNegativeDescriptiveName, lOhdpMIGSdyahJLjLKbbeUkHQJxnB3.nonLocalizedNegativeDescriptiveName, StringComparison.Ordinal)))
		{
			return false;
		}
		return true;
	}

	protected virtual void WMXfllbJKAGDKEIxApFjDoihZWQjc()
	{
		bnDwmhTjXYwxCTTxOQceUSJDV();
		EmWRFnLFeWCswGUFMLlLjSxsndSIA.Clear();
		eWcBnrCtmGcAsuKkcBHpeNOiZPLWB.Clear();
	}

	protected virtual void IZCAELzoFeyRUzPVARqKAgrELlQr(cwXjjPkxPWMBcEFwnCUCcKJomfDI P_0)
	{
		base.nIhCTLejCUDzcAzoRcmLjSsBLnitA(P_0);
		lOhdpMIGSdyahJLjLKbbeUkHQJxnB lOhdpMIGSdyahJLjLKbbeUkHQJxnB2 = aymUlkLwdVCotZlKiVYDmhTNEVBU();
		if (lOhdpMIGSdyahJLjLKbbeUkHQJxnB2 == null)
		{
			return;
		}
		if ((lOhdpMIGSdyahJLjLKbbeUkHQJxnB2.autoGeneratedValueFlags & 2) == 0 && string.IsNullOrEmpty(lOhdpMIGSdyahJLjLKbbeUkHQJxnB2.nonLocalizedPositiveDescriptiveName) && fVPibPAwXXbhXGcJdASDzpsOjkcS(Pole.Positive))
		{
			lOhdpMIGSdyahJLjLKbbeUkHQJxnB2.nonLocalizedPositiveDescriptiveName = lOhdpMIGSdyahJLjLKbbeUkHQJxnB2.nonLocalizedDescriptiveName;
			if (skxgvaBdTdsRurUIZiOBHfjiunfgA(Pole.Positive))
			{
				lOhdpMIGSdyahJLjLKbbeUkHQJxnB2.nonLocalizedPositiveDescriptiveName = LocalizationManager.AppendToNameAxisPole(lOhdpMIGSdyahJLjLKbbeUkHQJxnB2.nonLocalizedPositiveDescriptiveName, Pole.Positive);
			}
			lOhdpMIGSdyahJLjLKbbeUkHQJxnB2.autoGeneratedValueFlags |= 2;
			WNOKfMLBcQgmwLBfRHLEkGrCnlHM(2);
		}
		if ((lOhdpMIGSdyahJLjLKbbeUkHQJxnB2.autoGeneratedValueFlags & 4) == 0 && string.IsNullOrEmpty(lOhdpMIGSdyahJLjLKbbeUkHQJxnB2.nonLocalizedNegativeDescriptiveName) && fVPibPAwXXbhXGcJdASDzpsOjkcS(Pole.Negative))
		{
			lOhdpMIGSdyahJLjLKbbeUkHQJxnB2.nonLocalizedNegativeDescriptiveName = lOhdpMIGSdyahJLjLKbbeUkHQJxnB2.nonLocalizedDescriptiveName;
			if (skxgvaBdTdsRurUIZiOBHfjiunfgA(Pole.Negative))
			{
				lOhdpMIGSdyahJLjLKbbeUkHQJxnB2.nonLocalizedNegativeDescriptiveName = LocalizationManager.AppendToNameAxisPole(lOhdpMIGSdyahJLjLKbbeUkHQJxnB2.nonLocalizedNegativeDescriptiveName, Pole.Negative);
			}
			lOhdpMIGSdyahJLjLKbbeUkHQJxnB2.autoGeneratedValueFlags |= 4;
			WNOKfMLBcQgmwLBfRHLEkGrCnlHM(4);
		}
		if (string.IsNullOrEmpty(lOhdpMIGSdyahJLjLKbbeUkHQJxnB2.key))
		{
			return;
		}
		if ((lOhdpMIGSdyahJLjLKbbeUkHQJxnB2.autoGeneratedValueFlags & 8) == 0 && string.IsNullOrEmpty(lOhdpMIGSdyahJLjLKbbeUkHQJxnB2.positiveKey) && fVPibPAwXXbhXGcJdASDzpsOjkcS(Pole.Positive))
		{
			lOhdpMIGSdyahJLjLKbbeUkHQJxnB2.positiveKey = lOhdpMIGSdyahJLjLKbbeUkHQJxnB2.key;
			if (skxgvaBdTdsRurUIZiOBHfjiunfgA(Pole.Positive))
			{
				lOhdpMIGSdyahJLjLKbbeUkHQJxnB2.positiveKey = LocalizationManager.AppendToKeyAxisPole(lOhdpMIGSdyahJLjLKbbeUkHQJxnB2.positiveKey, Pole.Positive);
			}
			lOhdpMIGSdyahJLjLKbbeUkHQJxnB2.autoGeneratedValueFlags |= 8;
			WNOKfMLBcQgmwLBfRHLEkGrCnlHM(8);
		}
		if ((lOhdpMIGSdyahJLjLKbbeUkHQJxnB2.autoGeneratedValueFlags & 0x10) == 0 && string.IsNullOrEmpty(lOhdpMIGSdyahJLjLKbbeUkHQJxnB2.negativeKey) && fVPibPAwXXbhXGcJdASDzpsOjkcS(Pole.Negative))
		{
			lOhdpMIGSdyahJLjLKbbeUkHQJxnB2.negativeKey = lOhdpMIGSdyahJLjLKbbeUkHQJxnB2.key;
			if (skxgvaBdTdsRurUIZiOBHfjiunfgA(Pole.Negative))
			{
				lOhdpMIGSdyahJLjLKbbeUkHQJxnB2.negativeKey = LocalizationManager.AppendToKeyAxisPole(lOhdpMIGSdyahJLjLKbbeUkHQJxnB2.negativeKey, Pole.Negative);
			}
			lOhdpMIGSdyahJLjLKbbeUkHQJxnB2.autoGeneratedValueFlags |= 16;
			WNOKfMLBcQgmwLBfRHLEkGrCnlHM(16);
		}
	}

	protected virtual void OZjiwDPnVDEcSSvzSQhiTvLqthTC(IWFfSiUJvBqDpiIZIfMeuQqJMGul P_0)
	{
		base.EfmhgRjLUYYNAKgnORbsBEMiVRrB(P_0);
		lOhdpMIGSdyahJLjLKbbeUkHQJxnB lOhdpMIGSdyahJLjLKbbeUkHQJxnB2 = aymUlkLwdVCotZlKiVYDmhTNEVBU();
		if (lOhdpMIGSdyahJLjLKbbeUkHQJxnB2 != null && ((uint)lOhdpMIGSdyahJLjLKbbeUkHQJxnB2.autoGeneratedValueFlags & (uint)P_0) != 0)
		{
			if ((P_0 & IWFfSiUJvBqDpiIZIfMeuQqJMGul.PositiveKey) != IWFfSiUJvBqDpiIZIfMeuQqJMGul.None && (lOhdpMIGSdyahJLjLKbbeUkHQJxnB2.autoGeneratedValueFlags & 8) != 0)
			{
				lOhdpMIGSdyahJLjLKbbeUkHQJxnB2.positiveKey = null;
				WNOKfMLBcQgmwLBfRHLEkGrCnlHM(8);
				lOhdpMIGSdyahJLjLKbbeUkHQJxnB2.autoGeneratedValueFlags &= -9;
			}
			if ((P_0 & IWFfSiUJvBqDpiIZIfMeuQqJMGul.NegativeKey) != IWFfSiUJvBqDpiIZIfMeuQqJMGul.None && (lOhdpMIGSdyahJLjLKbbeUkHQJxnB2.autoGeneratedValueFlags & 0x10) != 0)
			{
				lOhdpMIGSdyahJLjLKbbeUkHQJxnB2.negativeKey = null;
				WNOKfMLBcQgmwLBfRHLEkGrCnlHM(16);
				lOhdpMIGSdyahJLjLKbbeUkHQJxnB2.autoGeneratedValueFlags &= -17;
			}
			if ((P_0 & IWFfSiUJvBqDpiIZIfMeuQqJMGul.PositiveDescriptiveName) != IWFfSiUJvBqDpiIZIfMeuQqJMGul.None && (lOhdpMIGSdyahJLjLKbbeUkHQJxnB2.autoGeneratedValueFlags & 2) != 0)
			{
				lOhdpMIGSdyahJLjLKbbeUkHQJxnB2.nonLocalizedPositiveDescriptiveName = null;
				WNOKfMLBcQgmwLBfRHLEkGrCnlHM(2);
				lOhdpMIGSdyahJLjLKbbeUkHQJxnB2.autoGeneratedValueFlags &= -3;
			}
			if ((P_0 & IWFfSiUJvBqDpiIZIfMeuQqJMGul.NegativeDescriptiveName) != IWFfSiUJvBqDpiIZIfMeuQqJMGul.None && (lOhdpMIGSdyahJLjLKbbeUkHQJxnB2.autoGeneratedValueFlags & 4) != 0)
			{
				lOhdpMIGSdyahJLjLKbbeUkHQJxnB2.nonLocalizedNegativeDescriptiveName = null;
				WNOKfMLBcQgmwLBfRHLEkGrCnlHM(4);
				lOhdpMIGSdyahJLjLKbbeUkHQJxnB2.autoGeneratedValueFlags &= -5;
			}
		}
	}

	protected virtual IWFfSiUJvBqDpiIZIfMeuQqJMGul YStzNOSJWfEbbHfXhIXBhTOtyMwrA(cwXjjPkxPWMBcEFwnCUCcKJomfDI P_0)
	{
		IWFfSiUJvBqDpiIZIfMeuQqJMGul iWFfSiUJvBqDpiIZIfMeuQqJMGul = base.MYTaudXHwNmJAoFwqqafrbwMFkCFA(P_0);
		if ((P_0 & cwXjjPkxPWMBcEFwnCUCcKJomfDI.Keys) != cwXjjPkxPWMBcEFwnCUCcKJomfDI.None)
		{
			iWFfSiUJvBqDpiIZIfMeuQqJMGul |= (IWFfSiUJvBqDpiIZIfMeuQqJMGul)24;
		}
		if ((P_0 & cwXjjPkxPWMBcEFwnCUCcKJomfDI.Names) != cwXjjPkxPWMBcEFwnCUCcKJomfDI.None)
		{
			iWFfSiUJvBqDpiIZIfMeuQqJMGul |= (IWFfSiUJvBqDpiIZIfMeuQqJMGul)6;
		}
		return iWFfSiUJvBqDpiIZIfMeuQqJMGul;
	}

	protected lOhdpMIGSdyahJLjLKbbeUkHQJxnB aymUlkLwdVCotZlKiVYDmhTNEVBU()
	{
		return tFHgnqTfapMzUfeUcgrtSgOorhTm() as lOhdpMIGSdyahJLjLKbbeUkHQJxnB;
	}

	protected virtual bool skxgvaBdTdsRurUIZiOBHfjiunfgA(Pole P_0)
	{
		return base.tnQKiUchqifinDnJuSQdboJqaQgK switch
		{
			sztzDKprOgaEtSRoFjITTczsHDuW.Axis => true, 
			sztzDKprOgaEtSRoFjITTczsHDuW.Button => false, 
			_ => false, 
		};
	}

	protected virtual bool fVPibPAwXXbhXGcJdASDzpsOjkcS(Pole P_0)
	{
		return base.tnQKiUchqifinDnJuSQdboJqaQgK switch
		{
			sztzDKprOgaEtSRoFjITTczsHDuW.Axis => true, 
			sztzDKprOgaEtSRoFjITTczsHDuW.Button => P_0 switch
			{
				Pole.Positive => true, 
				Pole.Negative => false, 
				_ => false, 
			}, 
			_ => false, 
		};
	}

	protected virtual void jCxGnYjNnoPKyGKuADugbqhFnNRFb()
	{
		base.eCoUKPYzeytCrbuDxEwhAldiAbYf();
		_ = ypoFNNDaQTVeKqsDkwEcIpgjZwGfA;
		_ = CIYbIIBbIoEXdOMvSfyWNziRLZjc;
	}

	protected virtual void zeBbDTMRdibflgRgLqVpJrThIwMJA()
	{
		KDsUceJlYCDVBhMNBMROGovUueSnA();
		gHHpnMuGywauOByTsYtKEwUhbDMtA(1, new OBzZblFCcoXjpegrNwgWHpLkWsfD
		{
			zYaGNhhcsCIUvDXBxclPthDHCMVvA = 6
		});
		gHHpnMuGywauOByTsYtKEwUhbDMtA(8, new OBzZblFCcoXjpegrNwgWHpLkWsfD(EmWRFnLFeWCswGUFMLlLjSxsndSIA, 2));
		gHHpnMuGywauOByTsYtKEwUhbDMtA(16, new OBzZblFCcoXjpegrNwgWHpLkWsfD(eWcBnrCtmGcAsuKkcBHpeNOiZPLWB, 4));
		gHHpnMuGywauOByTsYtKEwUhbDMtA(2, new OBzZblFCcoXjpegrNwgWHpLkWsfD
		{
			KOtNCnhieDYUVmamgrTOUjanaOIu = EmWRFnLFeWCswGUFMLlLjSxsndSIA
		});
		gHHpnMuGywauOByTsYtKEwUhbDMtA(4, new OBzZblFCcoXjpegrNwgWHpLkWsfD
		{
			KOtNCnhieDYUVmamgrTOUjanaOIu = eWcBnrCtmGcAsuKkcBHpeNOiZPLWB
		});
	}
}
