namespace Features.StreamersSupportModule.Scripts
{
	public enum StreamersStandType
	{
		None = 0,
		DeadPart = 1,
		Mascot = 2,
		Face = 3,
		BoysGaming = 4,
		AndySlapsMascot = 5,
		BiggMaticMascot = 6,
		BigPufferMascot = 7,
		CaRtOoNzMascot = 8,
		CloudMascot = 9,
		DeadSquirrelMascot = 10,
		DefuseDevilMascot = 11,
		ElasticDroidMascot = 12,
		EntoanMascot = 13,
		Fl0mMascot = 14,
		GamejaReviewMascot = 15,
		GodenotMascot = 16,
		H2JDeliriousMascot = 17,
		ImCadeMascot = 18,
		KaifMascot = 19,
		KryozMascot = 20,
		ManguniGamerMascot = 21,
		PaulGGPlaysMascot = 22,
		RetrixxMascot = 23,
		SenpaiSpiderMascot = 24,
		SimMeowTogetherMascot = 25,
		Smii7yMascot = 26,
		SoltekiMascot = 27,
		TamilGamingMascot = 28,
		TheBoysGamingMascot = 29,
		TheLosersMascot = 30,
		Zeus = 31,
		TheSnowyRaven = 32,
		Tabs_a = 33,
		SphinxDSaiyan = 34,
		Sinder = 35,
		RiotEmpress = 36,
		Parkape = 37,
		Kestay = 38,
		ImmaShork = 39,
		SnowDayMedia = 40,
		RiotEmpressCrew = 41,
		ImmaShorkCrew = 42,
		CreatorAlertWinner = 43
	}
}
