using System;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Localization;
using UnityEngine.Localization.Settings;

public class LocalizationKeys
{
	public enum Keys
	{
		HelmetWelcome = 0,
		HelmetFailed = 1,
		Sleep = 2,
		Day = 3,
		Views = 4,
		Quota = 5,
		Money = 6,
		Empty = 7,
		Save = 8,
		DivingBellNotReadyMissingPlayersState = 9,
		DivingBellNotReadyDoorOpenState = 10,
		DivingBellReady = 11,
		DivingBellReadySurface = 12,
		DivingBellRechargingState = 13,
		JoinRandom = 14,
		EnterDiveBellDay2Objective = 15,
		EnterDiveBellObjective = 16,
		BuyEquipmentObjective = 17,
		ExtractVideoObjective = 18,
		FilmSomethingScaryObjective = 19,
		GoToBedFailedObjective = 20,
		GoToBedSuccessObjective = 21,
		InviteFriendsObjective = 22,
		LeaveHouseObjective = 23,
		PickupDiscObjective = 24,
		PickupTheCameraObjective = 25,
		ReturnToTheDiveBellObjective = 26,
		UploadVideoObjective = 27,
		WakeUpObjective = 28,
		CelebrateObjective = 29,
		DaysLeft = 30,
		LastDay = 31,
		Buy = 32,
		Left = 33,
		Right = 34,
		NotSleepy = 35,
		StartGame = 36,
		Submerge = 37,
		ReturnToSurface = 38,
		TerminalBusy = 39,
		Help = 40,
		InviteFriends = 41,
		Open = 42,
		Close = 43,
		GameFull = 44,
		GameStarted = 45,
		Offline = 46,
		StartGameTitle = 47,
		StartGameBody = 48,
		StartGameConfirm = 49,
		Cancel = 50,
		PickUp = 51,
		SwitchCategory = 52,
		AddToCart = 53,
		SoldOut = 54,
		Clear = 55,
		Order = 56,
		DeleteSave = 57,
		DeleteSaveConfirm = 58,
		Yes = 59,
		No = 60,
		Interact = 61,
		HelmetDaysLeft = 62,
		HelmetLastDay = 63,
		HelmetForgetCamera = 64,
		Oxygen = 65,
		Distance = 66,
		Items = 67,
		CloseVideo = 68,
		ReplayVideo = 69,
		SaveVideo = 70,
		UploadToSpookTube = 71,
		ShopClosed = 72,
		Lights = 73,
		Medical = 74,
		Gadgets = 75,
		Emotes = 76,
		Emotes2 = 77,
		Upgrades = 78,
		Misc = 79,
		SpookTubeViews = 80,
		AdRevenue = 81,
		HospitalBill = 82,
		CalibrationUseVoice = 83,
		CalibrationUseHeadphones = 84,
		CalibrationSelectMic = 85,
		CalibrationSelectVoice = 86,
		CalibrationBrightness = 87,
		CalibrationMonster = 88,
		Brightness = 89,
		Continue = 90,
		OldVersion = 91,
		PleaseUpdate = 92,
		CloseGame = 93,
		CrouchKeybindSetting = 94,
		DropKeybindSetting = 95,
		EmoteKeybindSetting = 96,
		InteractKeybindSetting = 97,
		JumpKeybindSetting = 98,
		ToggleSelfieModeKeybindSetting = 99,
		WalkBackwardKeybindSetting = 100,
		WalkForwardKeybindSetting = 101,
		WalkLeftKeybindSetting = 102,
		WalkRightKeybindSetting = 103,
		AmbientOcclusionSetting = 104,
		BrightnessSetting = 105,
		ChromaticAberrationSetting = 106,
		FullscreenSetting = 107,
		VoiceVolumeSetting = 108,
		VoiceSetting = 109,
		VoiceChatModeSetting = 110,
		VSyncSetting = 111,
		ShadowQualitySetting = 112,
		ScreenResolutionSetting = 113,
		SFXVolumeSetting = 114,
		MouseSensitivitySetting = 115,
		MaxFramerateSetting = 116,
		MasterVolumeSetting = 117,
		SprintKeybindSetting = 118,
		JoinError = 119,
		JoinErrorMismatch = 120,
		Ok = 121,
		VideoSaved = 122,
		VideoSavedAs = 123,
		VideoFailedSave = 124,
		ServerIssues = 125,
		DropItem = 126,
		Battery = 127,
		FilmLeft = 128,
		ToggleLight = 129,
		ZoomKey = 130,
		SelfieMode = 131,
		Aim = 132,
		HostingGame = 133,
		Connecting = 134,
		BoomMic = 135,
		Camera = 136,
		CameraBroken = 137,
		Clapper = 138,
		Defibrilator = 139,
		Disc = 140,
		Flare = 141,
		GooBall = 142,
		Hugger = 143,
		LongFlashlightPro = 144,
		LongFlashlight = 145,
		ModernFlashlightPro = 146,
		ModernFlashlight = 147,
		OldFlashlight = 148,
		PartyPopper = 149,
		ShockStick = 150,
		SoundPlayer = 151,
		WalkieTalkie = 152,
		WideFlashlight2 = 153,
		WideFlashlight3 = 154,
		Winch = 155,
		Aminalstateu = 156,
		Animalstatue = 157,
		Bone = 158,
		Brainonastick = 159,
		Chorby = 160,
		Container = 161,
		OldPainting = 162,
		Radio = 163,
		Ribcage = 164,
		Skull = 165,
		Spine = 166,
		ReporterMic = 167,
		RescueHook = 168,
		Emote_Applause = 169,
		Emote_Dance1 = 170,
		Emote_Dance2 = 171,
		Emote_Dance3 = 172,
		Emote_FingerScratch = 173,
		Emote_HalfBackflip = 174,
		Emote_Handstand = 175,
		Emote_HuggerHeal = 176,
		Emote_JumpJack = 177,
		Emote_MiddleFings = 178,
		Emote_Peace = 179,
		Emote_PushUp = 180,
		Emote_Shrug = 181,
		Emote_Stretch = 182,
		Emote_Thumbnail1 = 183,
		Emote_Thumbnail2 = 184,
		Emote_ThumbsUp = 185,
		BoomMic_ToolTips = 186,
		Camera_ToolTips = 187,
		Clapper_ToolTips = 188,
		Defibrilator_ToolTips = 189,
		Disc_ToolTips = 190,
		FakeOldFlashlight = 191,
		FakeOldFlashlight_ToolTips = 192,
		Flare_ToolTips = 193,
		GooBall_ToolTips = 194,
		GrabberArm = 195,
		GrabberArm_ToolTips = 196,
		Hugger_ToolTips = 197,
		LongFlashlightPro_ToolTips = 198,
		LongFlashlight_ToolTips = 199,
		LostDisc = 200,
		LostDisc_ToolTips = 201,
		ModernFlashlightPro_ToolTips = 202,
		ModernFlashlight_ToolTips = 203,
		OldFlashlight_ToolTips = 204,
		PartyPopper_ToolTips = 205,
		ReporterMic_ToolTips = 206,
		ShockStick_ToolTips = 207,
		SoundPlayer_ToolTips = 208,
		WalkieTalkie_ToolTips = 209,
		WideFlashlight2_ToolTips = 210,
		WideFlashlight3_ToolTips = 211,
		Radio_ToolTips = 212,
		Emote_Applause_ToolTips = 213,
		Emote_Dance1_ToolTips = 214,
		Emote_Dance2_ToolTips = 215,
		Emote_Dance3_ToolTips = 216,
		Emote_FingerScratch_ToolTips = 217,
		Emote_HalfBackflip_ToolTips = 218,
		Emote_Handstand_ToolTips = 219,
		Emote_HuggerHeal_ToolTips = 220,
		Emote_JumpJack_ToolTips = 221,
		Emote_MiddleFings_ToolTips = 222,
		Emote_Peace_ToolTips = 223,
		Emote_PushUp_ToolTips = 224,
		Emote_Shrug_ToolTips = 225,
		Emote_Stretch_ToolTips = 226,
		Emote_Thumbnail1_ToolTips = 227,
		Emote_Thumbnail2_ToolTips = 228,
		Emote_ThumbsUp_ToolTips = 229,
		ThrowItemToolTip = 230,
		Endscreen1_1 = 231,
		Endscreen1_2 = 232,
		Endscreen1_3 = 233,
		Endscreen1_4 = 234,
		Endscreen1_5 = 235,
		Endscreen2_1 = 236,
		Endscreen2_2 = 237,
		Endscreen2_3 = 238,
		Endscreen2_4 = 239,
		Endscreen2_5 = 240,
		Endscreen3_1 = 241,
		Endscreen3_2 = 242,
		Endscreen3_3 = 243,
		Endscreen3_4 = 244,
		Endscreen3_5 = 245,
		Endscreen3_6 = 246,
		EndscreenDream = 247,
		Bomb = 248,
		Apple = 249,
		Sit = 250,
		Error_Steam_Title = 251,
		Error_Steam_Body = 252,
		Error_Auth_Failed = 253,
		Error_File_Not_Found = 254,
		Error_Save = 255,
		Error_RecordingsFolder = 256,
		Error_NoSave = 257,
		Error_HostLeft = 258,
		Error_Disconnected = 259,
		Error_Join = 260,
		Error_Delete_TempFolder = 261,
		Error_CreateRoom = 262,
		Error_VideoPath = 263,
		Error_MissingAvxSupport = 264,
		AddedToCart = 265,
		PushToTalk = 266,
		VoiceDetection = 267,
		FullScreenMode = 268,
		WindowedMode = 269,
		HighSetting = 270,
		MediumSettings = 271,
		LowSetting = 272,
		OnSetting = 273,
		OffSetting = 274,
		PressAnyKeySetting = 275,
		Emote_Applause_Text = 276,
		Emote_Dance1_Text = 277,
		Emote_Dance2_Text = 278,
		Emote_Dance3_Text = 279,
		Emote_FingerScratch_Text = 280,
		Emote_HalfBackflip_Text = 281,
		Emote_Handstand_Text = 282,
		Emote_HuggerHeal_Text = 283,
		Emote_JumpJack_Text = 284,
		Emote_MiddleFings_Text = 285,
		Emote_Peace_Text = 286,
		Emote_PushUp_Text = 287,
		Emote_Shrug_Text = 288,
		Emote_Stretch_Text = 289,
		Emote_Thumbnail1_Text = 290,
		Emote_Thumbnail2_Text = 291,
		Emote_ThumbsUp_Text = 292,
		Unlock = 293,
		BalaclavaHat = 294,
		BeanieHat = 295,
		BucketHatHat = 296,
		CatEarsHat = 297,
		ChefHat = 298,
		FloppyHat = 299,
		HomburgHat = 300,
		Hair1Hat = 301,
		Hat_BowlerHat = 302,
		Hat_CapHat = 303,
		Hat_ChildHat = 304,
		Hat_ClownHat = 305,
		Hat_CowboyHat = 306,
		Hat_CrownHat = 307,
		Hat_HaloHat = 308,
		Hat_HornsHat = 309,
		Hat_HotdogHat = 310,
		Hat_JesterHat = 311,
		Hat_KnifoHat = 312,
		Hat_MilkHat = 313,
		Hat_NewsHat = 314,
		Hat_PirateHat = 315,
		Hat_RugbyHat = 316,
		Hat_SavannahHat = 317,
		Hat_TooopHat = 318,
		Hat_TopHat = 319,
		PartyHat = 320,
		ShroomHat = 321,
		UshankaHat = 322,
		WitchHat = 323,
		NetworkBingoBongo_0_EmailTitle = 324,
		NetworkBingoBongo_0_DealName = 325,
		NetworkBingoBongo_0_Description = 326,
		NetworkBingoBongo_0_SuccessEmailBody = 327,
		NetworkBingoBongo_0_FailedEmailBody = 328,
		NetworkHoldTheBombo_9_EmailTitle = 329,
		NetworkHoldTheBombo_9_DealName = 330,
		NetworkHoldTheBombo_9_Description = 331,
		NetworkHoldTheBombo_9_SuccessEmailBody = 332,
		NetworkHoldTheBombo_9_FailedEmailBody = 333,
		NetworkInterviewer_2_EmailTitle = 334,
		NetworkInterviewer_2_DealName = 335,
		NetworkInterviewer_2_Description = 336,
		NetworkInterviewer_2_SuccessEmailBody = 337,
		NetworkInterviewer_2_FailedEmailBody = 338,
		NetworkJackass_4_EmailTitle = 339,
		NetworkJackass_4_DealName = 340,
		NetworkJackass_4_Description = 341,
		NetworkJackass_4_SuccessEmailBody = 342,
		NetworkJackass_4_FailedEmailBody = 343,
		NetworkMultiMonsterInFrameAtOnce_5_EmailTitle = 344,
		NetworkMultiMonsterInFrameAtOnce_5_DealName = 345,
		NetworkMultiMonsterInFrameAtOnce_5_Description = 346,
		NetworkMultiMonsterInFrameAtOnce_5_SuccessEmailBody = 347,
		NetworkMultiMonsterInFrameAtOnce_5_FailedEmailBody = 348,
		NetworkTaunting_3_EmailTitle = 349,
		NetworkTaunting_3_DealName = 350,
		NetworkTaunting_3_Description = 351,
		NetworkTaunting_3_SuccessEmailBody = 352,
		NetworkTaunting_3_FailedEmailBody = 353,
		NetworkWalletMoney_1_EmailTitle = 354,
		NetworkWalletMoney_1_DealName = 355,
		NetworkWalletMoney_1_Description = 356,
		NetworkWalletMoney_1_SuccessEmailBody = 357,
		NetworkWalletMoney_1_FailedEmailBody = 358,
		NoHat = 359,
		HatShop_AlreadyOwn = 360,
		HatShop_Buy = 361,
		HatShop_CantAfford = 362,
		Difficulty_VeryEasy = 363,
		Difficulty_Easy = 364,
		Difficulty_Medium = 365,
		Difficulty_Hard = 366,
		Difficulty_VeryHard = 367,
		Deal_Reward_Items = 368,
		Deal_Reward_Meta = 369,
		Deal_SignDeal = 370,
		ControllerSensitivitySetting = 371,
		PushToTalkButtonSetting = 372,
		InvertedMouseSetting = 373,
		SelectItem1KeybindSetting = 374,
		SelectItem2KeybindSetting = 375,
		SelectItem3KeybindSetting = 376,
		PreferredLanguageMatchmakingSetting = 377,
		SecondLanguageMatchmakingSetting = 378,
		ThirdLanguageMatchmakingSetting = 379,
		TypeAFace = 380,
		Retry = 381,
		DialogueFailed = 382,
		EnterRoomCode = 383,
		InvalidRoomCode = 384,
		InvalidRoomCodeHint = 385,
		PlayOffline = 386,
		PlayOfflineHint = 387,
		Shroom = 388,
		SketchPad = 389,
		SketchPad_ToolTips = 390,
		RescueHook_ToolTips = 391,
		PersistantRadio_ToolTips = 392,
		NorfGun_ToolTips = 393,
		Emote_Dance4TokTok = 394,
		PersistantRadio = 395,
		SirMonsterBurger = 396,
		FredGull = 397,
		NorfGun = 398,
		HermansBag = 399,
		PlayerCell_MuteButton_Mute = 400,
		PlayerCell_MuteButton_Unmute = 401,
		PlayerCell_BlockButton_Block = 402,
		PlayerCell_BlockButton_Unblock = 403,
		PlayerCell_ReportButton = 404,
		Modal_AreYouSure = 405,
		Modal_KickPlayer = 406,
		Modal_Block = 407,
		Modal_Unblock = 408,
		Modal_Kicked_Title = 409,
		Modal_Kicked_Body = 410,
		Modal_MatchError_Title = 411,
		Modal_MatchError_Body = 412,
		Modal_CorruptSave_Title = 413,
		Modal_CorruptSave_Body = 414,
		Modal_BadSave_Title = 415,
		Modal_BadSave_Body = 416,
		Disabled = 417,
		ToggleToTalk = 418,
		Quit = 419,
		CrossPlatformSetting = 420,
		LanguageSetting = 421,
		Language_English = 422,
		Language_French = 423,
		Language_Italian = 424,
		Language_German = 425,
		Language_Spanish = 426,
		Language_Japanese = 427,
		Language_ChineseSimplified = 428,
		Language_ChineseTraditional = 429,
		Language_Portuguese = 430,
		Language_Russian = 431,
		Language_Ukrainian = 432,
		Language_Korean = 433,
		Language_Swedish = 434,
		Hat_HardHat = 435,
		Modal_ModWarning_Body = 436,
		Modal_ModError_Body = 437,
		Modal_Continue = 438,
		Modal_Warning = 439,
		Modal_Lacking_AVX = 440,
		MM_None = 441,
		MM_ArabicAlgerian = 442,
		MM_ArabicEgyptian = 443,
		MM_Belarusian = 444,
		MM_Bengali = 445,
		MM_Croatian = 446,
		MM_Czech = 447,
		MM_Danish = 448,
		MM_Dutch = 449,
		MM_English = 450,
		MM_Farsi = 451,
		MM_Finnish = 452,
		MM_French = 453,
		MM_German = 454,
		MM_Greek = 455,
		MM_Gujarati = 456,
		MM_Hindi = 457,
		MM_Hungarian = 458,
		MM_Italian = 459,
		MM_Japanese = 460,
		MM_Korean = 461,
		MM_Malayalam = 462,
		MM_Mandarin = 463,
		MM_Marathi = 464,
		MM_Norwegian = 465,
		MM_Oriya = 466,
		MM_Panjabi = 467,
		MM_Polish = 468,
		MM_Portuguese = 469,
		MM_Russian = 470,
		MM_Spanish = 471,
		MM_Sunda = 472,
		MM_Swedish = 473,
		MM_Tamil = 474,
		MM_Telugu = 475,
		MM_Turkish = 476,
		MM_Ukrainian = 477,
		MM_Urdu = 478,
		MM_Vietnamese = 479,
		InvertedVerticalView = 480,
		InvertedHorizontalView = 481,
		HoldSelfieMode = 482
	}

	private static Dictionary<Keys, string> m_StringDictionary;

	private static Dictionary<Locale, Dictionary<Keys, string>> m_LanguageStrings;

	private static bool m_MadeLocaleStrings;

	public static event Action OnLanguageChanged;

	public static string GetLocalizedString(Keys key)
	{
		if (!m_MadeLocaleStrings)
		{
			MakeLocaleStrings();
		}
		if (m_StringDictionary == null || !m_StringDictionary.ContainsKey(key))
		{
			Debug.LogError("Cant find locale key for: " + key);
			return "LOCALIZATION ERROR";
		}
		return m_StringDictionary[key];
	}

	public static string GetLocalizedString(Locale locale, Keys key)
	{
		if (!m_MadeLocaleStrings)
		{
			MakeLocaleStrings();
		}
		if (m_LanguageStrings.TryGetValue(locale, out var value) && value.TryGetValue(key, out var value2))
		{
			return value2;
		}
		return GetLocalizedInternal(locale, key);
	}

	private static string GetLocalizedInternal(Locale locale, Keys key)
	{
		string text = LocalizationSettings.StringDatabase.GetLocalizedString(key.ToString(), locale, FallbackBehavior.UseProjectSettings);
		if (string.IsNullOrEmpty(text))
		{
			text = LocalizationSettings.StringDatabase.GetLocalizedString(key.ToString(), LocalizationSettings.ProjectLocale, FallbackBehavior.UseProjectSettings);
			if (string.IsNullOrEmpty(text))
			{
				text = "LOCALIZATION ERROR";
			}
		}
		return text;
	}

	public static void MakeLocaleStrings()
	{
		if (m_MadeLocaleStrings)
		{
			VerboseDebug.Log("Dont Redo Language Strings!");
			return;
		}
		m_LanguageStrings = new Dictionary<Locale, Dictionary<Keys, string>>();
		Keys[] array = (Keys[])Enum.GetValues(typeof(Keys));
		int num = array.Length;
		foreach (Locale locale in LocalizationSettings.AvailableLocales.Locales)
		{
			Dictionary<Keys, string> dictionary = new Dictionary<Keys, string>();
			for (int i = 0; i < num; i++)
			{
				Keys key = array[i];
				string localizedInternal = GetLocalizedInternal(locale, key);
				dictionary.Add(key, localizedInternal);
			}
			m_LanguageStrings.Add(locale, dictionary);
		}
		m_MadeLocaleStrings = true;
		OnLanguageSwitch();
	}

	public static void OnLanguageSwitch()
	{
		if (m_MadeLocaleStrings)
		{
			m_StringDictionary = m_LanguageStrings[LocalizationSettings.SelectedLocale];
		}
		LocalizationKeys.OnLanguageChanged?.Invoke();
	}
}
