<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Assembly-CSharp</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="PhotonUnityNetworking">
      <HintPath>..\..\Assemblies\PhotonUnityNetworking.dll</HintPath>
    </Reference>
    <Reference Include="Zorro.Core.Runtime">
      <HintPath>..\..\Assemblies\Zorro.Core.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="Zorro.Recorder">
      <HintPath>..\..\Assemblies\Zorro.Recorder.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>..\..\Assemblies\UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="Photon3Unity3D">
      <HintPath>..\..\Assemblies\Photon3Unity3D.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIElementsModule">
      <HintPath>..\..\Assemblies\UnityEngine.UIElementsModule.dll</HintPath>
    </Reference>
    <Reference Include="PhotonRealtime">
      <HintPath>..\..\Assemblies\PhotonRealtime.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AnimationModule">
      <HintPath>..\..\Assemblies\UnityEngine.AnimationModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>..\..\Assemblies\Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TerrainModule">
      <HintPath>..\..\Assemblies\UnityEngine.TerrainModule.dll</HintPath>
    </Reference>
    <Reference Include="Zorro.ControllerSupport">
      <HintPath>..\..\Assemblies\Zorro.ControllerSupport.dll</HintPath>
    </Reference>
    <Reference Include="Zorro.Settings.Runtime">
      <HintPath>..\..\Assemblies\Zorro.Settings.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Localization">
      <HintPath>..\..\Assemblies\Unity.Localization.dll</HintPath>
    </Reference>
    <Reference Include="com.rlabrecque.steamworks.net">
      <HintPath>..\..\Assemblies\com.rlabrecque.steamworks.net.dll</HintPath>
    </Reference>
    <Reference Include="Zorro.UI.Runtime">
      <HintPath>..\..\Assemblies\Zorro.UI.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Unity.RenderPipelines.Core.Runtime">
      <HintPath>..\..\Assemblies\Unity.RenderPipelines.Core.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Mathematics">
      <HintPath>..\..\Assemblies\Unity.Mathematics.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>..\..\Assemblies\UnityEngine.AudioModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.RenderPipelines.Universal.Runtime">
      <HintPath>..\..\Assemblies\Unity.RenderPipelines.Universal.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Unity.InputSystem">
      <HintPath>..\..\Assemblies\Unity.InputSystem.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>..\..\Assemblies\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="Platforms">
      <HintPath>..\..\Assemblies\Platforms.dll</HintPath>
    </Reference>
    <Reference Include="Unity.ResourceManager">
      <HintPath>..\..\Assemblies\Unity.ResourceManager.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ParticleSystemModule">
      <HintPath>..\..\Assemblies\UnityEngine.ParticleSystemModule.dll</HintPath>
    </Reference>
    <Reference Include="PhotonVoice.API">
      <HintPath>..\..\Assemblies\PhotonVoice.API.dll</HintPath>
    </Reference>
    <Reference Include="PhotonChat">
      <HintPath>..\..\Assemblies\PhotonChat.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>..\..\Assemblies\UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>..\..\Assemblies\UnityEngine.UIModule.dll</HintPath>
    </Reference>
    <Reference Include="Discord">
      <HintPath>..\..\Assemblies\Discord.dll</HintPath>
    </Reference>
    <Reference Include="PhotonVoice">
      <HintPath>..\..\Assemblies\PhotonVoice.dll</HintPath>
    </Reference>
    <Reference Include="Zorro.PhotonUtility">
      <HintPath>..\..\Assemblies\Zorro.PhotonUtility.dll</HintPath>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>..\..\Assemblies\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="HBAO.Universal.Runtime">
      <HintPath>..\..\Assemblies\HBAO.Universal.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="sc.posteffects.runtime">
      <HintPath>..\..\Assemblies\sc.posteffects.runtime.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.VideoModule">
      <HintPath>..\..\Assemblies\UnityEngine.VideoModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Splines">
      <HintPath>..\..\Assemblies\Unity.Splines.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AIModule">
      <HintPath>..\..\Assemblies\UnityEngine.AIModule.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath>..\..\Assemblies\Assembly-CSharp-firstpass.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Animation.Rigging">
      <HintPath>..\..\Assemblies\Unity.Animation.Rigging.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestModule">
      <HintPath>..\..\Assemblies\UnityEngine.UnityWebRequestModule.dll</HintPath>
    </Reference>
    <Reference Include="Sirenix.Serialization">
      <HintPath>..\..\Assemblies\Sirenix.Serialization.dll</HintPath>
    </Reference>
    <Reference Include="Managers">
      <HintPath>..\..\Assemblies\Managers.dll</HintPath>
    </Reference>
    <Reference Include="pworld">
      <HintPath>..\..\Assemblies\pworld.dll</HintPath>
    </Reference>
    <Reference Include="VerboseAssembly">
      <HintPath>..\..\Assemblies\VerboseAssembly.dll</HintPath>
    </Reference>
    <Reference Include="LocalizationAssembly">
      <HintPath>..\..\Assemblies\LocalizationAssembly.dll</HintPath>
    </Reference>
    <Reference Include="ModalAssembly">
      <HintPath>..\..\Assemblies\ModalAssembly.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>..\..\Assemblies\UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
    <Reference Include="Sirenix.Utilities">
      <HintPath>..\..\Assemblies\Sirenix.Utilities.dll</HintPath>
    </Reference>
    <Reference Include="Photon">
      <HintPath>..\..\Assemblies\Photon.dll</HintPath>
    </Reference>
    <Reference Include="PhotonVoice.PUN">
      <HintPath>..\..\Assemblies\PhotonVoice.PUN.dll</HintPath>
    </Reference>
    <Reference Include="SteamCommon">
      <HintPath>..\..\Assemblies\SteamCommon.dll</HintPath>
    </Reference>
    <Reference Include="SteamManagerAssembly">
      <HintPath>..\..\Assemblies\SteamManagerAssembly.dll</HintPath>
    </Reference>
    <Reference Include="PlayEveryWare.VideoEncoding">
      <HintPath>..\..\Assemblies\PlayEveryWare.VideoEncoding.dll</HintPath>
    </Reference>
    <Reference Include="Utilities">
      <HintPath>..\..\Assemblies\Utilities.dll</HintPath>
    </Reference>
    <Reference Include="Mono.Cecil">
      <HintPath>..\..\Assemblies\Mono.Cecil.dll</HintPath>
    </Reference>
    <Reference Include="websocket-sharp">
      <HintPath>..\..\Assemblies\websocket-sharp.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>..\..\Assemblies\UnityEngine.IMGUIModule.dll</HintPath>
    </Reference>
    <Reference Include="PhotonUnityNetworking.Utilities">
      <HintPath>..\..\Assemblies\PhotonUnityNetworking.Utilities.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>