using System;
using System.Collections;
using System.Collections.Generic;
using NWH.Common.Utility;
using NWH.Common.Vehicles;
using UnityEngine;
using UnityEngine.Events;

namespace NWH.VehiclePhysics2.Powertrain
{
	[Serializable]
	public class EngineComponent : PowertrainComponent
	{
		[Serializable]
		public class ForcedInduction
		{
			public enum ForcedInductionType
			{
				Turbocharger = 0,
				Supercharger = 1
			}

			[ShowInTelemetry]
			[Tooltip("    Should forced induction be used?")]
			[ShowInSettings("Enabled")]
			public bool useForcedInduction = true;

			[Range(0f, 1f)]
			[ShowInTelemetry]
			[Tooltip("    Boost value as percentage in 0 to 1 range. Unitless.\r\n    Can be used for boost gauges.")]
			public float boost;

			[Tooltip("    Type of forced induction.")]
			public ForcedInductionType forcedInductionType;

			[Tooltip("Imitates wastegate in a turbo setup.\r\nEnable if you want turbo flutter sound effects and/or boost to drop off faster after closing throttle.\r\nNot used with superchargers.")]
			[ShowInSettings("Has Wastegate")]
			public bool hasWastegate = true;

			[Range(1f, 3f)]
			[Tooltip("Additional power that will be added to the engine's power.\r\nThis is the maximum value possible and depends on spool percent.")]
			[ShowInSettings("Power Gain Mp.", 1f, 2f, 0.1f)]
			public float powerGainMultiplier = 1.4f;

			[Range(0.1f, 4f)]
			[Tooltip("Shortest time possible needed for turbo to spool up to its maximum RPM.\r\nUse larger values for larger turbos and vice versa.\r\nForced to 0 for superchargers.")]
			[ShowInSettings("Spool Up Time", 0f, 2f, 0.05f)]
			public float spoolUpTime = 0.3f;

			[Tooltip("    Flag for sound effects.")]
			public UnityEvent<float> onWastegateRelease = new UnityEvent<float>();

			private float _boostVelocity;

			public float PowerGainMultiplier
			{
				get
				{
					if (!useForcedInduction)
					{
						return 1f;
					}
					return Mathf.Lerp(1f, powerGainMultiplier, boost);
				}
			}

			public void Update(EngineComponent engine)
			{
				if (!useForcedInduction)
				{
					return;
				}
				if (forcedInductionType == ForcedInductionType.Supercharger)
				{
					boost = Mathf.Clamp01(engine.RPMPercent * 2f);
					return;
				}
				float num = ((!engine.vehicleController.powertrain.transmission.isShifting) ? (Mathf.Clamp01(engine.RPMPercent * 2f) * engine.ThrottlePosition) : 0f);
				boost = Mathf.SmoothDamp(boost, num, ref _boostVelocity, spoolUpTime);
				boost = Mathf.Clamp01(boost);
				if (hasWastegate && num < 0.3f && boost > 0.7f)
				{
					onWastegateRelease.Invoke(boost);
					boost = 0f;
				}
			}
		}

		public delegate float CalculateTorque(float angularVelocity, float dt);

		public delegate float PowerModifier();

		public delegate bool CanRunModifier();

		public enum EngineType
		{
			ICE = 0,
			Electric = 1
		}

		[Tooltip("    If true starter will be ran for [starterRunTime] seconds if engine receives any throttle input.")]
		public bool autoStartOnThrottle = true;

		[Tooltip("    Assign your own delegate to use different type of torque calculation.")]
		public CalculateTorque calculateTorqueDelegate;

		[Tooltip("Engine type. ICE (Internal Combustion Engine) supports features such as starter, stalling, etc.\r\nElectric engine (motor) can run in reverse, can not be stalled and does not use starter.")]
		[ShowInTelemetry]
		[ShowInSettings]
		public EngineType engineType;

		[Tooltip("    Turbocharger or supercharger.")]
		public ForcedInduction forcedInduction = new ForcedInduction();

		[NonSerialized]
		[Tooltip("    Power generated by the engine in kW")]
		[ShowInTelemetry]
		public float generatedPower;

		[SerializeField]
		[Tooltip("    RPM at which idler circuit will try to keep RPMs when there is no input.")]
		public float idleRPM = 900f;

		[SerializeField]
		[Tooltip("RPM at which the engine will stall. Set to 0 to disable stalling.")]
		public float stallRPM = 400f;

		[Tooltip("    Maximum engine power in [kW].")]
		[ShowInSettings("Max. Power", 20f, 400f, 10f)]
		public float maxPower = 120f;

		[Range(0f, 1f)]
		public float engineLossPercent = 0.25f;

		[Tooltip("    Called when engine hits rev limiter.")]
		public UnityEvent onRevLimiter = new UnityEvent();

		[Tooltip("    Called when engine is started.")]
		public UnityEvent onStart = new UnityEvent();

		[Tooltip("    Called when engine is stopped.")]
		public UnityEvent onStop = new UnityEvent();

		[Tooltip("If true the engine will be started immediately, without running the starter, when the vehicle is enabled.\r\nSets engine angular velocity to idle angular velocity.")]
		public bool flyingStartEnabled;

		public bool ignition = true;

		[Tooltip("Power curve with RPM range [0,1] on the X axis and power coefficient [0,1] on Y axis.\r\nBoth values are represented as percentages and should be in 0 to 1 range.\r\nPower coefficient is multiplied by maxPower to get the final power at given RPM.")]
		public AnimationCurve powerCurve;

		[NonSerialized]
		[Tooltip("List of callbacks that influence engine power. Examples would be traction control which\r\nreduces power (returns less than 1) or forced induction which increases power (returns more than 1).\r\nCan also be used by modules to reduce engine power in certain situations.\r\nFinal power modifier value is calculated by multiplying return values of all callbacks.")]
		public List<PowerModifier> powerModifiers = new List<PowerModifier>();

		[NonSerialized]
		public List<CanRunModifier> runModifiers = new List<CanRunModifier>();

		[NonSerialized]
		[Tooltip("    Is the engine currently hitting the rev limiter?")]
		public bool revLimiterActive;

		[Tooltip("If engine RPM rises above revLimiterRPM, how long should fuel cutoff last?\r\nHigher values make hitting rev limiter more rough and choppy.")]
		public float revLimiterCutoffDuration;

		[Tooltip("    Engine RPM at which rev limiter activates.")]
		public float revLimiterRPM = 4700f;

		[NonSerialized]
		[Tooltip("    Is the starter currently active?")]
		[ShowInTelemetry]
		public bool starterActive;

		[Tooltip("Torque starter motor can put out. Make sure that this torque is more than loss torque\r\nat the starter RPM limit. If too low the engine will fail to start.")]
		public float startDuration = 0.5f;

		private float _starterTorque;

		private float _idleAngularVelocity;

		private float _stallAngularVelocity;

		private float _revLimiterAngularVelocity;

		private float _powerModifierSum;

		private Coroutine _starterCoroutine;

		private float _userThrottleInput;

		private float _prevAngularVelocity;

		private float _prevDamage;

		private bool _wasRunning;

		private float _peakPower;

		private float _peakPowerRpm;

		private float _peakTorque;

		private float _peakTorqueRpm;

		private float _rpmPercent;

		private float _throttlePosition;

		private bool _isRunning;

		private float _load;

		public float EstimatedPeakPower => _peakPower;

		public float EstimatedPeakPowerRPM => _peakPowerRpm;

		public float EstimatedPeakTorque => _peakTorque;

		public float EstimatedPeakTorqueRPM => _peakTorqueRpm;

		public float RPMPercent => _rpmPercent;

		[ShowInTelemetry]
		public float ThrottlePosition => _throttlePosition;

		public bool IsRunning => _isRunning;

		public bool IsStalled
		{
			get
			{
				if (engineType == EngineType.ICE)
				{
					return Mathf.Abs(outputAngularVelocity) < _stallAngularVelocity;
				}
				return false;
			}
		}

		public float Load => _load;

		protected override void VC_Initialize()
		{
			UpdatePeakPowerAndTorque();
			_wasRunning = false;
			_isRunning = false;
			if (engineType == EngineType.ICE)
			{
				calculateTorqueDelegate = CalculateTorqueICE;
			}
			else if (engineType == EngineType.Electric)
			{
				forcedInduction.useForcedInduction = false;
				_stallAngularVelocity = 0f;
				idleRPM = 0f;
				flyingStartEnabled = true;
				calculateTorqueDelegate = CalculateTorqueElectric;
				starterActive = false;
				startDuration = 0.001f;
				revLimiterCutoffDuration = 0f;
			}
			base.VC_Initialize();
		}

		public override bool VC_Enable(bool calledByParent)
		{
			if (base.VC_Enable(calledByParent))
			{
				if (flyingStartEnabled)
				{
					StartEngine();
				}
				return true;
			}
			return false;
		}

		public override bool VC_Disable(bool calledByParent)
		{
			if (base.VC_Disable(calledByParent))
			{
				StopEngine();
				return true;
			}
			return false;
		}

		public override void VC_Validate(VehicleController vc)
		{
			base.VC_Validate(vc);
			if (engineType != EngineType.Electric && (powerCurve == null || powerCurve.keys.Length < 2))
			{
				PC_LogWarning(vc, "Power curve of the engine is not set.");
			}
		}

		public override void VC_SetDefaults()
		{
			base.VC_SetDefaults();
			inertia = 0.25f;
			forcedInduction = new ForcedInduction();
			powerCurve = new AnimationCurve
			{
				keys = new Keyframe[2]
				{
					new Keyframe(0f, 0f, 0f, 1f),
					new Keyframe(1f, 1f)
				}
			};
			UpdatePeakPowerAndTorque();
			base.Output = vehicleController.powertrain.clutch;
		}

		public void UpdatePeakPowerAndTorque()
		{
			GetPeakPower(out _peakPower, out _peakPowerRpm);
			GetPeakTorque(out _peakTorque, out _peakTorqueRpm);
		}

		public void StartStopEngine()
		{
			if (IsRunning)
			{
				StopEngine();
			}
			else
			{
				StartEngine();
			}
		}

		public float CalculateTorqueElectric(float angularVelocity, float dt)
		{
			float num = Mathf.Abs(angularVelocity);
			if (vehicleController.powertrain.transmission.isShifting)
			{
				_throttlePosition = 0f;
			}
			float num2 = maxPower * 0.3f * (1f - _throttlePosition) * RPMPercent;
			float num3 = (ignition ? (maxPower * _throttlePosition * _powerModifierSum) : 0f) - num2;
			num3 = Mathf.Lerp(num3 * 0.1f, num3, RPMPercent * 10f);
			return PowertrainComponent.PowerInKWToTorque((num < 10f) ? 10f : num, in num3);
		}

		public float CalculateTorqueICE(float angularVelocity, float dt)
		{
			if (vehicleController.powertrain.transmission.isShifting && angularVelocity > _idleAngularVelocity)
			{
				_throttlePosition = 0f;
			}
			if (starterActive)
			{
				_throttlePosition = 0f;
			}
			else
			{
				ApplyICEIdleCorrection();
			}
			if (angularVelocity >= _revLimiterAngularVelocity && !revLimiterActive)
			{
				vehicleController.StartCoroutine(RevLimiterCoroutine());
			}
			float num = ((!starterActive && !IsStalled) ? CalculateICEGeneratedTorqueFromPowerCurve() : 0f);
			float num2 = (starterActive ? 0f : CalculateICELossTorqueFromPowerCurve());
			if (revLimiterActive)
			{
				num2 *= 0.25f;
			}
			return num + (_starterTorque + num2);
		}

		private float CalculateICELossTorqueFromPowerCurve()
		{
			if (outputAngularVelocity < 10f)
			{
				return (0f - outputAngularVelocity) * maxPower * 0.03f;
			}
			float time = ((outputAngularVelocity < 10f) ? 0.1f : (Mathf.Clamp(outputAngularVelocity, _stallAngularVelocity, _revLimiterAngularVelocity) / _revLimiterAngularVelocity));
			float powerInKW = powerCurve.Evaluate(time) * (0f - maxPower) * Mathf.Clamp01(_userThrottleInput + 0.5f) * engineLossPercent;
			return PowertrainComponent.PowerInKWToTorque(in outputAngularVelocity, in powerInKW);
		}

		private float CalculateICEGeneratedTorqueFromPowerCurve()
		{
			generatedPower = 0f;
			float result = 0f;
			if (!ignition && !starterActive)
			{
				return 0f;
			}
			if (revLimiterActive)
			{
				_throttlePosition = 0.2f;
			}
			else
			{
				generatedPower = powerCurve.Evaluate(_rpmPercent) * (maxPower * (1f + engineLossPercent)) * _throttlePosition * _powerModifierSum * forcedInduction.PowerGainMultiplier;
				result = PowertrainComponent.PowerInKWToTorque(in outputAngularVelocity, in generatedPower);
			}
			return result;
		}

		private void ApplyICEIdleCorrection()
		{
			if (ignition && outputAngularVelocity < _idleAngularVelocity * 1.1f)
			{
				float num = _idleAngularVelocity * 1.08f - outputAngularVelocity;
				num = ((num < 0f) ? 0f : num);
				float b = Mathf.Clamp01(num * 0.01f);
				_throttlePosition = Mathf.Max(_userThrottleInput, b);
			}
		}

		private IEnumerator RevLimiterCoroutine()
		{
			if (revLimiterActive || engineType == EngineType.Electric || revLimiterCutoffDuration == 0f)
			{
				yield return null;
			}
			revLimiterActive = true;
			onRevLimiter.Invoke();
			yield return new WaitForSeconds(revLimiterCutoffDuration);
			revLimiterActive = false;
		}

		private IEnumerator StarterCoroutine()
		{
			if (engineType == EngineType.Electric || starterActive)
			{
				yield return null;
			}
			float startTimer = 0f;
			starterActive = true;
			if (startDuration < 0.1f)
			{
				startDuration = 0.1f;
			}
			_starterTorque = (_idleAngularVelocity - outputAngularVelocity) * inertia / startDuration;
			while (startTimer <= startDuration)
			{
				startTimer += 0.1f;
				yield return new WaitForSeconds(0.1f);
			}
			_starterTorque = 0f;
			starterActive = false;
			if (outputAngularVelocity < _stallAngularVelocity)
			{
				StopEngine();
			}
		}

		public void IntegrateDownwards(float dt)
		{
			if (dt == 0f)
			{
				Debug.LogError("Dt is 0!");
				return;
			}
			_prevDamage = _damage;
			_wasRunning = _isRunning;
			_userThrottleInput = vehicleController.input.InputSwappedThrottle;
			_throttlePosition = _userThrottleInput;
			_idleAngularVelocity = UnitConverter.RPMToAngularVelocity(idleRPM);
			_stallAngularVelocity = UnitConverter.RPMToAngularVelocity(stallRPM);
			_revLimiterAngularVelocity = UnitConverter.RPMToAngularVelocity(revLimiterRPM);
			_prevAngularVelocity = outputAngularVelocity;
			bool flag = SumRunModifiers();
			_isRunning = ignition && flag && _damage < 1f && !IsStalled;
			if (_wasRunning && !_isRunning)
			{
				StopEngine();
			}
			else if (vehicleController.input.EngineStartStop)
			{
				StartStopEngine();
				vehicleController.input.EngineStartStop = false;
			}
			if (autoStartOnThrottle && !IsRunning && _userThrottleInput > 0.2f && _damage < 0.999f)
			{
				StartEngine();
			}
			_powerModifierSum = (_isRunning ? SumPowerModifiers() : 0f);
			forcedInduction.Update(this);
			if (outputNameHash != 0)
			{
				float num = _output.QueryInertia();
				float num2 = inertia + num;
				if (num2 == 0f)
				{
					Debug.LogError("Inertia Sum can not be 0!");
					return;
				}
				float num3 = QueryAngularVelocity(outputAngularVelocity, dt);
				float num4 = inertia / num2 * outputAngularVelocity + num / num2 * num3;
				float torque = calculateTorqueDelegate(outputAngularVelocity, dt);
				generatedPower = PowertrainComponent.TorqueToPowerInKW(in outputAngularVelocity, in torque);
				float num5 = (num4 - outputAngularVelocity) * inertia / dt;
				outputTorque = torque - num5;
				float num6 = ForwardStep(outputTorque, 0f, dt);
				float num7 = torque + num6 + num5;
				outputAngularVelocity += num7 / num2 * dt;
				float min = 0f;
				float max = _revLimiterAngularVelocity * 1.05f;
				outputAngularVelocity = Mathf.Clamp(outputAngularVelocity, min, max);
				_rpmPercent = Mathf.Clamp01(outputAngularVelocity / _revLimiterAngularVelocity);
				_load = Mathf.Clamp01(generatedPower / (maxPower * (forcedInduction.useForcedInduction ? forcedInduction.powerGainMultiplier : 1f)));
			}
		}

		public void StartEngine()
		{
			ignition = true;
			if (_damage >= 1f)
			{
				return;
			}
			onStart.Invoke();
			if (engineType != EngineType.Electric)
			{
				if (flyingStartEnabled)
				{
					FlyingStart();
				}
				else if (!starterActive && vehicleController != null)
				{
					_starterCoroutine = vehicleController.StartCoroutine(StarterCoroutine());
				}
			}
		}

		private void FlyingStart()
		{
			ignition = true;
			starterActive = false;
			outputAngularVelocity = UnitConverter.RPMToAngularVelocity(idleRPM);
		}

		public void StopEngine()
		{
			if (_starterCoroutine != null && vehicleController != null)
			{
				vehicleController.StopCoroutine(_starterCoroutine);
			}
			ignition = false;
			_starterTorque = 0f;
			_throttlePosition = 0f;
			_userThrottleInput = 0f;
			_powerModifierSum = 0f;
			_load = 0f;
			starterActive = false;
			onStop.Invoke();
		}

		private float SumPowerModifiers()
		{
			if (powerModifiers.Count == 0)
			{
				return 1f;
			}
			float num = 1f;
			int count = powerModifiers.Count;
			for (int i = 0; i < count; i++)
			{
				num *= powerModifiers[i]();
			}
			return Mathf.Clamp(num, 0f, 1f / 0f);
		}

		private bool SumRunModifiers()
		{
			if (runModifiers.Count == 0)
			{
				return true;
			}
			bool flag = true;
			int count = runModifiers.Count;
			for (int i = 0; i < count; i++)
			{
				flag &= runModifiers[i]();
				if (!flag)
				{
					break;
				}
			}
			return flag;
		}

		public void GetPeakTorque(out float peakTorque, out float peakTorqueRpm)
		{
			peakTorque = 0f;
			peakTorqueRpm = 0f;
			for (float num = 0.05f; num < 1f; num += 0.05f)
			{
				float num2 = num * revLimiterRPM;
				float num3 = powerCurve.Evaluate(num) * maxPower;
				if (!(num2 < idleRPM))
				{
					float num4 = UnitConverter.RPMToAngularVelocity(num2);
					float num5 = num3 * 1000f / num4;
					if (num5 > peakTorque)
					{
						peakTorque = num5;
						peakTorqueRpm = num2;
					}
				}
			}
			float num6 = (forcedInduction.useForcedInduction ? forcedInduction.powerGainMultiplier : 1f);
			peakTorque *= num6;
		}

		public void GetPeakPower(out float peakPower, out float peakPowerRpm)
		{
			float num = 0f;
			float num2 = 1f;
			for (float num3 = 0f; num3 < 1f; num3 += 0.05f)
			{
				float num4 = powerCurve.Evaluate(num3);
				if (num4 > num)
				{
					num = num4;
					num2 = num3;
				}
			}
			float num5 = (forcedInduction.useForcedInduction ? forcedInduction.powerGainMultiplier : 1f);
			peakPower = num * maxPower * num5;
			peakPowerRpm = num2 * revLimiterRPM;
		}
	}
}
