namespace Concentus.Enums
{
	public enum OpusApplication
	{
		OPUS_APPLICATION_UNIMPLEMENTED = 0,
		OPUS_APPLICATION_VOIP = 2048,
		OPUS_APPLICATION_AUDIO = 2049,
		OPUS_APPLICATION_RESTRICTED_LOWDELAY = 2051
	}
}
