namespace Concentus.Enums
{
	public enum OpusBandwidth
	{
		OPUS_BANDWIDTH_AUTO = -1000,
		OPUS_BANDWIDTH_NARROWBAND = 1101,
		OPUS_BANDWIDTH_MEDIUMBAND = 1102,
		OPUS_BANDWIDTH_WIDEBAND = 1103,
		OPUS_BANDWIDTH_SUPERWIDEBAND = 1104,
		OPUS_BANDWIDTH_FULLBAND = 1105
	}
}
