using Rewired.Internal.Localization;

namespace Rewired.Interfaces
{
	[CustomObfuscation(rename = false)]
	[CustomClassObfuscation(renamePrivateMembers = false, renamePubIntMembers = false)]
	internal interface IControllerElementIdentifierCommon_Internal
	{
		int id { get; }

		string name { get; }

		string positiveName { get; }

		string negativeName { get; }

		string nonLocalizedName { get; }

		string nonLocalizedPositiveName { get; }

		string nonLocalizedNegativeName { get; }

		string key { get; }

		string positiveKey { get; }

		string negativeKey { get; }

		bool isNonLocalizedPositiveNameAutoGenerated { get; }

		bool isNonLocalizedNegativeNameAutoGenerated { get; }

		bool isPositiveKeyAutoGenerated { get; }

		bool isNegativeKeyAutoGenerated { get; }

		DeviceLocalizationInfo deviceLocalizationInfo { get; }

		object elementType { get; }

		bool useEditorElementTypeOverride { get; }

		ControllerElementType editorElementTypeOverride { get; }

		string GetSpecialElementNonLocalizedName(int index);

		string GetSpecialElementKey(int index);
	}
}
